### ISSUE TITLE
Don't rely on system icon theme for appmenu icon by default

### ISSUE THREAD

**Issue by serebit** [BuddiesOfBudgie/budgie-desktop#10]
Putting here as a sort of RFC. Currently, stock budgie uses Adwaita by default due to gschema defaults, and the foot that's displayed as an appmenu icon in Adwaita isn't the best impression for new users. We're not GNOME, and the panel should reflect that.

### Proposal
Use the Papirus appmenu icon or similar as a custom appmenu image by default, leveraging the current functionality to set a custom appmenu icon. If users wish to use their theme's appmenu icon, they can remove the custom image. Alternatively, we could add a switch to Budgie Desktop Settings dedicated to using the appmenu icon from the theme rather than the custom one.

**Comment by fossfreedom** [comment]
I would support this.

In terms of practicability the License for such a logo should match https://github.com/BuddiesOfBudgie/budgie-desktop/tree/master/data/icons I.e. GPL2/2+ or CC BY SA 4.0

Or just simply default to the budgie logo

https://github.com/BuddiesOfBudgie/budgie-desktop/blob/master/data/icons/apps/budgie-desktop-symbolic.svg

**Comment by serebit** [comment]
Accepting as per discussion on IRC. Plan is to create our own start-here-symbolic icon for use with the appmenu, with a design similar to most other icon themes (grid of boxes). Should be a smooth transition for those using Solus theming.

**Comment by glow12121** [comment]
> and the foot that's displayed as an appmenu icon in Adwaita isn't the best impression for new users

It's true.
