### ISSUE TITLE
Changing themes through Budgie Desktop Settings does not change title bar's theme unless the session or window manager restarts

### ISSUE THREAD

**Issue by abembritishav** [BuddiesOfBudgie/budgie-desktop#101]
## Description
After changing themes via the Desktop Settings, the title bar from window manager does not updated to change from previous theme until the session is restarted, or replacing window manager (via budgie-wm --replace.)

So far, apps using GTK headerbar or CSD decoration are unaffected. Elements that wasn't managed by Budgie's window manager, such as menu bar are not affected by this issue.

## Budgie version
budgie-desktop 10.6.1

## Operating system
Debian testing (Debian 12)

## Steps to reproduce the issue
Using Budgie Desktop Settings to switch between themes. For example, switching between light and dark variants of the same theme can should produce where the light or dark version of title bar stay

## Actual result
![Screenshot from 2022-04-07 10-31-36](https://user-images.githubusercontent.com/75411083/162114792-8e4e9556-5364-45bd-9c81-2e5b648736f8.png)

## Expected result
Changing themes should also change the window manager's title bar theme. For the theme I'm using it should change synaptic's title bar to white/black scheme.

## Additional information
None at the moment.

**Comment by JoshStrobl** [comment]
This isn't a Budgie issue. More a GTKism.
