### ISSUE TITLE
Can't see symlinks on samba or sftp file shares

### ISSUE THREAD

**Issue by Hew-ux** [BuddiesOfBudgie/budgie-desktop#104]
## Description
Using the default file manager, Nautilus, symlinks in network file shares are not visible: 
![image](https://user-images.githubusercontent.com/67527064/162346131-dc3e3691-629d-48c6-9204-e70f00462ced.png)

These are visible from other computers on my network such as my Raspberry Pi and Windows (very ironically):
![image](https://user-images.githubusercontent.com/67527064/162346167-0ef88ee9-5dfd-4f6d-8e4f-04b0bfa1b02e.png)

## Budgie version
budgie-desktop 10.6
Copyright © 2014-2022 Budgie Desktop Developers

## Operating system
Solus 4.3 Fortitude

## Steps to reproduce the issue
  - On another computer on the network, setup a network share that contains symlinks. In this case, I have Batocera installed which by default opens a network share which contains symlinks.
  - On Solus, open file manager and navigate to "Other locations".
  - Click on your network share.
  - Navigate to the symlinks.

## Actual result
The symlinks do not appear in the file manager at all.

## Expected result
To be able to see and manipulate them as I would any other system.

## Additional information
I've been informed by my colleague who used Solus in the past for this exact same purpose (editing symlinks on the network share created on a Batocera installation) that this used to work fine. So I'm lead to believe this is a regression, hence why I'm reporting it now.

**Comment by serebit** [comment]
While most distributions that ship Budgie use Nautilus as the default file manager, we don't actually have any specific recommendations for default file managers. 

In any case, this appears to be a Nautilus-specific issue, which is up to the GNOME developers to fix, or you can poke the Solus developers about shipping a patch.

Nautilus bug tracker is here: https://gitlab.gnome.org/GNOME/nautilus/-/issues
Solus dev tracker is here: https://dev.getsol.us/

Closing as wontfix.

**Comment by Hew-ux** [comment]
Ah okay, thanks for the directions.
