### ISSUE TITLE
Spotify from Flatpak doesn't show on bottom panel

### ISSUE THREAD

**Issue by Mark12870** [BuddiesOfBudgie/budgie-desktop#105]
## Description
On Solus Budgie, when I start Spotify installed over Flatpak, it doesn't show on Bottom panel. The same thing is also happening with Flatpak version of Tuxguitar.

## Budgie version
10.6.1

## Operating system
Solus 4.3 Fortitude

## Steps to reproduce the issue
1. Install Spotify from Flathub
2. Open Spotify

## Actual result
Spotify icon doesn' show on bottom panel.
![image](https://user-images.githubusercontent.com/32600962/162638147-6158734b-87a0-4704-beaa-08887d1838c2.png)

## Expected result
Spotify icon shows on bottom panel as other applications.

## Additional information
Here is the start log from Spotify:

```
marek@marek-pc ~ $ flatpak run com.spotify.Client
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
marek@marek-pc ~ $ [spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
Traceback (most recent call last):
  File "/app/bin/set-dark-theme-variant.py", line 11, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.9/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":99.0": b'Invalid MIT-MAGIC-COOKIE-1 key'
Gtk-Message: 17:40:32.006: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:40:32.006: Failed to load module "canberra-gtk-module"
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[spotifywm] attached to spotify
[spotifywm] spotify window found
marek@marek-pc ~ $
```

Also already posted here: https://dev.getsol.us/T10230

**Comment by JoshStrobl** [comment]
Can confirm that on my local system that it does not appear when launched and not pinned. If Spotify is pinned, it will be tracked correctly.

As a temporary workaround @Mark12870, open up Budgie Menu, type Spotify, then drag the item into IconTasklist. Once you have done that, you can launch it from there.

**Comment by serebit** [comment]
Postal 2 also doesn't show up.

**Comment by elusian** [comment]
I have this issue in a few applications, but I noticed that it is selective:
* in Firefox, the main window is accounted for, but if I open for example the history window it is not shown in the IconTaskList
* Thunderbird is shown in the IconTaskList, but only if it is the first window of its stack. If I start writing a new mail (which is a new window), hide the main window (through birdtray) and then reopen it, the main window is not shown in the IconTaskList
* MPV is shown only if it is displaying video (including songs with a background image). Songs with no video are not shown in the IconTaskList

OS is Solus 4.3, updated a few days ago. Budgie is at version 10.6.1
I hope this helps.
