### ISSUE TITLE
Workspace applet: apps icons no longer visible

### ISSUE THREAD

**Issue by Solarunit** [BuddiesOfBudgie/budgie-desktop#106]
## Description

Apps icons no longer visible in the Workspace switcher applet when the size of the Panel is relatively small. 
You can't see 2 icons at the same time like it was before.

## Budgie version

budgie-desktop 10.6.1

## Operating system

Solus

## Steps to reproduce the issue

- Panel at the bottom
- Panel size: 34 <-- This is important I guess
- two open apps on a single workspace

## Actual result

I see just `+2` 

![](https://i.imgur.com/OAEtIaC.png)

## Expected result

It would be nice to see at least 2 icons. IIRC it was possible before 10.6 update.
Icons are important because you can quickly d&d them to another workspace.

**Comment by serebit** [comment]
I'm seeing this on latest git master on EndeavourOS, with a bit of inconsistency with respect to whether any application icons are shown. It appears to switch to `+2` when sizing down to 32 pixels in height, and it appears to switch back to icons when sizing up to 38 pixels in height. I'll see what I can do to fix this.
