### ISSUE TITLE
Workspace applet: dead pixels at the bottom

### ISSUE THREAD

**Issue by Solarunit** [BuddiesOfBudgie/budgie-desktop#108]
## Description

It's impossible to switch to the another workspace when the cursor at the edge of the screen

## Budgie version

budgie-desktop 10.6.1

## Operating system

Solus

## Steps to reproduce the issue

- try to switch to the another workspace when the cursor at the edge of the screen

## Actual result

dead pixels at the bottom

## Expected result

No dead pixels, same behavior when you click on the icons on the Panel or Menu button.

**Comment by JoshStrobl** [comment]
What theme are you using?
