### ISSUE TITLE
Applications in tray leaking memory

### ISSUE THREAD

**Issue by elusian** [BuddiesOfBudgie/budgie-desktop#111]
## Description
Since the update to 10.6, I noticed that some applications with a status indicator are leaking memory and end up consuming GB of memory after a few hours of use. 
I noticed this happening in particular with telegram-desktop and birdtray (status indicator for thunderbird)

## Budgie version
Currently 10.6.1 but issue is be older (10.6). This did not happen in the 10.5.* series

## Operating system
Solus 4.3

## Steps to reproduce the issue
Open telegram or birdtray, leave them alone for a few hours, check memory usage

## Actual result
Both applications consume a large amount of memory. In case of birdtray that memory is _just_ for the status indicator, since thunderbird is a separate process

## Expected result
No significant memory increase

## Additional information
Both applications were installed via flatpak, unsure if relevant.
Let me know if I can provide additional information

**Comment by serebit** [comment]
No source code changes were made to the system tray between v10.5.3 and v10.6. Still worth looking into, though.

**Comment by JoshStrobl** [comment]
Going to close this as we are not handling this in any special way. It is the application that provides these icons. In the case of Birdtray, there is even an upstream issue on it.

https://github.com/gyunaev/birdtray/issues/478

**Comment by elusian** [comment]
Thank you for the link. 
I apologize for the incorrect issue, I was thrown off by multiple application showing the same problem, but it seems it may have been a coincidence. I'll have to try to solve it for telegram.
