### ISSUE TITLE
Unable to disable sticky edges

### ISSUE THREAD

**Issue by TroyHernandez** [BuddiesOfBudgie/budgie-desktop#112]
# Description

I'm unable to find/turn off sticky edges. I've tried settings, tweaks, [ccsm as described here](https://askubuntu.com/a/725289).

To add to the complication, I'm using the Synergy virtual KVM hosted on another ubuntu machine. The Budgie desktop is in the "middle" with the Ubuntu host to the "right" and a RHEL machine to the "left". There is no sticky edge between the RHEL and Budgie screen, but there is between the Budgie and Ubuntu machine. Additionally, the app dock is also sticky.

# Operating system

Ubuntu Budgie 21.10

# Actual result

The edges are sticky.

# Expected result

A functional option to disable sticky edges/dock

# Additional information

**Comment by serebit** [comment]
Are you referring to windows sticking in place when one of their edges touches the edge of a monitor or the edge of a panel? If so, that's a behavior that's dictated by [Mutter](https://gitlab.gnome.org/GNOME/mutter) (relevant source file [here](https://gitlab.gnome.org/GNOME/mutter/-/blob/main/src/core/edge-resistance.c), and isn't something we can change on our end. I would recommend filing an issue on the Mutter GitLab if you'd like to see this option exposed via tweaks or dconf.

**Comment by TroyHernandez** [comment]
I'm referring to the cursor sticking on the dock and edge when hovering over/near it.

**Comment by serebit** [comment]
Could you record a video with OBS or simple-screen-recorder so I can see what you're talking about? I'm not sure I understand.

**Comment by JoshStrobl** [comment]
@TroyHernandez Are you using a Budgie panel in Dock Mode or Plank? Because we don't develop Plank.

**Comment by TroyHernandez** [comment]
I wasn't using Plank, but I was using Synergy. Sorry I can't make a video because my HP Spectre crashed out on the 22.04 upgrade.
