### ISSUE TITLE
Budgie doesn't render properly

### ISSUE THREAD

**Issue by tiagodinis33** [BuddiesOfBudgie/budgie-desktop#115]
## Description

I had installed budgie on arch linux today, and it just doesn't work, the screen is black, and it has some red pixels

## Budgie version

budgie-desktop 10.6.1 (git-04839d95cad1671dfdfb7cd5ddefcb5a2f31c56f)

## Operating system

Arch Linux

## Actual result
![image](https://cdn.discordapp.com/attachments/848349994082893884/969687310398525471/20220429_204238.jpg)

## Expected result
Render the screen properly with the correct colors

## Additional information
I'm using GDM as the display manager, probably doesn't matter, but idk
i have vannila gnome and dwm installed too and they work properly so it's definitely budgie

**Comment by JoshStrobl** [comment]
Need logs in order to debug this. I would recommend switching to TTY and getting logs via journalctl.

**Comment by tiagodinis33** [comment]
The logs are too big so:
https://tastebin.vercel.app/c20b75ba-f48a-474d-92ef-7d8858b961e5

**Comment by tiagodinis33** [comment]
I was just using a bad color profile, nvm
