### ISSUE TITLE
What are our supported Notification options

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#117]
## Description
In budgie control center we have this dialog for each application

![image](https://user-images.githubusercontent.com/996240/166142768-df70f9ce-1fc6-42f9-823e-12a1fc443bbf.png)

End user is reporting that

## Budgie version
BCC 1.0
Budgie Desktop v10.6.1

## Operating system
Ubuntu Budgie 22.04

## Steps to reproduce the issue
Enable notification sound for an application e.g. network applet
Wait until that app produces a notification - e.g. disconnect / reconnect a network

## Actual result
No sound for a notification

## Expected result
That's the question ... if we don't support sounds then the BCC dialog needs to be adjusted.  What needs to be removed?
If we do - then we need to tweak the notifications stuff in budgie

**Comment by EbonJaeger** [comment]
At the moment, only Notifications and Notification Popups are checked. I think supporting the Show Message Content option would be worthwhile. It shouldn't be too difficult to support sounds as well with the new notifications stuff, either.

**Comment by fossfreedom** [comment]
Ah. Excellent.  Cheers.
