### ISSUE TITLE
notifications regression: NotificationClosed emitted with wrong type

### ISSUE THREAD

**Issue by The-Compiler** [BuddiesOfBudgie/budgie-desktop#118]
## Description

When a notification is closed, `NotificationClosed` is emitted with `uint32, int32` as arguments (id, reason) while the [specification](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#signals) mandates uint32 for both.

## Budgie version
budgie-desktop 10.6.1

This seems to be a recent regression: On a fresh Solus 4.3 install I can't reproduce, only after a full update.

## Operating system
Solus 4.3

## Steps to reproduce the issue

- Run `dbus-monitor interface=org.freedesktop.Notifications`
- Trigger a notification, e.g. by running `notify-send foo` in another terminal

## Actual result

```
signal time=1651502524.321176 sender=:1.42 -> destination=(null destination) serial=73 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 2
   int32 2
 ```

## Expected result

`uint32 2` for both arguments

## Additional information

This currently causes [qutebrowser](https://www.qutebrowser.org/) to crash when a notification is closed - will add a workaround there too.

**Comment by EbonJaeger** [comment]
I neglected to realize that enum values are `int32` not `uint32`. Just made a PR to fix that. Sorry for the inconvenience!
