### ISSUE TITLE
Clicking on the "Calendar" menu item of the "Clock" applet opens empty documents in default text editor instead of calendar

### ISSUE THREAD

**Issue by rm1984** [BuddiesOfBudgie/budgie-desktop#121]
## Description
I have the "Clock" applet in my top panel, and when I click on it and then I click on "Calendar", it opens two new empty documents in my text editor instead of opening the calendar.

## Budgie version
`budgie-desktop 10.6.1`

## Operating system
```
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2022.2
Codename:	kali-rolling
```

## Steps to reproduce the issue
1) Add the "Clock" applet to a panel
2) Click on the time/date string on the applet
3) Click on "Calendar" item on the popup menu
4) It opens two new empty documents in the default text editor instead of opening the calendar

## Actual result
![Screenshot from 2022-05-12 18-00-10](https://user-images.githubusercontent.com/10762991/168118671-86d2692b-a7be-4d7e-aa06-e892ae1f0826.png)

## Expected result
Right opening of the calendar

## Additional information
```
budgie-app-launcher-applet       1.4.0-1
budgie-applications-menu-applet  1.4.0-1
budgie-clockworks-applet         1.4.0-1
budgie-control-center            1.0.1-2
budgie-control-center-data       1.0.1-2
budgie-core                      10.6.1-1
budgie-desktop                   10.6.1-1
budgie-desktop-view              1.2-1
budgie-extras-common             1.4.0-1
budgie-extras-daemon             1.4.0-1
budgie-fuzzyclock-applet         1.4.0-1
budgie-hotcorners-applet         1.4.0-1
budgie-indicator-applet          0.7.2-2
budgie-network-manager-applet    1.4.0-1
budgie-previews                  1.4.0-1
budgie-showtime-applet           1.4.0-1
gir1.2-budgie-1.0                10.6.1-1
libbudgie-plugin0                10.6.1-1
libbudgie-private0               10.6.1-1
libbudgietheme0                  10.6.1-1
libraven0                        10.6.1-1
```

**Comment by EbonJaeger** [comment]
Looks like this will be removed in the next version of Budgie, because as [this commit]9https://github.com/BuddiesOfBudgie/budgie-desktop/commit/7b3ed6f0536fe46b2300b075bb7cb2573b91cfec) says:
> Unfortunately AppInfo get_default_for_type had the tendency to provide applications that did not really handle text/calendar, such as gedit, resulting in user confusion. Since the underlying struct of DesktopAppInfo and AppInto do not expose MimeType, we cannot perform validation of the mimetypes to dynamically hide the button. So, just remove it.
