### ISSUE TITLE
Incorrect title label for Firefox

### ISSUE THREAD

**Issue by solomongrundy6** [BuddiesOfBudgie/budgie-desktop#126]
## Description

This may be related to the other issues with the icon tasklist at the moment, but I thought I should mention it.  Frequently when hovering over my Firefox icon in the taskbar, it will have the wrong title popup appear above it.  Most recently it referenced a Firefox window that had been open hours ago (and Firefox had closed and reopened several times in the interim.)

## Budgie version

budgie-desktop 10.6.1

## Operating system

Solus Budgie

## Steps to reproduce the issue

Hover your mouse over a Firefox icon in your Icon Tasklist

## Actual result

Tooltip shows title of a Firefox window from earlier, sometimes hours ago.

## Expected result
Tooltip shows current window title.

## Additional information
I'll note here that I'm using the Firefox in Solus' main repository and not a flatpak.

**Comment by guillotjulien** [comment]
@solomongrundy6 do you have the Firefox icon pinned in the task list?

**Comment by solomongrundy6** [comment]
Yes

**Comment by Solarunit** [comment]
Maybe it's related. Often tooltips are not centered and even in the wrong location:

![cropped](https://user-images.githubusercontent.com/20891064/169024498-40b5526c-6f7f-42d2-b4fe-181feb19efe5.jpg)

**Comment by serebit** [comment]
Tooltip location weirdness is down to GTK3. Also this may be fixed with 14b685b.

**Comment by serebit** [comment]
I'm going to mark this as verified, given that I've seen this too. I'm pretty sure this is fixed with 14b685b and 81e3821, since that specifically addresses pinned apps and ensuring that their tooltips stay updated, so I'm going to close this as completed. 

If you're still seeing this behavior in the next release of Budgie, comment here and I'll reopen it.
