### ISSUE TITLE
Applications not launching on the correct GPU

### ISSUE THREAD

**Issue by LinUwUxCat** [BuddiesOfBudgie/budgie-desktop#127]
## Description

I have a dual-GPU optimus laptop. On GNOME, applications are launched on the iGPU (here, intel iRIS Xe) as default and on the dGPU (here, NVIDIA MX450) when the .desktop file includes the line `PrefersNonDefaultGPU=true`. On budgie, everything launches on the iGPU no matter what, leaving me with poor performance in games.

## Budgie version

budgie-desktop 10.6.1

## Operating system

Pop!_OS 22.04

## Steps to reproduce the issue

1 : Be in hybrid mode (Pop!_OS has multiple modes, hybrid is the default one with both cards activated)
2 : Launch any application that has the line `PrefersNonDefaultGPU=true` in their .desktop file

## Actual result

Observe (with e.g. `nvtop`) that the application was launched with the wrong GPU

## Expected result
The application should launch on the NVIDIA GPU if it has the corresponding line.

## Additional information
I use proprietary NVIDIA drivers, version 510.68.02.

**Comment by EbonJaeger** [comment]
This should be fixed in the upcoming menu rewrite as long as Switcheroo is installed.

**Comment by LinUwUxCat** [comment]
I see. I have no clue what switcheroo is tho, so what's that?

**Comment by EbonJaeger** [comment]
https://gitlab.freedesktop.org/hadess/switcheroo-control/
> D-Bus service to check the availability of dual-GPU

It's an agnostic way to check the capability to use dual-GPU setups. It's in the Ubuntu repos, so it should be available on Pop!_OS if it's not installed already.

**Comment by LinUwUxCat** [comment]
It is installed indeed. I'll wait for the rewrite now, thanks!
