### ISSUE TITLE
Option to enable Adaptive Sync/VRR/Freesync

### ISSUE THREAD

**Issue by ghost** [BuddiesOfBudgie/budgie-desktop#133]
**Current Budgie version**
10.6.1

**Use-cases**
Adaptive Sync/VRR/Freesync makes your refresh rate fluctuate with the framerate of full screen applications. It makes playing games at low framerates feel much smoother and responsive, helps with tearing, and in general is extremely convenient to have the option- especially considering how having a monitor that supports Freesync but an OS that doesn't can cause issues, at least with gameplay recording. VariableRefresh is very easy to enable on xorg. On Wayland, only Plasma & Sway has it figured out, as Gnome [still has issues with it.](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1154)

**Proposal**
A simple on and off switch that applies [this](https://wiki.archlinux.org/title/Variable_refresh_rate#Xorg_configuration)

On Plasma Wayland, the option shows up under Display settings the moment it detects vrr_capable=1 (I require Displayport in my case) I'm aware that Wayland is the plan for Budgie's future, very glad about that. Can we also be the only non-Plasma Wayland DE to have adaptive sync support built in? Freesync monitors are very common, it's a hardware requirement that is a sore spot on Linux and would definitely come in handy, and help set us apart. I use Budgie on Solus and currently have VRR enabled with the amdgpu config, it works great.

**References**

![image](https://user-images.githubusercontent.com/106335362/170528105-375e718e-c2ba-44f7-8d17-41a2185dab77.png)
![Screenshot from 2022-05-26 11-07-27](https://user-images.githubusercontent.com/106335362/170528376-14f43a09-d0f2-4ae1-94fe-c6911b5e6e4a.png)
[Gnome merge request, unsuccessful](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1154)
[Working Xorg config](https://wiki.archlinux.org/title/Variable_refresh_rate#Xorg_configuration)

**Comment by JoshStrobl** [comment]
Closing as per my [write-up](https://blog.buddiesofbudgie.org/state-of-the-budgie-may-2022/), VRR and the likes are already planned. We do not need a tracking item for this in budgie-desktop as this repo will not be used for Budgie 11's WM.

This can't be supported until we implement our new Wayland-based WM.

**Comment by serebit** [comment]
Additionally, kernel 5.18 has Freesync enabled by default on compatible AMD GPUs, so this won't be something that requires manual configuration once that starts landing in more repos.

**Comment by DeN-AlB** [comment]
Just a short question: Since Budgie 10.9 Wayland seems to be supported. Is VRR / Adaptive sync support included already?

I think about switching from Gnome to Budgie, and it would be great to have support for VRR / Adaptive sync also.

**Comment by serebit** [comment]
Budgie 10.9 is still X11 only.

**Comment by DeN-AlB** [comment]
Good to know! Thanks, @serebit . :+1:
