### ISSUE TITLE
Untranslated strings in the Budgie Desktop Settings (French language)

### ISSUE THREAD

**Issue by roxfr** [BuddiesOfBudgie/budgie-desktop#135]
Budgie Version : 10.6.1
OS : Ubuntu 22.04 LTS
Display server : X11

Hello,
There are untranslated strings (French language) in the Budgie Desktop Settings (for the panel).
See attached images.
Regards,
Roxfr

![Budgie_Desktop_Settings_-_Applets_01](https://user-images.githubusercontent.com/52124613/170833957-b63ae7d2-8e12-48d7-8fc0-252c279db973.jpg)

**Comment by JoshStrobl** [comment]
More appropriate for Transifex: https://www.transifex.com/buddiesofbudgie/budgie-10/

**Comment by roxfr** [comment]
> More appropriate for Transifex: https://www.transifex.com/buddiesofbudgie/budgie-10/

Budgie is 100% translated into French for this part but maybe its strings can't be translated?

![Transifex_Budgie_French_100_pourcent](https://user-images.githubusercontent.com/52124613/170835054-7f42b60e-b7ef-4cea-b6d1-6e448fbb7ed7.jpg)

**Comment by roxfr** [comment]
> More appropriate for Transifex: https://www.transifex.com/buddiesofbudgie/budgie-10/

![budgie-desktop_po_fr po](https://user-images.githubusercontent.com/52124613/170835209-9d771051-8751-4e20-bc33-fcb80b917d76.jpg)

**Comment by fossfreedom** [comment]
@roxfr the name of the plugin is not translated.  The description of the plugin should be translatable.

**Comment by roxfr** [comment]
> @roxfr the name of the plugin is not translated. The description of the plugin should be translatable.

@fossfreedom Could you tell me where is it, please.

**Comment by fossfreedom** [comment]
The screenshot you have lists the applets on your panel. Those are the names of the applets. These are not translatable.

**Comment by roxfr** [comment]
Ha ok, thank you for your answer.
