### ISSUE TITLE
Custom Keyboard Shortcut for 'Switch applications' is Disabled after Logout / Restart

### ISSUE THREAD

**Issue by chaibronz** [BuddiesOfBudgie/budgie-desktop#136]
## Description
In Budgie Control Center I set 'super + tab' as my keyboard shortcut to 'switch applications'. After I logout or restart my system, the 'switch applications' shortcut becomes disabled. 

## Budgie version
1.0.0

## Operating system
openSUSE Tumbleweed

## Steps to reproduce the issue
- Open Budgie Control Center
- click on the 'Keyboard' category
- under 'Keyboard Shortcuts' select 'View and Customize Shortcuts'
- select the 'Navigation' category
- click the 'Switch applications' shortcut
- set 'super + tab' as the keyboard shortcut
- enjoy using 'super + tab' to switch through your applications
- logout or restart
- notice that 'super + tab' isn't functioning anymore
- navigate back to Keyboard Shortcuts and see that 'Switch applications' is now Disabled   

## Actual result
'Switch applications' shortcut is Disabled after logout / restart

## Expected result
'Switch applications' shortcut not Disabled after logout / restart (unless you have disabled it beforehand)

## Additional information
- I've set up and changed several keyboard shortcuts and from what I can tell this only happens for 'Switch applications'.  

- (this may be important) I'm using openSUSE Tumbleweed where I have installed and removed several Desktop Environments and Window Managers over the year. I can understand if this behavior somehow led to this issue. If someone can test the above on their end and simply confirm everything is working as expected I'd be happy to chalk this up to a user-specific issue and consider it closed.

**Comment by fossfreedom** [comment]
Actually found the issue - its because budgie-extras-daemon is doing the reset - nothing to-do with budgie-desktop.  I'll close this here - it needs raising here https://github.com/ubuntubudgie/budgie-extras
