### ISSUE TITLE
Notification position incorrect after upgrade

### ISSUE THREAD

**Issue by CalmDownMonkey** [BuddiesOfBudgie/budgie-desktop#139]
## Description
Since upgrading Ubuntu Budgie from 21.10 to 22.04 (not sure which version of Budgie Desktop that involves), I have a minor problem with the position of notifications.
I have them set to "bottom right", but they now appear a few inches up the screen instead of in the corner as they used to. Still works fine, just looks odd.

## Budgie version
10.6.1 on Ubuntu Budgie 22.04

## Operating system
Ubuntu Budgie 22.04

## Steps to reproduce the issue
Set notification position to "bottom right"
Receive a notification

## Actual result
Notification appears further up the screen than it should
![image](https://user-images.githubusercontent.com/18017631/172542875-f1df04f9-c6bd-4271-9eb3-0ef774efa4b7.png)

## Expected result
Notification appears at the bottom right of the screen

## Additional information
I don't use any DPI scaling. I use 2540x1440 resolution. Fractional scaling is off.

**Comment by serebit** [comment]
Seeing this on master, looking into it.
