### ISSUE TITLE
Switching Keyboard Layout via Alt+Shift_L doesn't work when Budgie Menu is open

### ISSUE THREAD

**Issue by TheK0tYaRa** [BuddiesOfBudgie/budgie-desktop#140]
## Description
The Budgie Menu prevents layout switching

## Budgie version
budgie-desktop 10.6.1

## Operating system
Solus 4.3 Fortitude

## Steps to reproduce the issue
1) Add additional keyboard layout
2) Open Budgie Menu
3) Try to switch the keyboard layout

## Actual result
Layout doesn't switch

## Expected result
Layout switches

## Additional information
null

**Comment by JoshStrobl** [comment]
Yes this is expected behavior of Budgie Menu. Close the menu and switch your layour, BudgiePopovers will capture input.
