### ISSUE TITLE
[solved] Re-consider EFL? -- never mind, it's coming!

### ISSUE THREAD

**Issue by BeaverTek** [BuddiesOfBudgie/budgie-desktop#141]
### Current Budgie version

I tried some crusty old version in the Ubuntu 20.04 / Bodhi 6.0 HWE repos. Looks like... 10.5.1-6 ubuntu0.2
However, this pertains to Budgie 11, I believe.

### Use-cases

To provide an alternative light weight, beautiful, and fully featured desktop based on EFL.

Personally, I enjoy having at least a secondary DE on each computer that's based on the same toolkit. 
Some reasons:
- In case settings get messed up
- just for a change of scenery 
- simply to check up on things 
- to stay familiar 
- to recommend or troubleshoot to help others

### Proposal

Besides KDE Plasma, there are already multiple Qt based DEs including LXQt, Lumina, and Trinity (TDE). All of which are still actively maintained and developed. 

We don't really need yet another one. I think it would be best to have another choice built from the same foundation as Enlightenment and Moksha but it'd be quite different. I find this to be very appealing and interesting, unlike yet another Qt base which might get lost in the mix and Qt focused devs would be better focusing on the already existing environments and programs.

True variety and choice are imperative. Moving to EFL would solidify and help balance GTK, Qt, and EFL as major DE choices. Choosing between one of two isn't much of a choice. ;) Competition drives innovation, isn't that what they say?

E has proven to be very light on resources yet also has great aesthetics. It's used on novel/embedded devices such as watches and appliances.

From my understanding, it's built on C. Is not no longer common enough?

It has Wayland support.

### References

https://www.enlightenment.org/about-efl
https://events.static.linuxfound.org/sites/events/files/slides/efl_elce_13_0.pdf
https://docs.tizen.org/application/native/guides/ui/efl/getting-started/
https://lumina-desktop.org/
https://www.trinitydesktop.org/

Thank you and keep up the good work either way.

**Comment by EbonJaeger** [comment]
Erm. The plan for Budgie 11 *is* for it to be built with EFL. :D

**Comment by BeaverTek** [comment]
That's what I heard on netcasts and such but then I also saw articles like: https://linuxhint.com/budgie-desktop-qt-replace-gnome/

**Comment by EbonJaeger** [comment]
Ah. The plan when Ikey was still involved (a couple of years ago now, I think) was to move to Qt. More recently, the toolkit scene was re-evaluated and things landed on EFL instead. I think [this blog post](https://joshuastrobl.com/2021/09/14/building-an-alternative-ecosystem/) by Josh has all of that information, and more.

But yeah, we'll be moving to EFL for Budgie 11. :)

**Comment by BeaverTek** [comment]
Oh, awesome! We need to write in to all these news outlets and ask them to append an update to these posts. Maybe it'll stir up some hype and get new people involved in helping out. :D

**Comment by AloneER0** [comment]
But the look and functionality of the Budgie desktop will stay the same right?
