### ISSUE TITLE
X11 Stutter

### ISSUE THREAD

**Issue by IdentifyTajo** [BuddiesOfBudgie/budgie-desktop#143]
Good morning. 
Sorry in advance for not knowing much about Linux and budgie.
My issue consists of windows like steam stuttering when moved around, this is amplified when I'm gaming when the stutter freezes my entire pc for a couple of seconds.
This doesn't happen with Wayland.
My specs: 
i7 11th gen
GTX 1060 6gb
32 GB of ram

I'm using the proprietary Nvidia drivers, tried with Noveau and the stutter seems to be gone but I can't open games because it says directx10 is no longer supported.

Thanks.

**Comment by serebit** [comment]
Josh replied to your question in the Matrix support channel. I would recommend continuing your support request there. Marking as invalid until we've established that this is an issue with Budgie, and not with X or with NVIDIA.
