### ISSUE TITLE
Workspace switcher becomes bigger when using Join Displays

### ISSUE THREAD

**Issue by Solarunit** [BuddiesOfBudgie/budgie-desktop#144]
## Description

Workspace switcher becomes bigger when using Join Displays

![alt text](https://i.imgur.com/DyNaf3N.png)

Single display mode:

![alt text](https://i.imgur.com/MdQTtHz.png)

Join Displays:

![alt text](https://i.imgur.com/auc3rTd.png)

## Budgie version

budgie-desktop 10.6.1

## Operating system

Solus

## Expected result

Workspace switcher shouldn't change

## Additional information

2 monitors setup: 27' 4K and 24' 1080p, scale 200%.
For some reason I can't drag the running Vbox icon to another Workspace.

Also icons are blurry, should I create another issue?

**Comment by serebit** [comment]
Found this bug a few days ago and patched it in master (commit 31eedb7). You should see this behavior gone with v10.6.2, when that releases—if not, comment here and I'll reopen the issue and reinvestigate.

**Comment by Solarunit** [comment]
Hi @serebit!
So I updated today to v10.6.2 and Workspace switcher is 2 times bigger now (with Single Display config):

![alt text](https://i.imgur.com/WFCwY9T.png)

**Comment by Solarunit** [comment]
ping @serebit 
Should I create maybe a new issue?

**Comment by serebit** [comment]
The size is intentional. The old size only allowed 2-3 icons to be visible (3 at maximum, above 3 would show a `+X` indicator for extra windows with only 2 icons to the left of it). If you'd like the size to be adjustable, I'd recommend filing a new issue.

**Comment by Solarunit** [comment]
>The size is intentional. The old size only allowed 2-3 icons to be visible (3 at maximum, above 3 would show a +X indicator for extra windows with only 2 icons to the left of it). 

now it's 4 icons and it occupies a lot of space on the panel especially when you have >2 workspaces.

>If you'd like the size to be adjustable, I'd recommend filing a new issue.

Okay, will do :slightly_smiling_face:
