### ISSUE TITLE
appindexer error on update

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#156]
## Description

```
** (budgie-panel:85076): WARNING **: 15:37:08.991: AppIndex.vala:289: Error enumerating files in desktop-directories: Error opening directory '/home/dad/.local/share/desktop-directories': No such file or directory
```

I spotted the above when performing a `sudo apt update && sudo apt upgrade` on UB 22.10.  I don't have a "desktop-directories" folder - don't believe Ubuntu has ever had folder.  

Thoughts?

## Budgie version
10.6.1 + git commit https://github.com/BuddiesOfBudgie/budgie-desktop/commit/6fd3e1a0c479fb6c3645ce6b939ff002d7753680

## Operating system
UB 22.10

## Steps to reproduce the issue
1. budgie-panel --replace &!
2. `sudo apt update && sudo apt upgrade`

## Actual result
See description

## Expected result
Guessing this is erroneous checking?

**Comment by JoshStrobl** [comment]
This is an intentional warning but could likely be changed to debug instead to reduce noise.
