### ISSUE TITLE
Custom timezone in Clock Applet makes budgie to crash

### ISSUE THREAD

**Issue by hosttry** [BuddiesOfBudgie/budgie-desktop#164]
## Description
When enabling the option to use a custom time zone in the clock applet, budgie crashes and can't display the desktop again, the way I found to restore is entering in a tty, revert that configuration with dconf, reset budgie-panel and reboot.

## Budgie version
budgie-desktop 10.6.2

## Operating system
Solus 4.3 Fortitude

## Steps to reproduce the issue
- Open Budgie Desktop Settings.
- Go to the panels section.
- Select Clock applet.
- Set Custom Timezone to on.
- Desktop crashes at this point.

## Actual result
Budgie Desktop crashes and is unable to show the desktop interface.

## Expected result
Be able to use a custom time zone in the Clock applet without budgie crashing.

## Additional information
I can't search for logs and I wont be able to make more tests because i'm using my pc for my studies.

**Comment by fossfreedom** [comment]
Yep - can reproduce this on UB - the journalctl error is

"Settings schema 'com.solus-project.clock' does not contain a key named 'custom_timezone'"

The schema key is "custom-timezone" - so its a mismatch '_' vs '-' character.

I'll look at the code a tweak.
