### ISSUE TITLE
Super_L + [key] doesn't work correctly as a global shortcut

### ISSUE THREAD

**Issue by VeeBop** [BuddiesOfBudgie/budgie-desktop#169]
## Description
When trying to open [Ulauncher](https://github.com/Ulauncher/Ulauncher) or [guake](https://github.com/Guake/guake) with super+space as the shortcut, space has to be pressed twice in order to toggle the program when using the left super key. This happens with any super_L+[key] combination, not just space, but doesn't occur when using the right super key.

## Budgie version
budgie-desktop 10.6.2

## Operating system
EndeavourOS; Build ID: 2022.06.23

## Steps to reproduce the issue
Assign super+space as the shortcut to open a program that is not in focus that allows it, like Ulauncher or guake. Then hold the left super key and press space twice.

## Actual result
Space has to be pressed twice while the left super key is held down in order to open the application.

## Expected result
Space should only be pressed once with the super key in order to open the application.

## Additional information
Assigning super+space to a shortcut through the budgie control center works as expected. When using super+space as a shortcut in an app requires to be in focus for the shortcut to work, it works as expected. Assigning a shortcut such as ctrl+super+space works as expected. Holding down the left super key takes away focus from the current window until it is released, or if another key is pressed with it.

This issue occurs whether or not the budgie menu applet is in any dock, although I suspect it may still have something to do with the budgie menu. Maybe a fix exists by disabling or changing the left super key as a shortcut to open the menu? I wasn't able to find any way to do that to try it.

**Comment by fossfreedom** [comment]
Super+Space is usually a reserved keyboard shortcut to switch input-sources.

**Comment by ScootTheBoot** [comment]
Sorry, I forgot to mention I disabled that shortcut in the settings. This issue also occurs with keys other than space.

**Comment by serebit** [comment]
Testing on EndeavourOS with latest updates as of today, I can launch `kitty` with Super+Space after clearing the change-input-sources shortcut, no extra presses required. Would you mind re-testing to see if it still doesn't work on your system?

**Comment by ScootTheBoot** [comment]
Sorry about the late response, I don't use my Linux machine terribly often anymore. (And when I did, updating everything was a hassle.) I went back and tried with the latest updates, and I was still having the issue. I also downloaded and tried it on GNOME, and it didn't work there, I'm assuming it's an issue with my machine.
