### ISSUE TITLE
Changig the name of setting apps

### ISSUE THREAD

**Issue by Triplesweet** [BuddiesOfBudgie/budgie-desktop#178]
In my opinion budgie control center is not a good name for 3 reasons
1. It is longet than what it should be imo considering some DEs and even windows just use settings
2.  When someone wants to open the settings app it is a muscle memory to press the super key and write settings, but budgie control center doesn't have setting in its name so it doesn't show and makes the person a little annoyed (it does for me at least)
3.  and budgie control center feels more like an app that controls budgie DE itself rather than the system, after all it is mostly settings for hardware of the system than software side that budgie will interact 

In my opinion you can rename the apps to system settings and desktop settings, I feel this will be easier to understand and solve the search problems as well

**Comment by JoshStrobl** [comment]
Wrong issue tracker.
