### ISSUE TITLE
Workspace Switcher High Memory Usage in Budgie 10.6.3

### ISSUE THREAD

**Issue by GZGavinZhao** [BuddiesOfBudgie/budgie-desktop#180]
## Description

`budgie-panel` consumes a lot of memory when Workspace Switcher is added to the panel.

## Budgie version

10.6.3. I rolled back to 10.6.2 and the problem disappeared, so it seems like 10.6.3 related.

## Operating system

Solus 4.3

## Steps to reproduce the issue

1. Open any system monitor, find the single `budgie-panel` process.
2. Open Budgie Desktop Settings. In Panels, click "add applet" and add a Workspace Switcher to any location in any panel.
3. Watch system monitor and check

## Actual result
The memory usage should not increase (a lot), as in Budgie 10.6.2.

## Expected result
The memory usage continues to increase and doesn't show signs of stopping. An extreme case brought this usage to 9GB.

Also, when I hover my mouse on any of the icons, it flashes repeatedly instead of just lighting up once.

## Additional information
#150 might be related since the reported user also has Workspace Switcher in his applet list and this issue went unresolved. However, he's on 10.6.1, so it also might not be related :P

**Comment by serebit** [comment]
#150 was due to a third-party applet, as detailed in the comments prior to the closure of the issue. I'll check this out and see if I can find anything.

**Comment by nathanpainchaud** [comment]
I didn't notice the high memory usage, but I **did** notice the icons flashing when hovering over them. Also, I'm used to dragging the icons to move programs between workspaces, and that's not working anymore either. I rolled back to 10.6.2 and everything is working as intended.

**Comment by JoshStrobl** [comment]
@nathanpainchaud Those are separate issues and should be filed separately. Deleting comment to keep this on topic.

**Comment by nathanpainchaud** [comment]
@JoshStrobl It's an issue with the workspace switcher mentionned by the original poster himself, so I thought it was relevant to mention, in case it could have helped @serebit figure out what's going on. But I'll let you be the judge of that...
