### ISSUE TITLE
[Feature] Add volume control to Budgie's alert sound effect

### ISSUE THREAD

**Issue by 0x199x** [BuddiesOfBudgie/budgie-desktop#181]
### Current Budgie version
Budgie 10.6.2

### Use-cases
The ability to lower the volume or mute alert sound effects would be a very welcome feature.  The available sound effects aren't terribly pleasant and can get a little annoying at times

An additional button to select a custom sound effect would be helpful also, but volume control & mute at the very least would be nice

### Proposal
Change this:
![image](https://user-images.githubusercontent.com/89231731/187244440-13135229-9c85-432d-b7ce-4334864f2abb.png)

To this:
![image](https://user-images.githubusercontent.com/89231731/187246228-26946c51-3fe5-4a2b-a511-00c3245350dd.png)

**Comment by fossfreedom** [comment]
Isn't that what the system sound bar does?
