### ISSUE TITLE
Workspace Switcher: right click menu doesn't work

### ISSUE THREAD

**Issue by Solarunit** [BuddiesOfBudgie/budgie-desktop#184]
## Description

Right click menu doesn't work, it could appear for a a fraction of a second then vanishes.

## Budgie version

budgie-desktop 10.6.3

## Operating system

Solus

## Steps to reproduce the issue

Right click in the Workspace Switcher applet

**Comment by serebit** [comment]
I've had this happen on Arch and Endeavour. Marked as verified.

**Comment by Solarunit** [comment]
here is related bug - Drag&drop doesn't work: https://github.com/BuddiesOfBudgie/budgie-desktop/issues/182
