### ISSUE TITLE
Switch windows of an app not working with Vivaldi/Chrome browsers

### ISSUE THREAD

**Issue by presianbg** [BuddiesOfBudgie/budgie-desktop#190]
## Description
This shortcut:
![image](https://user-images.githubusercontent.com/2163486/188064912-47159dbe-1784-466f-a6ee-fe7f847f83cf.png)

works with everything I've tested, BUT Vivaldi / Chrome browser.

## Budgie version
- 10.6.4

## Operating system
Solus (up-to-date)

## Steps to reproduce the issue
Open two windows / profiles of Vivaldi / Chrome and try to switch between them with **Alt + `**.

## Actual result
Nothing happens. 
Works with other apps having multiple windows.

## Expected result
Using **Alt + `** should cycle back and forth trough all open Vivaldi / Chrome windows, like with the other apps.

**Comment by JoshStrobl** [comment]
This is not a Budgie-specific issue, but a long-standing issue likely related to the applications or Mutter. For example, here is an issue reported by someone on Ubuntu 20.04 with GNOME Flashback: https://askubuntu.com/questions/1358683/switching-between-windows-of-the-same-application-not-always-working

**Comment by presianbg** [comment]
Ahh... I see, thanks!
