### ISSUE TITLE
Style of window's title-bars

### ISSUE THREAD

**Issue by gucio321** [BuddiesOfBudgie/budgie-desktop#193]
## Description

There is a several types of window's top-bars in the system
one, looks like copy-pasted from gnome-desktop, another one seems to be native budgie-styled

## Budgie version

```console
budgie-desktop 10.5.3
Copyright © 2014-2022 Budgie Desktop Developers
```

## Operating system

Ultramarine OS 36

## Steps to reproduce the issue

- click on the desktop -> `Budgie desktop settings`
- open any system app e.g. calculator

## Actual result

you'll see that one window has a white when the another one dark title bar

## Expected result
the top-bars should look the same

## Additional information
![Screenshot from 2022-09-14 12-11-58](https://user-images.githubusercontent.com/73652197/190127242-665844ec-7b60-40d3-8004-0ab20378e2e0.png)

**Comment by fossfreedom** [comment]
GNOME Calculator and alot of GNOME based apps now use libadwaita which enforces its own styling i.e. budgie cannot change this.  Thus you could in theory change from High Contrast to adwaita to have a "common look" - adwaita though doesn't currently have styling specifically for budgie thus things will look broken.

Best advice is to be selective in your choice of applications - either accept the libadwaita based apps as is - or choose apps based on whether they accept your chosen GTK3/GTK4 or equivalent Qt styling.
