### ISSUE TITLE
Icons don't get removed from icon task list when some apps close?

### ISSUE THREAD

**Issue by mitchellurgero** [BuddiesOfBudgie/budgie-desktop#196]
## Description

Using Steam installed from an RPM
This has happened in other apps, but Steam is the worst. When I run a game and play for  awhile, I close the game and in the icon task list at the bottom the icon is not removed. Other apps, closing them removes the icon unless they are a favorite. Steam is not a favorite. When I turn off Window Grouping there are literally hundreds of "rogue" icons.

## Budgie version
10.5.3

## Operating system
Ultramarine (Based off Fedora 36)

## Steps to reproduce the issue
Open Steam, run game, close game and steam.

## Actual result
Icons for Steam & Steam-launched apps/games do NOT get removed from icon task list.

## Expected result
Icons for closed apps removed from icon task list.

## Additional information

Edit: Looks like I missed this issue from a few months ago and updating my budgie may actually help: https://github.com/BuddiesOfBudgie/budgie-desktop/issues/109

**Comment by serebit** [comment]
Yeah, we've fixed a ton of similar issues with Icon Tasklist in the 10.6 series. I'd recommend updating your version of Budgie and seeing if the issue persists.

**Comment by JoshStrobl** [comment]
Additionally, Budgie Desktop is officially supported starting in Fedora 37, so it may be worth considering switching to Fedora or the official packages when it is released.

I am closing this as you are on a very outdated version of Budgie Desktop.
