### ISSUE TITLE
Windows are grouped incorrectly using Chromium PWAs

### ISSUE THREAD

**Issue by joeldeteves** [BuddiesOfBudgie/budgie-desktop#201]
Moving this issue here as I accidentally created it under the old Solus repo:

## Description
When using a PWA (Progressive Web App) created in Chrome, if I attempt to minimize that instance of the PWA it also minimizes all other Chrome windows.

The workaround I have found is to turn off the Window Grouping feature in the Icon Task List applet, but this is not ideal since it goes back to the old "Windows-2000esque" behaviour of having a plethora of terminal windows splattered across taskbar.

Since PWAs are becoming more mainstream as an alternative for Linux support (for example many of us are forced to live in the Microsoft world for work-related reasons), it would make sense if PWAs are handled as "apps" rather than being treated as multiple instances of Chrome.

- Gnome 42 handles this the right way no matter which browser the PWA is created in
- Gnome Web (Epiphany) also handles this the right way when used *with* Budgie. So it seems to be some odd behaviour between Budgie and Chrome specifically

## Budgie Version
budgie-desktop 10.5.3

## Operating System
Ultramarine Linux 36 Flagship Edition (Fedora 36 base)
Kernel Version: 5.19.9-200.fc36.x86_64

## Steps to reproduce
1. Create a couple of different PWAs using Chrome / Chromium's "Create shortcut" feature, e.g. GitHub and Notion
2. Open multiple PWA instances
3. All PWAs are grouped under the icon of the first PWA that gets launched

## Expected behaviour
PWAs should be treated as individual Applications

## Potential solutions
It would be nice if Budgie had an option to exclude certain applications from Window Grouping - this would be the most flexible solution IMO, as then the Budgie team don't have to make exceptions for every possible app that can break using this behaviour (another badly-behaving app is Steam, which creates multiple Window instances and doesn't remove them from the Budgie taskbar when done).

**Comment by serebit** [comment]
Could you re-test under a newer Budgie version, ideally v10.6.4? We've made a lot of changes to the Icon Task List in the v10.6 series, including numerous grouping fixes.

**Comment by joeldeteves** [comment]
Looks like I grabbed the wrong version - I was using `neofetch` but it doesn't report the correctly installed version.

The version I'm currently on is `10.6.3-2.`

Will try `10.6.4` when it gets backported and report back.

**Comment by serebit** [comment]
There were no changes in v10.6.4 related to the Icon Task List, so v10.6.3 is good enough. I'll see if I can reproduce this later, though I'm going to need to figure out... how to create a Chrome PWA.

**Comment by serebit** [comment]
Well I'm definitely getting some odd behavior with Flatpak Ungoogled Chromium PWAs installed, but it's not identical to what you're reporting - opening a PWA completely desyncs the icon task list with regards to Chromium windows, and the Arch Chromium package does the same thing.

**Comment by tmknight** [comment]
Reviving this as "chrome" PWAs are not correctly handled by `Icon Task List` as of `10.8.2` via Ultramarine Flagship and Fedora Budgie.
Example using Ultramarine, Vivaldi and Microsoft Teams PWA - Teams is not displayed in any form or fashion in ITL (including right-click on Vivaldi icon):
![Snapshot_2023-12-03_10-17-14](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/548588/9a2a6cf9-09a8-4089-bed8-31074d06a5d0)

**Comment by tmknight** [comment]
Reviewing other issues, I wonder if this possibly is tied to #469

**Comment by JoshStrobl** [comment]
It isn't, that hasn't landed yet.
