### ISSUE TITLE
Large size JPEG background no longer renders, cannot open image file in Image Viewer

### ISSUE THREAD

**Issue by tomocafe** [BuddiesOfBudgie/budgie-desktop#202]
## Description

Sometime recently, the same desktop background I'd been using for several months stopped working. On Budgie startup, I would just get a solid black background, even though the Control Center _Background_ tab shows the image in the preview.

I thought maybe the file got corrupted, so I found it again and downloaded anew, but the same issue persisted despite other images working fine. I then tried to open the file in Image Viewer (EoG) and it also wouldn't render. But it did give me the helpful error: "Could not load image ... Error interpreting JPEG image file (Backing store not supported)".

This led me to an [issue](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/216) reported with gdk-pixbuf and EoG. It also seems to be affecting Budgie.

It seems it was introduced [here](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/commit/b659038e4296534c2e068de9bce8d9e17fbe58b4) as a security patch and affects large JPEG files.

## Budgie version

**10.6.4**

## Operating system

Solus 4.3 fortitude

## Steps to reproduce the issue

To reproduce, you can try downloading [this rather large image](https://unsplash.com/photos/uOi3lg8fGl4/download?ixid=MnwxMjA3fDB8MXxhbGx8NjR8fHx8fHwyfHwxNjY0Njg5NTM5&force=true) and try opening it in the Image Viewer app, or setting your background with it.

**Comment by serebit** [comment]
If this was an issue with gdk-pixbuf, then it needs to be fixed upstream—there's not really anything we can do about it here.

**Comment by tomocafe** [comment]
Got it, wasn’t sure if this needed any attention from the Budgie side. At least it’s here in case anyone else comes looking with the same issue.
