### ISSUE TITLE
Unable to right-click on the desktop

### ISSUE THREAD

**Issue by 0x199x** [BuddiesOfBudgie/budgie-desktop#204]
## Description
Possibly related to #176 

Menu does not appear when desktop is right-clicked.  Two systems are affected, both running EndeavourOS.  On both of these systems, I also have the issue described in #176 

## Budgie version
10.6.4

## Operating system
EndeavourOS

## Steps to reproduce the issue
Right-click desktop

## Actual result
Nothing happens

## Expected result
Menu appears

## Additional information
I assume these two issues are related in some way, but do not seem to be directly connected.  In BoB matrix chat about this issue a while ago, at least one other user was having trouble with only window titles, but not with desktop menu. So I am filing separate issue for this.

**Comment by serebit** [comment]
I'm on Endeavour and not seeing this, but this also isn't a new install, and (being a developer) I've mucked with Budgie a lot on this system. I'll see if I can reproduce this in an Endeavour VM.

**Comment by serebit** [comment]
Not seeing this in a brand-new Endeavour VM using the stock Budgie configuration, Is there any additional info you can give about your system and OS installation? Can you reproduce it on those systems in a newly spun up VM?

**Comment by 0x199x** [comment]
It is likely something that occurred as the result of a system update if it's not showing up on a fresh install.  On my main system, I've had Budgie installed as my primary desktop for probably 2-3 years.  

On my laptop, (EndeavourOS ARM), I've had Budgie installed for about 1 year (since 9/2021).  

Both systems are on 10.6.4.

I might have a unique opportunity to test this theory ... I have EOS w/ Budgie installed on a virtual machine that I haven't updated since 10.6.1. I was using it for applet dev a while back.  Currently, the right-click is **working** on that VM.  The possibility exists that if I update now, the right-click could quit working post-upgrade.  Before I run an upgrade, is there anything you'd like me to check beforehand?

**Comment by serebit** [comment]
Could you save a snapshot of the VM before you upgrade, and roll back afterwards?

**Comment by 0x199x** [comment]
I took a snapshot and updated. 

Unfortunately the desktop right-clicking still works.  I was sort of hoping that would break, to make this easier to figure out.   

Window title right clicking completely broke, as expected.

**Comment by serebit** [comment]
Could this be caused by another package on the system that interferes with Budgie? Can you run `yay -Q` on your affected systems and put the result in a gist so I can take a look at it?

**Comment by fossfreedom** [comment]
@serebit it could be exactly the same issue as #176  ... in the menus daemon the desktop menu is displayed using the same popup_at_pointer method used by the titlebar action menu right click ... so maybe the use of popup like I suggest in the #176 PR is worth trying ... at the very least to confirm if it is so similar.

**Comment by serebit** [comment]
@fossfreedom Maybe. I'll take a look at it.

**Comment by serebit** [comment]
I managed to get this to trigger, but only because the version of budgie-desktop-view on my system hadn't been rebuilt for the GNOME 43 stack upgrade. After installing budgie-desktop-view-git and relogging, the right-click behavior restored itself.

**Comment by JoshStrobl** [comment]
Let's try not to conflate the issues with the Budgie Desktop View internal right click with the wm's background or window title right clicks. The Budgie Desktop View right click menu is within the application itself, it's just that it is a DESKTOP-type application with no window decorations, skips taskbar, etc.

This issue is related to the right-click functionality in Budgie itself, e.g. right-clicking on window titlebars and the "background" when the desktop view is not used or on non-primary monitors.

**Comment by serebit** [comment]
Okay, so right click on desktop is broken *in budgie-desktop*, but works perfectly fine in budgie-desktop-view. That explains the inconsistency. I'll mark this as verified with that in mind. Seems to be the same root bug as #176.
