### ISSUE TITLE
Same icon used for all applications in the new menu

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#205]
## Description
![image](https://user-images.githubusercontent.com/996240/197505285-e2b50565-040b-45c1-bbd3-bd8320ade7ed.png)

In the menu - the same icon is used - I am using Papirus icons.

Is this intentional?

What is the actual icon name expected - because some icon themes like Moka currently need a tweak to display something

![image](https://user-images.githubusercontent.com/996240/197505579-5813ca80-42ca-446f-b730-3e1b38c81fde.png)

## Budgie version
git master - around end-august 2022

## Operating system
Debian 11 testing

## Steps to reproduce the issue
Choose either Moka-icons or Papirus icons

## Actual result
See Description

## Expected result

TBD

**Comment by serebit** [comment]
I have yet to see this, and I've been using the new menu for a while.
