### ISSUE TITLE
Minor Suggestion: Change the "Show Window Controls" icon on the task list to a more descriptive icon 

### ISSUE THREAD

**Issue by 0x199x** [BuddiesOfBudgie/budgie-desktop#213]
### Current Budgie version
10.6.4

### Use-cases
More useful visual cue for the user.

### Proposal
This is very, very minor, but this icon isn't terribly descriptive of its function.  In all the years I've used Budgie, I haven't bothered clicking it until just recently.  I figured the arrow meant "take me to this window" or something, and never had any reason to click on it.

![image](https://user-images.githubusercontent.com/89231731/200210921-f439b142-aea2-4938-87bf-2bfe17ee3496.png)

I propose changing the icon to the "three vertical dots" icon, unless someone knows of a more appropriate icon to use.  The three vertical dots icon typically represents a popup context menu, so it seems a good choice to me.  But I'm not sure if you'd want the icon to represent "a list of options" or something more specific to window controls.. so a different icon option might be more fitting.

Cheers

**Comment by JoshStrobl** [comment]
A vertical or horizontal ellipsis is, in my opinion, less obvious to most users than the arrow. I am quite surprised that it was not obvious, even with using "legacy" window menus (like File, Edit, etc...) the denoting of nested items is made evident with an arrow character, and in modern design it is very common for layers / nested menus (for example in drawers) to use the same arrow iconography to denote sub-menus (e.g [Ant Design](https://ant.design/components/menu/#components-menu-demo-vertical) and [Material Design](https://m3.material.io/components/menus/overview)).

If you have any other suggestions. they could be discussed, but I am not convinced that the current icon is problematic.

**Comment by serebit** [comment]
I'm actually in agreement with @0x199x here—I think a stubby arrow would better indicate the purpose of the button.

**Comment by 0x199x** [comment]
This is where I wasn't sure of the appropriate icon selection, it really just depends on if you want to relay _generic_ or _specific_ information to the user.  

►, or even three dots, would indicate _generic_ menu navigation like "expand", "more options", or "a nested sub-menu"

Or, if you wanted to indicate more _specific_ functionality to the user, something like the [tune icon](https://materialdesignicons.com/icon/tune-variant) could be used to indicate "settings related to the adjacent UI element" (in this case, the window)

Either a generic or specific visual cue could work just fine I think
