### ISSUE TITLE
Window animation is positioned wrong and sliding down

### ISSUE THREAD

**Issue by handyrka** [BuddiesOfBudgie/budgie-desktop#216]
## Description

Sometimes it just happens randomly, but it also happens everytime i click multiple times on an icon in the panel.
Basically with each new click window in animation kinda slides down more and more (?)

## Budgie version

budgie-desktop 10.6.4

## Operating system

Arch Linux 6.0.8-arch1-1

## Steps to reproduce the issue

1. `pacman -Syu`
2. `pacman -S budgie-desktop`
3. Start budgie 
4. Try to click multiple times on an icon in the bottom panel 

## Actual result

Weird animation with window sliding more and more down
Video of what is happening: https://youtu.be/IKhHvGz1wqo

## Expected result
Actually working animation

## Additional information
Just in case, my specs:
* ryzen 5500
* gtx 1050ti (nvidia driver 520.56.06)

**Comment by serebit** [comment]
So I've experimented with this for a couple hours, and I'm not sure if there's a way for us to fix this within the confines of Mutter. I did manage to fix the sliding down, but the way I did it only made the rapid minimize/unminimize worse (to the extent that I'd be concerned about photosensitive epilepsy).

**Comment by handyrka** [comment]
> So I've experimented with this for a couple hours, and I'm not sure if there's a way for us to fix this within the confines of Mutter. I did manage to fix the sliding down, but the way I did it only made the rapid minimize/unminimize worse (to the extent that I'd be concerned about photosensitive epilepsy).

Can you please expain why this bug happens? (Like is it Mutter issue or something else)

**Comment by serebit** [comment]
I'm not sure why it just happens randomly to you, but the reason it happens when you spam click on the icon in the task list is because the window is performing an animation and the spam-clicking repeatedly interrupts that animation and restarts it from the point where the window *currently is*, rather than its original position. That's my understanding, anyway. Because of this, there isn't really a good way to fix it as far as I can tell.

**Comment by handyrka** [comment]
@serebit, Any progress on this issue?

**Comment by serebit** [comment]
I'm going to call this wontfix. It's not significant enough to call an actual problem, and we're replacing our window management code anyway with the move to Wayland. If you have any other issues, feel free to report them.
