### ISSUE TITLE
Glitches when mazimizing application windows on Mutter 43.1

### ISSUE THREAD

**Issue by stabilergriller** [BuddiesOfBudgie/budgie-desktop#217]
## Description

Hello, 

since a week or so, I've been experiencing issues when maximizing application windows. The windows appear "out of bounds" with not visible GUI elements and there is a lot of glitching around.

I have beforehand [asked on the Arch BBS Forums for help](https://bbs.archlinux.org/viewtopic.php?id=281260). This is the [response](https://bbs.archlinux.org/viewtopic.php?pid=2067822#p2067822) I got:

_"The root window isn't bigger than the monitor, this smells like a bug in budgies WM/compositor.
Consult your pacman log to see whether there was a budgie related update around the time this started."_

But I don't think there had been any Budgie updates recently?

Here's a screenshot:

![Workspace 1_001](https://user-images.githubusercontent.com/115423284/201538295-354f197c-936c-4f5d-a676-67d4ba0c7cc1.png)

The maximize-button is at the very edge of the right screen. Notice how the close button is missing. It seems to lie "outside" of the monitor.

Also almost every time I get glitches like these:

![Selection_001](https://user-images.githubusercontent.com/115423284/201538425-e6314a27-3498-4f27-8e34-d28537f225c0.png)

Here is a full video of me trying to maximize Budgie Control Center: https://postimg.cc/py4tv0L4

This happens both on the Longterm and Stable Kernels. I did a fresh installation of Arch just to be sure and the issue still persists. I also installed the latest version of GNOME 43 and tested it thoroughly - no glitches. Everything maximizes as expected.

## Budgie version

10.6.4

## Operating system

Arch Linux x86_64

## Steps to reproduce the issue

Clean install Arch, budgie-desktop and lightdm
Maximize some applications like gedit, Budgie Control Center or Budgie Desktop Settings

## Additional information

CPU: Intel Pentium G4560 (4) @ 3.500GH
GPU: Intel HD Graphics 610 (KBL GT1)
Resolution: 1920x1080

**Comment by fossfreedom** [comment]
You mentioned this started in the last week or so. What packages were
updated around the date the issue was first noticed?

**Comment by stabilergriller** [comment]
> You mentioned this started in the last week or so. What packages were updated around the date the issue was first noticed?

I'm sorry, I can't answer that, because I formatted my drive and did a fresh installation of Arch since then. When this issue first occurred, I figured it was my fault and I messed something up.

**Comment by fossfreedom** [comment]
In arch can you tell when the libmutter-11 package was last updated?

**Comment by stabilergriller** [comment]
On the 4th of November, I think

https://archlinux.org/packages/extra/x86_64/mutter/
https://github.com/archlinux/svntogit-packages/commits/packages/mutter/trunk

**Comment by fossfreedom** [comment]
Do you have the ability to rollback to the previous 43.0 version? This will allow us to confirm if this is a mutter issue that has just been introduced.

**Comment by serebit** [comment]
I've been seeing this too on Arch + AMD with Firefox, so I'll mark it as verified.

**Comment by serebit** [comment]
@fossfreedom Rolled back to mutter 43.0, and the issue stopped happening. Seems to be a problem introduced with mutter 43.1.

**Comment by fossfreedom** [comment]
Hmm.  As another data point - is this specifically with client-side decorated apps like budgie-control-center or does it also occur with non CSD apps  like budgie-control-center.

Does turning off animation help budgie-desktop-settings - style - animations ?

**Comment by stabilergriller** [comment]
Budgie Control Center and Budgie Desktop Settings are both affected.
Not every app has this problem. I maximized [Wezterm](https://wezfurlong.org/wezterm/) for a long time. Never had a single glitch in this specific case.

Still got the glitch with animations off. I would say it's even worse. Before that, minimizing + opening the app again redraws the window correctly. Now, not even that works anymore and I'm stuck with an unusable Control Center.

![image](https://user-images.githubusercontent.com/115423284/201647425-1661212a-10d1-4512-a3d4-73513f67eb20.png)

![image](https://user-images.githubusercontent.com/115423284/201647957-6d8b882d-ad55-4abc-b86c-a09130268a0b.png)

**Comment by JoshStrobl** [comment]
This appears to be an upstream bug with Mutter. If you take a look at [this issue filed in GNOME Shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6054), you can see that it is exhibiting the same problems. There was some bisecting that happened and it looks like an MR landed, but it is unclear what the state of that is.

I would recommend filing an issue with the Mutter team.

**Comment by fossfreedom** [comment]
I've compiled mutter without that commit - seems to make things work again.

Lets see where that issue goes.  I'll keep an eye on Ubuntu kinetic since it hasn't received 43-1 - Debian unstable has has the same maximise/unmaximise broken behaviour.

**Comment by serebit** [comment]
Mutter 43.2 has been released, which includes a commit that fixes this issue.
