### ISSUE TITLE
Add step to disable GDM service on Fedora wiki page

### ISSUE THREAD

**Issue by jaypatelani** [BuddiesOfBudgie/budgie-desktop#219]
Addition of "sudo systemctl disable gdm" before "sudo systemctl enable lightdm"

**Comment by serebit** [comment]
This isn't necessary. Enabling lightdm doesn't automatically start it, and uninstalling gdm immediately after automatically disables the service.

**Comment by JoshStrobl** [comment]
Yea, the target will automatically be updated. You should not be disabling gdm before enabling lightdm or you will get kicked of our session and will not be able to get into a login manager without firing up a TTY, enabling lightdm, and then restarting or trying to switch to a new functional TTY.

So the instructions I wrote for this are very much intentionally designed to avoid that by keeping the existing target service running and swap it out dynamically.

**Comment by jaypatelani** [comment]
For me when i tried to enable lightdm as per wiki it showed error that other service was already enabled so I had to disable gdm first to make lightdm enable.

**Comment by JoshStrobl** [comment]
@jaypatelani Mind checking if adding `-f` sorts it for you?

**Comment by JoshStrobl** [comment]
Nah, will wait until someone else pokes on this issue :D

**Comment by jaypatelani** [comment]
Okay :)

**Comment by jaypatelani** [comment]
Installing Budgie + lightdm:

![Screenshot from 2022-11-17 17-44-20](https://user-images.githubusercontent.com/17174485/202452909-d7a185d0-0180-4ebb-bcd3-4620a5c04df4.png)

systemctl with "-f" option did setup lightdm
![Screenshot from 2022-11-17 17-51-07](https://user-images.githubusercontent.com/17174485/202452941-573d51f2-13d5-48a4-89d1-747c1c13ec62.png)

**Comment by JoshStrobl** [comment]
Thanks! Will add the `-f` to the doc.
