### ISSUE TITLE
Budgie Desktop Settings forces HighContrast for Widgets when Icons is hiColor and breaks the default dark theme.

### ISSUE THREAD

**Issue by Hi-Phile** [BuddiesOfBudgie/budgie-desktop#220]
## Description
Default installation using current ISO on Arch Linux (RebornOS) with Budgie DE 10.6.4 and when opening the Budgie Desktop Settings under 'Style' there's only the default Cursors 'Adwaita', and if you select the pull-down from Widgets, HighContrast appears but doesn't stick.  But, if you do the pull-down for 'Icons', then hicolor appears and then forces HighContrast to appear as well.  Then the menu and task bar changes, and no longer has the Dark theme as selected in the 'Dark theme' slider from the Style menu.  You cannot 'undo' these changes.

Secondarily, I'd assume that Budgie Desktop Settings should be able to change the Budgie Control Center at least for the Dark theme setting, but that's not the case.  I do understand the Gnome-Control-Center does allow the dark theme to work with the Gnome apps.  So, is this also a bug because neither BDS nor GCC doesn't seem to change BCC to the Dark theme?

## Budgie version
`$  sudo pacman -Q budgie-desktop budgie-screensaver budgie-control-center budgie-desktop-view network-manager-applet budgie-extras'
budgie-desktop 10.6.4-4
budgie-screensaver 5.1.0-1
budgie-control-center 1.1.1-3
budgie-desktop-view 1.2-2
network-manager-applet 1.30.0-1
budgie-extras 1.4.0-2

## Operating system
`$ cat /etc/lsb-release `
DISTRIB_ID="RebornOS"
DISTRIB_RELEASE="rolling"
`$ uname -s -r -v -o`
Linux 6.0.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:24 +0000 GNU/Linux

## Steps to reproduce the issue
Default 'Online installation' with Budgie Desktop Environment from rebornos_xfce_minimal-2022.11.13-x86_64.iso
Login onto the Budgie DE and open the Budgie Desktop Settings and under the Style settings:
Widgets pull-down and HighContrast appears but doesn't stick.
Icons pull-down and hicolor appears and sticks then forces the HighContrast setting under Widgets.
Cursors  pull-down only available is Adwaita.

Unable to blank it out or modify Widgets or Icons once it is set.

## Actual result

![image](https://user-images.githubusercontent.com/35350630/202589440-5edb0372-92b3-47a1-bce2-4d4db3d03934.png)

![screenshot-desktop-after-style-icon-hicolor-image](https://user-images.githubusercontent.com/35350630/202589939-f1388df1-dc5c-4d6e-b70b-5fd316fa535a.png)
![image](https://user-images.githubusercontent.com/35350630/202590355-991dc341-a0b6-43f7-801a-4ad676943945.png)

## Expected result
Be able to blank out the Icons or Widgets (select nothing) as it was before the pull-down menu access.

## Additional information
$ ps -ef | grep budgie
finnsst+     648     610  0 14:49 ?        00:00:00 /usr/lib/gnome-session-binary --builtin --session=budgie-desktop
finnsst+     809     648  0 14:49 ?        00:00:26 budgie-wm
finnsst+     844     648  0 14:49 ?        00:00:13 budgie-panel
finnsst+     887     648  0 14:49 ?        00:00:00 budgie-daemon
finnsst+     888     648  0 14:49 ?        00:00:00 budgie-polkit-dialog
finnsst+     911     648  0 14:49 ?        00:00:00 budgie-extras-daemon
finnsst+     921     648  0 14:49 ?        00:00:00 /usr/lib/budgie-previews/previews_daemon
finnsst+     923     648  0 14:49 ?        00:00:00 budgie-screensaver
finnsst+     924     648  0 14:49 ?        00:00:00 org.buddiesofbudgie.budgie-desktop-view
finnsst+     925     648  0 14:49 ?        00:00:00 /usr/lib/budgie-window-shuffler/windowshufflerdaemon
finnsst+     926     648  0 14:49 ?        00:00:20 /usr/lib/budgie-previews/previews_creator
finnsst+    1348       1  0 14:50 ?        00:00:09 budgie-control-center
finnsst+    5836    1411  0 16:18 pts/0    00:00:00 grep budgie
$ ps -ef |grep gnome
finnsst+     643     634  0 14:49 ?        00:00:00 /usr/bin/gnome-keyring-daemon --foreground --components=pkcs11,secrets --control-directory=/run/user/1000/keyring
finnsst+     648     610  0 14:49 ?        00:00:00 /usr/lib/gnome-session-binary --builtin --session=budgie-desktop
finnsst+     784     634  0 14:49 ?        00:00:00 /usr/lib/at-spi2-registryd --use-gnome-session
finnsst+    1180     634  0 14:49 ?        00:00:00 /usr/lib/xdg-desktop-portal-gnome

Installation log (/var/log/install.log) available to view here:  https://termbin.com/3nsd

**Comment by JoshStrobl** [comment]
> Secondarily, I'd assume that Budgie Desktop Settings should be able to change the Budgie Control Center at least for the Dark theme setting, but that's not the case. I do understand the Gnome-Control-Center does allow the dark theme to work with the Gnome apps. So, is this also a bug because neither BDS nor GCC doesn't seem to change BCC to the Dark theme?

No, see #27. The dark theme you see in GNOME Control Center only applies a dark theme preference on Adwaita apps and changes the theme to Adwaita, which does not support Budgie Desktop. Hicolor is also primarily focused of GNOME Shell with various elements supporting GTK applications (which impacts Budgie but does not imply support).

It is recommended you install Materia GTK Theme and Papirus on top of budgie-desktop.

Going to close this in favor of #27, which has an OKR around widget and icon theme selection improvements.
