### ISSUE TITLE
Grayish text with Materia

### ISSUE THREAD

**Issue by glow12121** [BuddiesOfBudgie/budgie-desktop#221]
## Description
Hi,

My understanding is that Materia is the recommended theme for Budgie currently, but as I switch to Materia-compact, the bottom panel elements with text are grayish. You can see below how the keyboard indicator's color differs from Dropbox icon. How could this be fixed?

![image](https://user-images.githubusercontent.com/29035180/202727018-80005116-461b-482e-8902-1e531a11ae7f.png)

I also noticed the colors don't work in some programs. For example, Gnome Emails (Evolution) has important icons in its title bar but, with Materia, they aren't visible:

![image](https://user-images.githubusercontent.com/29035180/202726839-322c71a2-64ea-423f-8ae6-fb5b5d0d4f73.png)

## Budgie version
10.6.4

## Operating system
Solus 4.3

**Comment by serebit** [comment]
These are issues that should be filed against Materia. There's not really anything we can do to fix theming issues in a third-party GTK theme. Additionally, if you're not a fan of how Materia themes components, there are other GTK themes that work pretty well with Budgie, like Arc and Matcha.

If you like Materia and just want to resolve the greyed out text thing, I'd suggest enabling the Budgie built-in theme. That keeps the GTK widget theme for all applications except Budgie itself.

**Comment by glow12121** [comment]
@serebit the problem is - with all themes I've tested, Arc and Matcha included, those title bar elements are not displayed properly. I am speaking about the theme modalities with contrasting title bar, those are usually called "darker". Turning on the "built-in theme" does not fix the problem.

I personally still stick to the once default Plata-compact because other similar themes have even more issues with the elements I mentioned. Unfortunately, Plata is no longer developed.

**Comment by glow12121** [comment]
@serebit many thanks, I switched to Papirus *Dark* and now, with Plata-compact, everything looks okay.
