### ISSUE TITLE
Workspace Switcher: In some file managers the icon doesn't match the current directory

### ISSUE THREAD

**Issue by stabilergriller** [BuddiesOfBudgie/budgie-desktop#224]
## Description

Hello,
When using file managers like [Nemo](https://github.com/linuxmint/nemo) and [Thunar](https://docs.xfce.org/xfce/thunar/start), the icon in the workspace switcher applet shows a representation of the current directory the user is in, instead of the generic application icon:
![Selection_003](https://user-images.githubusercontent.com/115423284/204589880-b1ba3174-576e-4cd4-a224-d71842fb9e3d.png)

(Here with the Papirus Dark Icon Theme)

But this icon does not change on the fly when switching folders, so it's possible to have cases like these, where you get conflicting information:

![Untitled4](https://user-images.githubusercontent.com/115423284/204617316-4f4f6988-50ad-444b-bd76-dc1bac770077.png)

The Video-Icon is somehow not updated to the Templates icon, although I changed locations. This icon seems to be only redrawn, if you minimize the application, or switch applications. 

Is it possible to update the workspace switcher icon always to the current folder directory? If it's not technically feasible, it might be preferable to always force the generic application icon on Nemo / Thunar, instead of the symbolic icon.

## Budgie version

10.6.4

## Operating system

Arch Linux x86_64

## Steps to reproduce the issue

Install Nemo / Thunar, activate the Workspace Switcher applet and change folders in the users home directory

## Actual result

Workspace Switcher shows mismatching symbolic icons instead correct ones / the generic application icon

## Expected result

Icons in the Workspace Switcher should always match current directory, or just show the generic Application Icon

## Additional information

Not every file manager has this problem, Nautilus works just fine.
There may be more file managers with this problem.

**Comment by serebit** [comment]
Reproduced with Nemo on EndeavourOS. Marking as verified.

**Comment by serebit** [comment]
Fortunately, this was an incredibly easy fix. I'll open a PR now.
