### ISSUE TITLE
Repeated terminal messages about non-existent desktop-directories folder

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#232]
## Description
Built git master with the new menu applet.

** (budgie-panel:7117): WARNING **: 21:07:01.264: AppIndex.vala:289: Error enumerating files in desktop-directories: Error opening directory '/home/dad/.local/share/desktop-directories': No such file or directory

This message is repeatedly seen in the terminal after running `budgie-panel --replace `

## Budgie version
10.6.4 - git master https://github.com/BuddiesOfBudgie/budgie-desktop/commit/41a6187daf3cf48815163f3abc14071199d32aa7

## Operating system
Ubuntu Budgie 22.10

## Steps to reproduce the issue
Replace the panel and observe the messages in the terminal

## Actual result
See the description

## Expected result
No warnings.

Note - in Debian/Ubuntu ~/.local/share/desktop-directories is not a folder that is created out of the box

**Comment by serebit** [comment]
Reproduced on EndeavourOS.
