### ISSUE TITLE
Let Budgie search for plugins on  /usr/local

### ISSUE THREAD

**Issue by jasaldivara** [BuddiesOfBudgie/budgie-desktop#237]
### Current Budgie version:

budgie-desktop 10.6.4

### Use-cases

I recently installed Budgie on my Fedora 37 system, from the fedora Repos.

I wanted to have a system monitor integrated on my desktop, so I found [Budgie System Monitor Applet](https://github.com/prateekmedia/budgie-systemmonitor-applet), which I built without any issues, but I set the installation prefix to `/usr/local`, so it won't interfere with software installed via the package manager:

```
$ meson build --prefix=/usr/local --buildtype=plain

$ sudo ninja -C build install
```

The problem is that Budgie wont find the plugin installed to `/usr/local` when I want to add the applet to a panel. I had to uninstall, and install it to `/usr`, and then it worked on Budgie without problem.

### Proposal

I think Budgie should search for plugins on `/usr/local` so more advanced users and developers can build and install their plugins easily without having conflicts with the package manager.

**Comment by serebit** [comment]
I think this is perfectly reasonable. The current version of Budgie searches in the prefix it was installed to - if the prefix is /usr/local, it searches in /usr/local, and the same for /usr. It should probably just search both by default.

**Comment by serebit** [comment]
For the record, Budgie does have an additional search path for plugins that you can use in the current version - `~/.local/share/budgie-desktop/plugins`.
