### ISSUE TITLE
Problems with Fullscreen Windows on NVIDIA

### ISSUE THREAD

**Issue by BlindRepublic** [BuddiesOfBudgie/budgie-desktop#247]
## Description

There seems to be a focusing issue with the volume change display when using direct fullscreen windows. This does not occur with Firefox and hitting F11 to put the window into fullscreen mode, but rather games specifically.

## Budgie version

`budgie-desktop 10.6.4`

## Operating system

Endeavouros

## Steps to reproduce the issue

1. Launch fullscreen game (not using a borderless window)
2. Use the keyboard to increase the volume

## Actual result

The OSD showing the volume appears, but the content of the current focused fullscreen window disappears and shows the desktop background instead

## Expected result
The OSD appears on top of the game content, but the content stays in the background

**Comment by serebit** [comment]
What games have you been able to reproduce this with?

**Comment by TrueTechie** [comment]
Originally I was having the issue with Hollow Knight, but after updating Steam to the Beta for unrelated reasons I cannot seem to reproduce it...

I'll reopen this if it happens again. Apologies

**Comment by serebit** [comment]
No worries.

**Comment by serebit** [comment]
Comment here if you (or anyone else) manage to reproduce it again, and I'll reopen.

**Comment by BlindRepublic** [comment]
So immediately after claiming the issue to be "fixed," it came back. I noticed that something similar to this has been reported as fixed with https://github.com/BuddiesOfBudgie/budgie-desktop/pull/267, but I still experience it. 

Could it possibly be an Nvidia issue? That's the only thing i can think of at this point

**Comment by EbonJaeger** [comment]
I wonder if the fullscreen state of the application is getting lost somewhere in the pipeline (possibly in Mutter) sometimes. With MechWarrior Online, it's also hit or miss on if the system thinks it's fullscreen or not. MWO is also a Windows game played on Linux through Proton, and it has other issues, so it's hard for me to say anything with much certainty.

**Comment by BlindRepublic** [comment]
@serebit 

> Comment here if you (or anyone else) manage to reproduce it again, and I'll reopen.

Hi, I finally figured out the issue!

I have two monitors with different refresh rates. If one window is on my secondary monitor and I have a fullscreen one on my main screen, I can replicate this 100% of the time.

**Comment by serebit** [comment]
What GPU is being used on the system?

**Comment by BlindRepublic** [comment]
The GPU is an Nvidia RTX 2070... Confirming on another machine with an Nvidia RTX 3050 refresh rate is not relevant.

**Comment by BlindRepublic** [comment]
> What GPU is being used on the system?

@serebit 

Hi, sorry to bother you but can this issue at least be re-opened?

**Comment by BlindRepublic** [comment]
Doing even more testing, this might be related to another issue with multi-monitor I've noticed with Steam Big Picture mode. 

When closing a game with the Big Picture overlay, the window loops through the closing animation. It doesn't stop unless I disconnect the external display.

I don't have much experience in graphics, but perhaps NVIDIA implements multimonitor in a different manner than the open source drivers?

**Comment by serebit** [comment]
Still happening, I assume?

**Comment by BlindRepublic** [comment]
> Still happening, I assume?

Disabling redirection actually fixes it.  I don't experience any issues whether or not redirection is enabled in other desktop environments, so it might still be a Budgie thing.

**Comment by JoshStrobl** [comment]
By `Disabling redirection` do you mean turning off (disabling) **un**redirection? Redirection issue can happen in any Mutter X11 based window manager (which includes Budgie), our logic effectively just toggles its behavior.

But yea, the toggle is basically there because of NVIDIA so working as intended then :)
