### ISSUE TITLE
Panel expands when text inside Task List overflows it

### ISSUE THREAD

**Issue by Solarunit** [BuddiesOfBudgie/budgie-desktop#249]
## Description

When running `./VentoyGUI.x86_64` from the terminal Authenticate dialog would appear and the panel would expand to 1/3 of the screen. I think that's bcs I am using Task List and text inside it "overflows" it

## Budgie version

budgie-desktop 10.6.4

## Operating system

Solus

## Steps to reproduce the issue

0. Enable Task List applet
1. Download and unpack ventoy-1.0.87-linux.tar.gz https://github.com/ventoy/Ventoy/releases/tag/v1.0.87
2. Run `./VentoyGUI.x86_64` from the terminal. Authenticate dialog would appear
3. Witness this:

![](https://i.imgur.com/xt69PHa.png)

**Comment by serebit** [comment]
I attempted to reproduce this a couple weeks ago using the steps outlined here, but failed to do so.

**Comment by Solarunit** [comment]
I will try reproduce again on 10.7.x when available and report back!

**Comment by serebit** [comment]
Have you managed to reproduce this?

**Comment by Solarunit** [comment]
@serebit can't reproduce it now. budgie-desktop 10.7.2

Gonna close it.
