### ISSUE TITLE
Duplicate volume controls in Raven for Firefox

### ISSUE THREAD

**Issue by 0x199x** [BuddiesOfBudgie/budgie-desktop#250]
## Description
Firefox often generates many duplicate volume control sliders in Raven

## Budgie version
10.6.4

## Operating system
EndeavourOS

## Steps to reproduce the issue
Unsure; see Additional Information

## Actual result
![image](https://user-images.githubusercontent.com/89231731/211650183-fc6366ff-ba1e-40e6-a979-1e67f1b115d5.png)

## Additional information
I suspect that this could _possibly_ be related to private browsing windows.  I have a weird habit of using a needlessly excessive number of private windows to manage cookies. For instance, I might open a Yahoo News link or something, and I don't want it saving cookies, so I open it in a private window and watch a video, a new volume slider appears in Raven, and doesn't get cleared out properly when I close the window.  I do this almost obsessively during my daily browsing and sometimes have 4-5 Firefox windows open at a time.  The screenshot above is after about 2 weeks of not rebooting or logging out of Budgie and letting the volume sliders pile up.

**Comment by JoshStrobl** [comment]
They are not duplicate so much as they are dedicated to different Gvc MixerStreams, which are created by libgnome-volume-control on a per-application basis whenever they play audio. I'll have to check where the issue lies (whether it's in Firefox or libgvc, in which case not much we can do about it or in Budgie, which we can).

Have you checked if this is a problem in other browsers? For example if you were to use private windows in Chrome or Vivaldi? Are these showing up in Budgie Control Center's Sound section at all?

**Comment by 0x199x** [comment]
I use also Pale Moon (based on FF) and haven't noticed the issue happening with that browser.   

I've had a similar issue in the recent past with a media player.. although I can't remember for sure if it was VLC or Sayonara Player causing it.  I was getting both duplicates and NULL entries.  Screenshot below.  I haven't been listening to much much lately so haven't had a chance to see that issue surface again.  

I cannot be certain that these two issues are related, but figured it would be worth mentioning.

![image](https://user-images.githubusercontent.com/89231731/211847256-45a237f4-ddac-4aef-9392-2d151beb0236.png)

**Comment by serebit** [comment]
This is almost certainly [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1602345), which is a known issue with Firefox's pulseaudio implementation. Essentially, it doesn't clean up the sinks that it creates, leading to duplicated outputs in Raven. For this reason, I'll be closing this as wontfix—@0x199x, I believe what you've posted is a different problem, and merits a different issue for discussion.
