### ISSUE TITLE
budgie-power-dialog installed in the wrong location?

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#259]
## Description
budgie-power-dialog is installed in /usr/bin.

Running this on a command line doesnt do anything
budgie-power-dialog --help doesnt reveal any help.  Debian recommends via a lintian warning that all /usr/bin executables should have an associated help manual.

Question - is /usr/bin a valid location since it doesn't appear to be user executed?  Perhaps /usr/lib.../budgie-desktop is a more valid location for a budgie-specific autostart exe? 
Or should some sort of help be displayed even if it says 'no help available...' ? 

## Budgie version
Git Master

## Operating system
ubuntu 23.04

## Steps to reproduce the issue
budgie-power-dialog --help

## Actual result
no help displayed

## Expected result
Basic help for a /usr/bin based executable

## Additional information
I tried to use help2man to generate basic help

**Comment by serebit** [comment]
Running it on the command line starts the dialog's background process. Regardless, it may be better for it to be installed to the libexec dir, rather than /usr/bin.
