### ISSUE TITLE
On Budgie, Chrome has a gap that I can see through between the toolbar and the webpage

### ISSUE THREAD

**Issue by jdrp2311** [BuddiesOfBudgie/budgie-desktop#261]
### Description

Whether using the GTK or the classic theme, Chrome displays a gap that I can see through between the toolbar and the webpage. That means I can always see a tiny portion of my wallpaper or app that is open behind Chrome. Only happens on Budgie desktop.

### Budgie version

10.6.4

### Operating System

Ubuntu Budgie 22.10

### Steps to reproduce the issue

Just open Google Chrome.

### Actual result

Gap exists.

### Expected result

Gap does not exist.

### Additional information

Happens both on Ubuntu Budgie and on Solus Budgie.
While lunching Chrome from the terminal, it spams the following message:

ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: Arquivo ou diretório inexistente (2)

However, after it has launched, it stops spamming that, so I guess it is unrelated.
I am not sure whether this is a Chromium or a Budgie bug, but since it has only happened on Budgie, I figured to post here first.

**Comment by fossfreedom** [comment]
Its a GTK Theme issue - I've fixed that on Ubuntu Budgie for the Pocillo theme which will be in 23.04.  Can be backported if need be to 22.04/22.10 https://discourse.ubuntubudgie.org/t/how-do-i-get-a-bug-related-to-budgie-fixed-in-a-stable-release/6436/2

For other themes you will need to ask the theme author (look through the open/closed issues first).
