### ISSUE TITLE
[Bug]: Icon Tasklist does not show Private Internet Access

### ISSUE THREAD

**Issue by ilvipero** [BuddiesOfBudgie/budgie-desktop#266]
### Description

On a fresh install of Ubuntu Budgie 23.04, with latest version of budgie and applets, I noticed that Icon Task List applet does not show all applications. I noticed this with Private Internet Access, I am not sure if other applications behave the same.

Removing the icon task list from the panel, and replacing it with task list, I can see all the apps, including Private Internet Access. However this applet displays text and is less useful for a dock-style panel.

Further tests, Private Internet Access is displayed correctly on Plank dock, and also on Ubuntu (GNOME) default dock.

Note. Private Internet Access is a .run script downloaded directly from their website. 

### Budgie version

10.6.4

### Operating System

Ubuntu Budgie 23.04

### Steps to reproduce the issue

1. Open "Budgie Desktop Settings" and create new panel
2. Select panel's settings:  
  - Position: Bottom
  - Dock Mode: On
3. Select panel's applets :
  - Add applet
  - Icon Task List
 

### Actual result

![icon-tasklist-01](https://user-images.githubusercontent.com/6520987/214068972-c665fd0c-8640-47f9-9624-062a5b4a51aa.png)

### Expected result

Expected result would be to see all applications on the "Icon Tasklist" applet.

### Additional information

Adding a screenshot of tasklist added to the bottom panel as dock.
![icon-tasklist-02](https://user-images.githubusercontent.com/6520987/214069265-acb7f843-f572-4509-b972-e30e55d549f6.png)

**Comment by serebit** [comment]
Gave this a look - this is a tricky one, because the window registers itself as a dialog (which we avoid showing in the Icon Task List) when it should be registering as a regular window. I'd recommend reporting this on the PIA side.
