### ISSUE TITLE
[Bug]: Night Light turned off by itself 1/2 seconds after relogin.

### ISSUE THREAD

**Issue by elliottophellia** [BuddiesOfBudgie/budgie-desktop#269]
### Description

Relogin to budgie after logout/reboot cause night light turned out by itself after 1/2 seconds, night light togle in icon panel is on but the night light is off, well you can turn it back on by double click the togle tho.

### Budgie version

10.6.4

### Operating System

Manjaro Linux x86_64

### Steps to reproduce the issue

1. Enable Night Light With Schedule Sunset to Sunrise + Temperature 2700
2. Logout/Reboot
3. Login

### Actual result

# After 1/2 seconds after relogin
![one](https://i.ibb.co/nQ3NL76/IMG20230125020343.jpg)

### Expected result

Night Light automatically enable not disabled by itself after 1/2 seconds after relogin.

### Additional information

# Double Click the Night Light togle to enable it again
![two](https://i.ibb.co/PwsQ6cg/IMG20230125020351.jpg)

**Comment by serebit** [comment]
Couldn't reproduce this on EndeavourOS, with both main and v10.6.4. It might be specific to Manjaro - I'll have to try a Manjaro VM to make sure.

**Comment by elliottophellia** [comment]
If that the case then I need to mention that I'm using minimal iso version of Manjaro budgie.

**Comment by samlane-ma** [comment]
It looks like you have the Brightness Controller applet installed. Does this issue still occur if you remove from the panel?

If so, it is probably a conflict similar to the issue raised here:
https://github.com/UbuntuBudgie/budgie-extras/issues/441

**Comment by elliottophellia** [comment]
> It looks like you have the Brightness Controller applet installed. Does this issue still occur if you remove from the panel?
> 
> If so, it is probably a conflict similar to the issue raised here: [UbuntuBudgie/budgie-extras#441](https://github.com/UbuntuBudgie/budgie-extras/issues/441)

This solve the issue thanks
