### ISSUE TITLE
[Request]: Add power-profiles-daemon control

### ISSUE THREAD

**Issue by kostadinsh** [BuddiesOfBudgie/budgie-desktop#276]
### Budgie version

10.6.4

### Use-cases

Currently, there is no quick setting for power-profiles-daemon in either the panel or Raven, and users have to open the control center.

### Proposal

Add a setting which lets users change the power-profiles-daemon profile quickly without having to open the control center. I think a good place for the control to appear would be upon clicking the battery icon in the panel.

**Comment by serebit** [comment]
I'm in favor of this, but what about systems without a battery where the panel icon doesn't show up?
