### ISSUE TITLE
[Request, documentation] Could the main README either contain instructions how to compile and then run it; or, if this takes too long on the main README, add a link to the wiki about this?

### ISSUE THREAD

**Issue by rubyFeedback** [BuddiesOfBudgie/budgie-desktop#280]
[Request, documentation] Could the main README either contain instructions how to compile and then run it; or, if this takes too long on the main README, add a link to the wiki about this?

Background rationale: I tend to compile from source, and I compiled fluxbox, all of KDE, lxqt, mate-desktop, xfce ... icewm.

These work somewhat (save for KDE in the last time, not sure why KDE5 is so much harder to get running compared to KDE3).

I'd like to try out budgie but I don't want to be tied to any particular distribution anymore. So, I would appreciate a better visibility of the installation instruction. As stated that can go into the wiki too. Or a separate document perhaps under doc/ or somewhere there.

Thanks for reading anyway.

**Comment by JoshStrobl** [comment]
The process is involved enough that it does not warrant being in the README. It is already on https://github.com/BuddiesOfBudgie/budgie-desktop/wiki/Building-Budgie-Desktop
