### ISSUE TITLE
[Request]: bring back window grouping option in icon task list app

### ISSUE THREAD

**Issue by mplx** [BuddiesOfBudgie/budgie-desktop#282]
### Budgie version

10.7

### Use-cases

Before 10.7 i had an option in `budgie settings` > `panel` > `icon task list`-app to disable window grouping, the option is gone now and window grouping is enabled by default

Budgie 10.7.
![Screenshot from 2023-01-30 13-57-35](https://user-images.githubusercontent.com/1986588/215484013-ffd64b4c-8185-4323-9cb8-8e2e672201f1.png)

Window grouping option in pre-10.7 (here: 10.6.4)
![Screenshot from 2023-01-30 13-58-25](https://user-images.githubusercontent.com/1986588/215484286-52d371bc-5454-4690-827e-fbb0fe3d95d5.png)

### Proposal

bring back code from pre 10.7

**Comment by JoshStrobl** [comment]
No. See #95

**Comment by mplx** [comment]
Thank you @JoshStrobl for your reply and the issue link. I was looking in the blog's release notes which does mentions changes to `Icon Task Lisk` but not this change.

It's sad to read users are forced to window grouping, and the `Task List`  applet is by far no replacement for the `Icon task list` - usually it's just a list of `...` seperated by small icons, and it does window grouping as well... :(

![image](https://user-images.githubusercontent.com/1986588/215743498-48dd6908-0ffe-43fa-91ea-1f1afd8aa594.png)

**Comment by serebit** [comment]
Task List is currently the best we have wrt a replacement for the Icon Task List's non-grouping functionality. We're intending for the *rewritten* Task List to better serve this use case - though unfortunately the developer who was working on the rewrite stopped using Linux, so it's been moved to the backlog. Rest assured that we do still intend on completing it, though.
