### ISSUE TITLE
[Bug]: "Budgie Menu" Applet: Search with parts of application name does not find application 

### ISSUE THREAD

**Issue by stabilergriller** [BuddiesOfBudgie/budgie-desktop#284]
### Description

Hello,

Something seems to have changed regarding the search provider between Budgie 10.6.4 and 10.7 using the budgie menu applet, and searching with parts of the application name. The search seems to be less useful than before, and in some cases requires the full application name to be remembered and typed in to get a result.

Example 1: 

Full application name that is searched for: "OpenJDK Java 11 Console"
entered search term: "JDK" or "jdk"

On Budgie 10.6.4: is found
![jdk_old](https://user-images.githubusercontent.com/115423284/215813588-6000253b-ff80-40f9-8ab9-8e9a797386f0.png)

But on Budgie 10.7: is not found

![jdk_new2](https://user-images.githubusercontent.com/115423284/215813617-f96f3c48-c002-4897-9127-94afa2ea9237.png)

Example 2:

Full application name that is searched for: "LibreOffice Writer"
entered search term: "Office" or "office"

On Budgie 10.6.4: is found

![office_old](https://user-images.githubusercontent.com/115423284/215815183-ca2ddab8-64be-4294-96e3-cc6bcb90ca52.png)

But on Budgie 10.7: is not found
![Office_new2](https://user-images.githubusercontent.com/115423284/215815217-9e29aa6d-cb2d-4d03-bae0-9dcd7876d314.png)

Note how WPS Office is not found anymore, either. I would expect that to be found too, when searching for Office software

Example 3:

Full application name that is searched for: "LibreWolf"
entered search term: "wolf" or "Wolf"

On Budgie 10.6.4: is found
![wolf_old](https://user-images.githubusercontent.com/115423284/215816469-46e53cf2-6fc4-453a-b581-07ccca994695.png)

But on Budgie 10.7: is not found
![wolf2](https://user-images.githubusercontent.com/115423284/215816440-375528f2-db87-46b7-bfb5-5d0729e35998.png)

In this case, a lot of not relevant search results seem to be returned, too. This is also true for Example 1.

This case is especially frustrating, since I'm used to typing "wolf" when searching for "LibreWolf", since any other open source application starts with the name "Libre", so will get results over results when searching for something that starts with "Libre"

Example 4:

Full application name that is searched for: "File Manager PCManFM"
entered search term: "manfm" or any variation

On Budgie 10.6.4: is found

![pcmanfm_old](https://user-images.githubusercontent.com/115423284/215818020-c9150cd1-b087-4a02-af1f-1204ddd25f5e.png)

But on Budgie 10.7: is not found
![pcmanfm_New2](https://user-images.githubusercontent.com/115423284/215819065-e9062bdb-fbc7-4b75-abc8-1d59ac4f2063.png)

### Budgie version

10.7

### Operating System

Arch

### Steps to reproduce the issue

Install the software listed above and compare search results between Budgie 10.6.4 and 10.7

Used packages names on Arch: community/pcmanfm, aur/librewolf-bin, extra/libreoffice-fresh, extra/jdk11-openjdk

### Actual result

Search for "jdk" does not return all applications with "jdk" in name such as "OpenJDK Java 11 Console"
Search for "wolf" does not find "LibreWolf"
Search for "Office" does not find "LibreOffice Writer"

### Expected result

Return to old search behaviour:

Search for "jdk" should return all applications with "jdk" in name such as "OpenJDK Java 11 Console"
Search for "wolf" should find "LibreWolf"
Search for "Office" should find "LibreOffice Writer"
...

**Comment by serebit** [comment]
Confirmed this on Arch Linux. You are correct that the search functionality has changed - we switched to using a fuzzy search algorithm to accommodate typos. Seems that this is a shortcoming with our current approach.
