### ISSUE TITLE
[Bug]: Navigating through Budgie-Menus using keyboard arrows not working on EndevourOS

### ISSUE THREAD

**Issue by Xmetalfanx** [BuddiesOfBudgie/budgie-desktop#290]
### Description

When trying to navigate the menus "envolking the menu" with either the super key or a left click with the mouse, navigation doesn't seem to work when using the arrow keys to browse the catagories OR the apps iside of each catagory 

### Budgie version

budgie-desktop 10.7

### Operating System

EndevourOS

### Steps to reproduce the issue

1. Either left click or use the Super key to "start" Budgie-Menu
2. Try to navigate using the arrow keys (any direction ... with or without a search for say an app... the issue happens either way) 

Before the last update, yesterday, the I am not sure what version the menu was on but it did not have those A) username at the bottom and B) icons on the bottom right ... but using the arrow keys to get around the menus had worked here before 

### Actual result

The Menu appears on the screen still but it acts like when a regular App is on the screen and loses focus for example

### Expected result

I expected whichever way i bring up the start menu, that I'd be able to use any arrow keys to move around the menu catagories and apps 

### Additional information

I did do another update before posting this (nothing budgie related was updated) just to double check if it was maybe a bug that had already been patched in a point release update or something like that.

I also have another Budgie install (Ubuntu Budgie) that without checking the version I am sure is not on 10.7 yet ... but even if so, I have NOT booted that system to check for the same issue

**Comment by EbonJaeger** [comment]
It looks like it *is* working the same as before, it just doesn't have a visual highlighting. Looks like this is a theme issue. What theme are you using?

**Comment by Xmetalfanx** [comment]
while i do admit i was changing themes to see what different ones looked like, I am on "Orchis" now
