### ISSUE TITLE
[Bug]: Plugins with "&" in their descrption fail to show the proper description

### ISSUE THREAD

**Issue by samlane-ma** [BuddiesOfBudgie/budgie-desktop#292]
### Description

When a plugin has an "&" in their "description=" line in the .plugin file, the description fails to properly show. (set_markup error).

(Markup.escape_text is not used on the description line)

### Budgie version

10.7

### Operating System

Ubuntu Budgie 22.10 / 23.04

### Steps to reproduce the issue

1. Open BDS
2. Add a plugin and select one that has an "&" in the description (for example the Budgie Extras Quick Notes applet has "Quick & Easy Notes"
3. Description for that applet does not properly load.

### Actual result

The description of the applet is not updated (it shows the prior selected applet description, in this case the Places applet )

![applet](https://user-images.githubusercontent.com/67085765/217001019-1c944c69-25f1-403b-b45f-78b2f36f7204.png)

### Expected result

Would expect the applet description to show "Quick & Easy Notes"

### Additional information

I noticed that several of the other lines use Markup.escape_text on the line from the plugin files. I assume it was just an oversight not to have it for the description line as well.

**Comment by serebit** [comment]
It was indeed an oversight. Thank you for the thorough investigation, I'll get this fixed for the next version.
