### ISSUE TITLE
[Bug]: Mouse pointer doesn't reappear when using trackpad after using touchscreen

### ISSUE THREAD

**Issue by chuckd853** [BuddiesOfBudgie/budgie-desktop#296]
### Description

**Surface Laptop 3 and Arch Linux/linux-surface**

After using touchscreen, the mouse pointer doesn't reappear when I go back to using the trackpad. 

The mouse operates as normal in that I can scroll, select text etc. I just don't have a pointer on the screen.

This has been happening for a 6 or more months.

To get the pointer back I open Tilix, press enter, then click the trackpad. 

### Budgie version

budgie-desktop 10.7

### Operating System

6.1.9-arch1-1-surface #1 x86_64 GNU/Linux

### Steps to reproduce the issue

1. Touch the screen.
2. Open xterm/Tilix
3. Press enter
4. Tap or hard click the trackpad

### Actual result

mouse pointer disappears when I touch the screen but doesn't show up when I go back to using the trackpad.

### Expected result

Mouse pointer reappears when I start using the trackpad.

**Comment by JoshStrobl** [comment]
This is an issue with Mutter, which Budgie leverages as part of its WM: https://gitlab.gnome.org/GNOME/mutter/-/issues/2376

**Comment by chuckd853** [comment]
Thanks for pointing that out Joshua. I'll close this issue and keep an eye
on Gnome/Mutter progression.

**Comment by RyuKurisu** [comment]
Uncertain if this bug should be opened again, considering it is an upstream bug in Mutter, but I wanted to report I'm also affected on Fedora 38 with Mutter 44.0

The mentioned bugs are marked closed, but the discussion continues on 2344.  I will also join that discussion after some more triaging 🤔
