### ISSUE TITLE
[Bug]: Budgie-Screenshot does not capture fullscreen games

### ISSUE THREAD

**Issue by Cherryda** [BuddiesOfBudgie/budgie-desktop#298]
### Description

When opening the screenshot utility and selecting the screen / window of a game, it will instead display an screenshot of the desktop's wallpaper. Happens on both native and Proton games. Some apps also have this problem but I couldn't reproduce that issue in all of them, and in some extreme cases my Budgie session would crash.

### Budgie version

budgie-desktop 10.7

### Operating System

Fedora 37

### Steps to reproduce the issue

1. Open Steam
2. Run a game through Proton's compatibility layer
3. Open Budgie-Screenshot
4.  Take a Window / Monitor screenshot

### Actual result

My desktop's wallpaper gets screenshotted.

### Expected result

An screenshot of the game.

**Comment by fossfreedom** [comment]
'fraid I don't play games nor have steam installed. The nearest equivalent I can think of is browser youtube fullscreen or fullscreen mp4 via parole

print screen and alt+print screen take screenshots just fine here.

**Comment by serebit** [comment]
I can reproduce this pretty easily with Deep Rock Galactic. *If the game is in focus,* it seems to capture the game about 20% of the time, and most of the time only captures the desktop. If the game *isn't* in focus, i.e. has a window above it or on another monitor that has focus, it captures the game just fine.

**Comment by fossfreedom** [comment]
Can confirm with supertuxkart - from an initial looksee it appears supertuxkart isnt drawing on the screen using mutter based stuff https://github.com/BuddiesOfBudgie/budgie-desktop/blob/cb54cba246bec4dadedbba3ed637c74031455b4d/src/wm/screenshot.vala#L228

**Comment by serebit** [comment]
That doesn't explain why captures work when the window isn't in focus, though.

**Comment by fossfreedom** [comment]
possibly - there is in BDS the ability to disable unredirection - what happens if you choose that?

**Comment by serebit** [comment]
I gave that option a try, but it didn't seem to do anything, even after restarting the session.

**Comment by fossfreedom** [comment]
Similar report https://gitlab.gnome.org/GNOME/mutter/-/issues/1453

**Comment by JoshStrobl** [comment]
It gets worked around by:

1. Ensuring undirect is disabled
2. Requesting the ClutterStage of a display is redrawn
3. Hooking into after-paint
4. Their function that after-paint calls disconnects from after-paint
5. It then triggers a GTask to perform the screenshotting if they are doing an area-type, otherwise normal screenshot op
6. Unredirect then gets (re-)enabled (in said function)

See https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/src/shell-screenshot.c

Does not apply to Wayland, only X11.

**Comment by JoshStrobl** [comment]
Working on this issue. Fortunately we already queue a repaint, so it should just be a matter of dynamically enabling / disabling unredirect.
