### ISSUE TITLE
Bulk Rename

### ISSUE THREAD

**Issue by Bhooty** [BuddiesOfBudgie/budgie-desktop#30]
Anyway you can add a bulk renamer like in thunar or share any way i can add the thunar bulk rename to files. Asking here cause I like the budgie desktop but feel bad when I remember the bulk rename is normal :(

**Comment by fossfreedom** [comment]
Umm - thats a file-manager responsibility - not the desktop GUI itself.  Best discuss that with your distro.

**Comment by Bhooty** [comment]
> Umm - thats a file-manager responsibility - not the desktop GUI itself. Best discuss that with your distro.

thanks for clearing it up :D I am using manjaro budgie but it comes with "FIles" file manager like in solus budgie so thought i should ask here
