### ISSUE TITLE
[Bug] "Incomplete language support"

### ISSUE THREAD

**Issue by abrendtro** [BuddiesOfBudgie/budgie-desktop#306]
### Description

Every time I login to budgie, I get an "incomplete language support" message. When I click "run this action now", the settings seem reasonable (ibus keyboard, American English, etc.).

Can I disable this message, or do I need to adress a problem?

### Budgie version

10.6.1

### Operating System

Ubuntu Budgie 22.04

### Steps to reproduce the issue

1. Log into Budgie Desktop
2. See "Incomplete Language Support" dialog

### Actual result

N/A

### Expected result

N/A

**Comment by fossfreedom** [comment]
this is a tracker for budgie desktop itself.  For distro issues please raise with your regular support forums - so in  this case for ubuntu based issues

askubuntu.com / ubuntuforums.org / discourse.ubuntubudgie.org

**Comment by abrendtro** [comment]
Thank you
