### ISSUE TITLE
[Request] Hide top bar and title bar when maximized

### ISSUE THREAD

**Issue by abrendtro** [BuddiesOfBudgie/budgie-desktop#307]
### Budgie version

10.6.1

### Use-cases

+ Easy Borderless Fullscreen for games
+ The title bar and status bar can be distracting when an app is maximized

### Proposal

+ When a window is maximized (`Alt F10`), hide the status bar and title bar
+ (Optional) `Alt` double-click to restore the window to its original size
+ (Optional) Show the status bar when the app menu is visible (Right Super)

**Comment by fossfreedom** [comment]
You can achieve this via setting panel autohide/intelligence hide is budgie desktop settings, and using the pixelsaver applet on you panel to control the titlebar hiding

**Comment by abrendtro** [comment]
I forgot about this issue for a while. The "toggle fullscreen" key works well for this, as you can have a regular maximized mode (to use the largest window size), then an additional fullscreen mode to also hide title bars, etc.
