### ISSUE TITLE
dead-space click where popovers does not close when using scaling 

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#312]
### Description

Ubuntu 23.04 with 10.7

Scaling set at 200%

Top panel - with places applet on the right side

Immediately clicking on the left hand side of the applet correctly closes the popover when open.

clicking approx 100px away on the left side doesn't close the applet

Clicking approx the size of the popover or more on the left side closes the applet popover.

Seems to be a dead-space when the popover doesn't close.  This occurs for scaling - at 100% the observation is not noted.

### Budgie version

10.7

### Operating System

Ubuntu Lunar

### Steps to reproduce the issue

See description

### Actual result

See description

### Expected result

popover closes always on the left side of the applet

### Additional information

Pinged in matrix.

Staudey also reproduced the same issue.

**Comment by Jacob-Vlijm** [comment]
This is actually a scaling issue. The dead spot is not quit dead; it is at the position where the panel _assumes_ the popover is: exactly the actual position, divided by the scale factor. This is confirmed if we set the scaling to 300%, clicking at 1/3 of the x-position seems "dead", 400%, clicking at 1/4 of the x-position. The widgets inside the popover are considered at the correct position though, we cannot e.g. click a button at 1/2, 1/3, 1/4 of the popover's real position.
