### ISSUE TITLE
[Bug] Less useful application search results since updating

### ISSUE THREAD

**Issue by justchen1369** [BuddiesOfBudgie/budgie-desktop#316]
### Description

Hey, I'm not entirely sure how to describe this, but the search results when searching for applications seem to have become less... useful? since updating. 

### Budgie version

10.7.1

### Operating System

Arch Linux

### Steps to reproduce the issue

Just as an repro example:
1. search "vscode"
2. search "ter"

### Actual result

1. The Itch launcher is the first result. 
2. "LibreOffice Writer" is the first result. 

### Expected result

1. "Visual Studio Code" is the first result. 
2. "Terminal" is the first result.

**Comment by justchen1369** [comment]
seems to be related to #283 and #291

**Comment by serebit** [comment]
I think `Terminal` showing up when you type `ter` makes far more sense than `LibreOffice Writer`. Additionally, I do think the Itch launcher showing up when you type `vscode` is weird, but the search algo doesn't interpret shorthand and is just coming up with the closest match to the literal text string you put in. Fuzzy text matching is tricky.

**Comment by justchen1369** [comment]
Whoops, I swapped the actual and expected on "ter" :p

**Comment by EbonJaeger** [comment]
I pushed a branch with a different text matching algorithm plus a couple other changes that make search results a lot better, at least on my system with the applications I could think of.

Unfortunately, "vscode" isn't actually the name of the program, nor does it appear anywhere, so it's impossible for that to work without special-casing it, which is kinda icky. Searching for "code" works though, on the new branch.

**Comment by justchen1369** [comment]
I'll check that out and report back, thank you!

**Comment by justchen1369** [comment]
works :)

As for the vscode thing, perhaps the relevancy algorithm could also consider abbreviated (keeping only the first letter(s)) version of each word within the application name. That does sound like a pain to get working well, though.
