### ISSUE TITLE
[Request] Add Favorites and New Instance to Task List

### ISSUE THREAD

**Issue by JL102** [BuddiesOfBudgie/budgie-desktop#338]
### Budgie version

 10.6.1

### Use-cases

The Icon Task List has some nice settings and features, such as the ability to set your favorite apps to always show in the list no matter whether they're open or closed. This is missing in Task List, so I have to open the app launcher and search for an app every time I want to open it. I believe this is a significant hindrance to the applet.
Additionally, if I want to launch multiple instances of the same app, there is no way to do so straight from the Task List. I would need to re-launch the app elsewhere or use a command from within the app itself (e.g. "open link in new window" in a web browser).

### Proposal

Please add support for the same favorites system that Icon Task List has. I believe its implementation is very good. 

To stay consistent with the existing menu style of Task List, and with other OSes like Windows, I propose that the favorite/unfavorite button should appear **above** "Close" but **below** "Always on top". I have no preferences for whether it should appear above or below the separator (but if it's to be consistent with Windows, it should be below the separator).

As for appearance/layout, you could either grab the same layout as the bottom row of icons in Icon Task List (★ and + next to each other), or separate it into multiple lines ("☆ Favorite" / "★ Unfavorite" on one line, and "+ Launch New Instance" on the second line). I'm indifferent between the two options, as long as the functionality is there.

I'm also indifferent on whether to include "Close All Windows" as well. If you opt to keep the same visual design as the row of buttons on the Icon Task List, it makes sense to include it for consistency's sake, but I don't personally mind.

**Comment by JoshStrobl** [comment]
Hey, I appreciate you creating this feature request. There are a bunch of other changes we would like to do to the "legacy" Tasklist. I am going to close this in favor of that issue (#95) and will copy / pasta your request there to keep those items as consolidated as possible :)

**Comment by JL102** [comment]
> Hey, I appreciate you creating this feature request. There are a bunch of other changes we would like to do to the "legacy" Tasklist. I am going to close this in favor of that issue (#95) and will copy / pasta your request there to keep those items as consolidated as possible :)

Oops - I didn't find that issue because I only searched for "Task list" and not "Tasklist". Thanks!
