### ISSUE TITLE
sassc is deprecated, use  libsass

### ISSUE THREAD

**Issue by JonathanVQP** [BuddiesOfBudgie/budgie-desktop#343]
### Description

I got all the dependencies installed and when I tried to compile Budgie-desktop, it gave me an error: Program 'sassc' not found or not executable. When I installed sassc and libsass from github, I got another message stating that sassc entry point is deprecated and that I should use pysassc instead. I tried pip3 install libsass and the pip installed it successfully. However, I still cannot compile Budgie Desktop because it cannot locate sassc. 

### Budgie version

Latest version from github

### Operating System

Photon OS Linux v4.0 Rev 2

### Steps to reproduce the issue

1. meson setup --prefix=/usr -Dwith-gnome-screensaver=false .. 2>&1 | tee meson.out
2. ../src/theme/meson.build:5:0: ERROR: Program 'sassc' not found or not executable.
3. Install SASS/libSASS from github
4. Get error that sassc entry point is deprecated, please use pysassc and use pip3 install libsass
5. meson setup again and get ERROR that sassc is not found.

### Actual result

None

### Expected result

Expect budgie-desktop to build properly. 

### Additional information

Not building.

**Comment by serebit** [comment]
Seems like the recommendation on the sass end is to use dart-sass instead:

![image](https://user-images.githubusercontent.com/12981608/228103359-a89bee27-5209-417b-9f0d-93f07d2c4202.png)

It's only available on Arch Linux and Slackware at the moment, though. As for pysassc, we're not going to be adding a dependency on a package that needs to be installed via pip - so I think the move here is to add a build flag to use dart-sass's sass compiler instead.
