### ISSUE TITLE
[Request] Enhance Budgie's menu search by adding the ability to search for acronyms

### ISSUE THREAD

**Issue by Gaarco** [BuddiesOfBudgie/budgie-desktop#347]
### Budgie version

10.7.1

### Use-cases

Right now the search feature of Budgie doesn't account for applications acronyms, but in the Linux world they are extremely common. Two notable examples are the GNU Image Manipulation Program and PulseAudio Volume Control, commonly referred as GIMP and PAVU.
Both those programs have a desktop entry with their full name (at least on Arch) and so searching for GIMP on Budgie won't produce any result.

### Proposal

Extend the search feature to search for acronyms.

Another option would be using more than just the `name` parameter of the `.desktop` file.
Both GIMP and PAVU provide their acronyms as keywords in their desktop entries.

**Comment by fossfreedom** [comment]
I suppose searching via keywords could be used to implement this rather than trying to hard-code certain acronyms?

https://gitlab.gnome.org/GNOME/gimp/-/blob/master/desktop/gimp.desktop.in.in

**Comment by serebit** [comment]
+1 on searching via keywords.
