### ISSUE TITLE
[Bug] Budgie Screenshot's Selection option opens in a window and doesn't screenshot applications

### ISSUE THREAD

**Issue by justinhschaaf** [BuddiesOfBudgie/budgie-desktop#358]
### Description

Attempting to screenshot a selection of the screen doesn't allow me to screenshot anywhere on the screen; instead, a window opens in which I can make a selection to screenshot; however, even this selection doesn't actually screenshot any content and instead only captures the desktop.

### Budgie version

10.7.1

### Operating System

Fedora 38

### Steps to reproduce the issue

1. Open Budgie Screenshot
2. Select the "Selection" option, followed by the screenshot button
3. A transparent "budgie-daemon" window opens, inside which a selection can be made and a screenshot can be taken
4. No matter what is present inside/under the window, only the desktop will be captured

### Actual result

https://user-images.githubusercontent.com/26681724/233763874-c365fc6b-7520-41b1-a5b2-8b354a305d93.mp4

### Expected result

The user should be able to make a selection for the screenshot anywhere on the screen, and the screenshot should include any content within the selection rather than just that chunk of desktop wallpaper.

### Additional information

My GPU is an NVIDIA RTX 2060, proprietary driver version 530.41.03

**Comment by fossfreedom** [comment]
This will probably fixed by upstream mutter changes in a future v44.1 point
release.

It is also fixed by this commit
https://github.com/BuddiesOfBudgie/budgie-desktop/commit/43f8745cedae8051dfff10e3295e54d5599f347c

**Comment by justinhschaaf** [comment]
This appears to have been resolved with [https://bodhi.fedoraproject.org/updates/FEDORA-2023-f1b068dfd5](https://bodhi.fedoraproject.org/updates/FEDORA-2023-f1b068dfd5), thank you so much for your help!
