### ISSUE TITLE
Desktop resolution cannot be changed.[Bug] 

### ISSUE THREAD

**Issue by ashvinlobo** [BuddiesOfBudgie/budgie-desktop#359]
### Description

I tried to change screen resolutions but it just wont change. 

### Budgie version

10.7.1

### Operating System

Fedora 38 Budgie Spin

### Steps to reproduce the issue

Budgie Control Cnter - Displays - Resolutio ( I went for 1600 from 1920 and clicked Apply. Then screen blacks out but it's still in 1920)

### Actual result

Resolution of the screen remains same.

### Expected result

The screen resolution should have changed to 1600 but it did not.

**Comment by EbonJaeger** [comment]
Closing as duplicate of #356

**Comment by tassajaratrek** [comment]
This is and was fixed in only - dew days after reported bug. Its a great spin, never again for regular gnome 44.
