### ISSUE TITLE
Budgie crashes when searching application menu.

### ISSUE THREAD

**Issue by dino8890** [BuddiesOfBudgie/budgie-desktop#365]
### Description

I just finished installing Fedora Budgie when this error happened. One thing to note is that it did not crash before I updated packages (`dnf upgrade`) so it seems this is a problem with recent version.

I would gladly produce stack trace, but I do not know how to start the DE with gdb.

### Budgie version

10.7.1

### Operating System

Fedora 38

### Steps to reproduce the issue

Press Super key or application menu and start typing letters.

### Actual result

Budgie will crash and display crash window.

### Expected result

Application menu should filter apps based on search terms.

### Additional information

Issue was reported by another user on Reddit:

https://www.reddit.com/r/Fedora/comments/12yxmgo/budgie_panel_crashing_when_search_in_start_menu/

NixOS user reported it to NixOS issue tracker as well:

https://github.com/NixOS/nixpkgs/issues/228142

**Comment by JoshStrobl** [comment]
This is fixed in 10.7.2 and was already fixed in Fedora Budgie Spin, the change just hasn't been pushed from bodhi to stable yet.
