### ISSUE TITLE
[Bug] Weird "ghost" rectangle under textfields

### ISSUE THREAD

**Issue by garfieldairlines** [BuddiesOfBudgie/budgie-desktop#368]
### Description

Hello, I bet it's a duplicate but I have no idea how to call it, I get a sort of ghost dropdown menu on many text fields (pictured here the start menu but I also get it on the address bar of librewolf or even here, while writing in this ticket).

I just freshly installed budgie to try it out and I don't know how to fix that, I don't even know how it's called.

If you have a clue I would be thankful.

![image](https://user-images.githubusercontent.com/3239124/235137495-2f7ca8d1-59d0-4169-b308-fc4540f99698.png)

### Budgie version

budgie-desktop 10.7.2 (git-868c87eb32c566eb50f69f80f82eb03c73821561)

### Operating System

Arch Linux / 6.2.12-zen1-1-zen kernel

### Steps to reproduce the issue

Just select any text field.

### Actual result

See ticket

### Expected result

Not getting that rectangle… thing ?

**Comment by JoshStrobl** [comment]
This sounds like common redraw issues with Mutter. For example: https://gitlab.gnome.org/GNOME/mutter/-/issues/2771

Going to close this as there are no actionable items for us. I would encourage you to file an issue with them. Thanks!
