### ISSUE TITLE
[Bug] Highcontrast theme broken on budgie spin of fedora 38

### ISSUE THREAD

**Issue by ludvigng** [BuddiesOfBudgie/budgie-desktop#369]
### Description

Hello!

When using the budgie spin of fedora 38, switching to the highcontrast theme breaks text visibility of the application menu.

### Budgie version

10.7.1

### Operating System

Fedora 38

### Steps to reproduce the issue

Open budgie desktop settings, switch widget theme to highcontrast.

### Actual result

![ezgif com-webp-to-png](https://user-images.githubusercontent.com/50339757/235210406-31e26828-6292-4d78-b980-6c6d4f3f92df.png)

### Expected result

Menu text should be readable, especially for the highcontrast theme for people with impaired vision.

**Comment by serebit** [comment]
The HighContrast theme has always been broken with Budgie, and generally shouldn't be used. We don't support it at the moment, though that may change after the new built-in theme is implemented.
