### ISSUE TITLE
Fuax blur support for budgie-panel

### ISSUE THREAD

**Issue by rbreaves** [BuddiesOfBudgie/budgie-desktop#38]
### Use-cases
Just for style.

### Proposal
Any time a user applies a wallpaper take a screenshot of it, the parts that overlap, & apply a gaussian blur. It's not necessary to implement an entire algorithm just to apply a blur to a panel that'll never have windows behind it imo. Just

**Comment by JoshStrobl** [comment]
Rejected for Budgie 10 series as performance with Mutter and Cogl is a concern. Happy to evaluate blur with Budgie 11 which'll use EFL and have better support for blurs.
