### ISSUE TITLE
Screenshots and notifications fail when audio sink is 'locked'

### ISSUE THREAD

**Issue by pddshk** [BuddiesOfBudgie/budgie-desktop#380]
### Description

I have an external DAC and use it to play music through mpd. When I connect DAC to the computer it is detected by system and system changes audio output to DAC. Then when I start mpd I use this DAC as output with no mixer, so mpd captures DAC and prevents any other process to access DAC until mpd plays music through it.

This leads to following bugs:

1. When trying to make a screenshot `org.buddiesofbudgie.BudgieScreenshot` tries to play screenshot sound through locked device and got stuck at this point (so there's no screenshot window appears) until mpd frees DAC. This also prevents from using Alt+Tab combination.
2. When some notification arises it tries to play notification sound and got stuck until mpd frees audio device and this leads to all notifications arose while DAC was locked showing up all together.

### Budgie version

10.7.2

### Operating System

Solus 4

### Steps to reproduce the issue

1. Install mpd, ncmpcpp, alsa
2. Plug in external DAC (in my case FiiO Q3)
3. Check that sound output device is 'Digital output ...' corresponding to connected DAC
4. Check out DAC name `cat /proc/asound/cards` (my output includes `1 [Q3             ]: USB-Audio - FiiO Q3`)
5. Modify mpd config file to use special output to DAC. Add the following specification to `~/.config/mpd/mpd.conf`
```
audio_output {
	type		"alsa"
	name		"Fiio Q3"       # output name seen in ncmpcpp later
	device		"hw:Q3,0"	# device name from previous step
	mixer_type      "none"
}
```
6. Start mpd, start ncmpcpp, connect it to mpd, select output device in screen no. 7 ("FiiO Q3" in my case as described in previous step)
7. Play some music through DAC with mpd
8. Try to generate some notifications; try to make a screenshot, then try to alt+tab

### Actual result

No notifications shown, no screenshot made, alt+tab stops working right after attempting to make a screenshot.

### Expected result

System ignores inability to play notification sound and screenshot sound and simply rises notifications and makes screenshots without playing their sounds

### Additional information

This may occur because of blocking writes to DAC fd.

**Comment by pddshk** [comment]
This might be achieved without external DAC, just granting mpd priority access to audio device in mpd.conf

**Comment by serebit** [comment]
I don't have an external DAC to test this with and have never used MPD - can you give me steps to reproduce this from scratch, with no existing MPD config?

**Comment by pddshk** [comment]
> I don't have an external DAC to test this with and have never used MPD - can you give me steps to reproduce this from scratch, with no existing MPD config?

To reproduce you need to install alsa, then get name of default output device:

```
$ cat /proc/asound/cards
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xa4418000 irq 147
```

In my case name is `PCH`. Then add the following into `~/.config/mpd/mpd.conf` replacing `PCH` with output from previous command:

```
audio_output {
    type        "alsa"
    name        "default_locked"
    mixer_type  "none"
    device	"hw:PCH,0"
}
```

Don't forget to select this device as output in 7th screen of ncmpcpp.

**Comment by serebit** [comment]
Yep, reproduced. Never used ncmpcpp either, but figured it out. Gotta dig into GStreamer to see if it exposes locked state.
