### ISSUE TITLE
gnome-session will lose --builtin support which means budgie will not launch correctly

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#384]
### Description

From this upstream PR --builtin is going to be dropped.

https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/93

Assuming this is merged - lets assume for GNOME 45 in september, budgie will no longer launch various components from logon - for example (custom?) keyboard shortcut keys 

Thus we collectively need to decide where to go from here.  That PR hardcodes systemd requirements for gnome-session.

### Budgie version

Future

### Operating System

Upstream

### Steps to reproduce the issue

See the upstream PR and this bit https://github.com/BuddiesOfBudgie/budgie-desktop/blob/a018185cd6d7d206de94eba0e7965f8dd590d5bc/src/session/budgie-desktop.in#L16

### Actual result

TBD

### Expected result

Need a way forward if gnome-session fully moves forward with systemd only.

**Comment by JoshStrobl** [comment]
We are still able to specify our session, so we will need to see if --builtin would actually still be needed. Budgie Desktop already effectively requires systemd or systemd-compatible replacements as well, so I do not see this greatly impacting us assuming session launching still actually works.

**Comment by serebit** [comment]
The linked patch was merged yesterday.

**Comment by JoshStrobl** [comment]
Guess it's time to test the impact of the removal of the builtin

**Comment by fossfreedom** [comment]
> https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/99#note_1863786

Well that effectively has told us that we have to fork gnome-session.  It will be merged sooner rather than later...

**Comment by serebit** [comment]
Closing now that we have budgie-session.
