### ISSUE TITLE
[Bug] Displays in the Budgie Control Center not saving or applying changes (Arch edition) 

### ISSUE THREAD

**Issue by darkjake** [BuddiesOfBudgie/budgie-desktop#386]
### Description

Any changes to the Display settings in Budgie Control Center do not apply correctly and are not retained.

Happens with both fresh and old installs, live or not. 

### Budgie version

budgie-desktop 10.7.2

### Operating System

Endeavour OS  Cassini_Nova-03-2023 with system kernel 6.3.3

### Steps to reproduce the issue

Prerequisite. Connect an external display.

Go to Budgie Control Center
Select Displays
Make any change Resolution, set primary display, Scale, display order etc.
Hit Apply
Screen will flicker, you may see your change briefly if you have a TN panel.
The settings will immediately revert to default.

### Actual result

Once your settings are chosen. And after you click on Apply the screen will attempt to make the change, then the changes will revert.

### Expected result

After I click Apply the chosen Display settings should update and be retained.

### Additional information

Type: Desktop 
Processor: Intel 6850k 
Gpu: Nvidia 2060

**Comment by fossfreedom** [comment]
What version of zenity is nstalled?

    zenity --version

**Comment by aandmsantos0910** [comment]
I am running Zenity Ver: 3.44.1 on EndeavorOS and it has the issue.

**Comment by darkjake** [comment]
> zenity --version

3.44.1

**Comment by JoshStrobl** [comment]
Yes this appears to be a regression in the Arch Linux package for budgie-desktop @serebit 

https://gitlab.archlinux.org/archlinux/packaging/packages/budgie-desktop/-/commit/8b222791eff838033c0919533c56f4c12549c530 changed it to "have new zenity" and removed the flag.

The flag is needed for 3.90+, 3.44 should use old flags.

Not a Budgie Control Center issue.

**Comment by serebit** [comment]
Should be resolved with 10.7.2-5.

**Comment by aandmsantos0910** [comment]
The update has been released. I installed it and now I can set my refresh rate and it also holds after a reboot.
