### ISSUE TITLE
Clock with Calendar Applet

### ISSUE THREAD

**Issue by kappaOne** [BuddiesOfBudgie/budgie-desktop#39]
When working, occasionally you just need to quickly know something like what day a certain date falls or vice versa, etc and you don't really want to go into another app or full blown calendar.

Most other desktop environments have this feature (including both Windows, Mac, PopOS, etc). However currently with Budgie when you click the clock, you are presented with a list to choose "System time and date settings" or "Calendar", this in my opinion is unintuitive. 

Budgie calendar applet is already perfect for this use case. Therefore what would be nice is when you click the clock, the calendar applet pops up instead (you could have two buttons under it for the "Time/Date settings" and "Calendar App".

I know the calendar applet is on the raven panel but so is the volume applet but when you click the volume control on the system tray it does show the volume applet, so it would also make it more consistent when clicking the clock to show the calendar applet.

**Comment by guillotjulien** [comment]
You can use this third party applet that does just that: https://github.com/danielpinto8zz6/budgie-calendar-applet/
