### ISSUE TITLE
Provide more information in privilege escalation dialogs

### ISSUE THREAD

**Issue by TheMachine101** [BuddiesOfBudgie/budgie-desktop#390]
The_Machine_101
Mar 26
I have observed after updating application that this authentication is required and presented via pop-up. There are no details provided as to what is requesting the authentication.

I would like to see a details tab on the pop-up detailing what application or process is requiring this (or any other) authentication as it would be beneficial to the security of the OS for all users. This detail is available on other platforms from the pop-up (dialogue box).

I have been referred here by fossfreedom and I attach the following:

fossfreedom
Ubuntu Budgie Team Member
Mar 26
Can you please drop a screenshot with what you are seeing?

The_Machine_101

4h
This is a screenshot of the pop-up:
![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/135080259/4d9daeb2-140d-42df-b53a-a35fcadb03b9)

This is what I would like to see (two examples):
![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/135080259/2f7ae8b5-b122-4939-a70d-941ca96eec4c)
![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/135080259/d4f5db62-131a-4615-9ef5-9959eeb43169)

**Comment by TheMachine101** [comment]
Please note the details tabs

**Comment by EbonJaeger** [comment]
Do you have an example of what shows after clicking the Details button of the KDE dialog?

**Comment by TheMachine101** [comment]
No I don’t but I assume details of the application requiring the authentication.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EbonJaeger** [comment]
Example acquired from a Plasma user:

![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/5157277/5ab7db25-246e-41c1-8f40-ad58537a2f0c)

**Comment by TheMachine101** [comment]
Looks good.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TheMachine101** [comment]
That’s a pity. Thank you for the info.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TheMachine101** [comment]
Hello

This is what I am getting on boot. It appears that my system is corrupted. I would like to know what happened and can it be fixed?

I have been using this flavour of ubunto for quite some time with minimal issues.

Sent from Outlook for iOS<https://aka.ms/o0ukef>

**Comment by TheMachine101** [comment]
Disregard. Problem solved.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ***@***.*** ***@***.***>
Sent: Sunday, August 11, 2024 12:12:00 AM
To: BuddiesOfBudgie/budgie-desktop ***@***.***>
Subject: Locked out of 22.04 LTS

Hello

This is what I am getting on boot. It appears that my system is corrupted. I would like to know what happened and can it be fixed?

I have been using this flavour of ubunto for quite some time with minimal issues.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
