### ISSUE TITLE
[Bug] No background in the power menu window / pop-up

### ISSUE THREAD

**Issue by 18Linky** [BuddiesOfBudgie/budgie-desktop#395]
### Description

The background of the shutdown or sleep menu is transparent when "Integrated theme" is off in the Budgie Settings
If you select an option such as turn off, the background of the window is no longer transparent.

### Budgie version

budgie-desktop 10.7.2

### Operating System

Solus 4.4

### Steps to reproduce the issue

Disable the "Integrated theme" in the Budgie Settings
Click on the "power menu button"

### Actual result

![Snapshot_2023-06-19_23-04-53](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/88231885/22d7ba49-c88c-4b82-993b-8a1e22ba7b31)

### Expected result

Having a dark or white background in this menu

### Additional information

I've had this problem since I installed Solus on my PC yesterday, I've done all the updates available and the problem persists. The only Budgie desktop settings I've tried are the dark theme and the built-in theme.

**Comment by fossfreedom** [comment]
In budgie desktop settings  - style what is the name of the theme you are using?

**Comment by 18Linky** [comment]
The name of the theme is "Plata-Noir"

**Comment by 18Linky** [comment]
Sorry, I accidentally clicked on "close with comment".
The theme I'm using is "Plata-Noir".

**Comment by EbonJaeger** [comment]
This will be fixed by https://github.com/BuddiesOfBudgie/budgie-desktop/pull/381

**Comment by EbonJaeger** [comment]
Let's keep this open since there's no other issues regarding this problem, in case someone else goes searching.
