### ISSUE TITLE
[Bug] Double frames around gnome applications

### ISSUE THREAD

**Issue by hazg** [BuddiesOfBudgie/budgie-desktop#397]
### Description

![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/178218/8b60fcfc-381a-4748-badd-a93011300723)

### Budgie version

budgie-desktop 10.7.1

### Operating System

Ubuntu 23.04

### Steps to reproduce the issue

$ gnome-software

### Actual result

two frames around window

### Expected result

one frame around window

**Comment by fossfreedom** [comment]
Are you running the pixelsaver applet or the global menu applet?

**Comment by hazg** [comment]
> Are you running the pixelsaver applet or the global menu applet?

Removing pixelsaver fixed the window frames.

Thank you.
