### ISSUE TITLE
Background desktop (wallpaper) likely to be changing

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#40]
## Description
Lets keep an eye on this (https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4936) - maybe consider reworking budgie's background handling code since it is directly impacted by the proposed changes i.e. gsettings schema, removal of the gnomebg library.

https://github.com/BuddiesOfBudgie/budgie-desktop/blob/master/src/wm/background.vala

## Budgie version
10.5.3 - possibly mutter for GNOME 42.

## Operating system
N/A

## Steps to reproduce the issue
N/A

## Actual result
If this lands - budgie will not compile with GNOME42 version of mutter - backgrounds will not work either unless reworked.

**Comment by JoshStrobl** [comment]
Classic GNOME. Can't even take backgrounds for granted.

**Comment by serebit** [comment]
How difficult would it be to implement our own background handling in View or Desktop?

**Comment by JoshStrobl** [comment]
It'd be more appropriate in src/wm of budgie-desktop. Budgie Desktop View is really just meant to be a primary-monitor desktop icons implementation, not be responsible for drawing BGs across multiple monitors as well. Plus we have to think about it in the context of Wayland as well, not really applicable for B10 but B11 it will be.

**Comment by fossfreedom** [comment]
@serebit correct - and since its passed feature freeze - unlikely without an exception.

I note the issue hasnt been closed - so worth keeping an eye on - but no need to keep this issue open.

**Comment by serebit** [comment]
I'd suggest perhaps writing up a proposal for implementing background management within budgie-desktop anyway, in a different issue. It seems like something within scope.
