### ISSUE TITLE
[Bug] Long titles in dropdown boxes can cause "unexpected" window rearrangement.

### ISSUE THREAD

**Issue by Cerrakin** [BuddiesOfBudgie/budgie-desktop#402]
### Description

When using Budgie Desktop Settings (this may apply elsewhere, but this is where it appears for me), a long title on say a Widget theme will cause the text to wrap and kinda jumble the look of the window. I can resize the window, which fixes the issue, but the resized window doesn't stay resized so it goes back to jumbled as soon as I close it and reopen it.

### Budgie version

10.7.2

### Operating System

Solus 4.4

### Steps to reproduce the issue

1. Install a long named widget theme. I use the catppuccin frappe GTK theme and that triggers the issue.
2. Open up Budgie Desktop Settings
3. Observe jumble.

### Actual result

![Snapshot_2023-07-08_14-10-31](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/41281403/58a1058a-989b-4372-92c3-778a71cca3a4)

### Expected result

I would expect there to be a maximum length before truncation on dropdown boxes if them being too long causes some strange window rearrangement.

**Comment by serebit** [comment]
This can't be fixed for every GTK combo box, but it can be fixed for the ones in Budgie Desktop Settings.
