### ISSUE TITLE
Output device list overlaps the Apps & Devices buttons [Bug] 

### ISSUE THREAD

**Issue by minhhut** [BuddiesOfBudgie/budgie-desktop#405]
### Description

In Raven, output devices overlaps to the App & Devices buttons. Clicks on collapse/expand button next to volume control doesn't fix the issue.

![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/656141/9b82d634-5f15-443c-ae25-1252480f9e9e)

### Budgie version

10.7.2

### Operating System

Solus 4

### Steps to reproduce the issue

1. Open Widgets panel (Win + A)
2. On Audio Output widget
3. Click on collapse/expand arrow to show App & Devices buttons
4. Click on Devices button
5. See the list of devices are overlap with the buttons

### Actual result

Overlap between output devices and App & Devices buttons

### Expected result

No overlap between them

**Comment by serebit** [comment]
This is a property deliberately set by Materia:
![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/12981608/e2d62672-cf39-4b02-9534-808dd6a557d6)
I would recommend filing an issue [on their bug tracker.](https://github.com/nana-4/materia-theme/issues/new/choose)
