### ISSUE TITLE
[Bug] Trash applet unable to act on items with a "%" in the name

### ISSUE THREAD

**Issue by samlane-ma** [BuddiesOfBudgie/budgie-desktop#409]
### Description

After building the latest budgie desktop from source, Trash applet has difficulties dealing with files that have a "%" in the name. While they show up in the popover, the actions return error messages when attempting to handle these files.

### Budgie version

git f59e6cf622fc5d2befbcccfd75e2d1fc3a563fa2

### Operating System

Ubuntu 23.10

### Steps to reproduce the issue

1. Create a file with a "%" in the file name (i.e "10%")
2. Drag and drop the file on the trash applet (Error message says not supported)
3. Move the file to the trash using a file manager - The file shows up in the trash applet
4. Select the file and attempt to delete it

### Actual result

Error message saying "Unable to delete (null): Operation not supported"

![ss](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/67085765/ab6bc05f-24ef-46fe-9111-bb1dc195410e)

### Expected result

The file to be restored or deleted

**Comment by serebit** [comment]
Reproduced by @EbonJaeger, presumably on Solus. Thanks for testing prerelease—I doubt we would have found this ourselves.
