### ISSUE TITLE
[Request] WLroots based Wayfire instead of mutter

### ISSUE THREAD

**Issue by anoraktrend** [BuddiesOfBudgie/budgie-desktop#411]
### Budgie version

budgie 10X

### Use-cases

Wayland support for 10.X or another possibility to move forward with wayland support that doesn't rely on a gnome based upstream.

### Proposal

Usage of a more advanced Wayland Compositor than mutter with the capacity to use a native to wlroots screen capture protocol would allow for an easier time getting away from x11 than switching to a new toolkit such as QT/efl but would allow for more features such as wobbly windows and others, along with the capacity to use the gtk-layer-shell protocol. 

### References

https://github.com/wmww/gtk-layer-shell
https://github.com/wmww/gtk4-layer-shell
https://github.com/WayfireWM/wayfire

**Comment by serebit** [comment]
We've already announced our intentions to write a wlroots-based Wayland compositor for Budgie 10: https://blog.buddiesofbudgie.org/wayland/
