### ISSUE TITLE
[Bug] Inconsistent system tray volume icon after muting and then rebooting

### ISSUE THREAD

**Issue by Gaarco** [BuddiesOfBudgie/budgie-desktop#417]
### Description

If I mute the volume via systray icon and then reboot, the tray shows the muted icon, but the volume is not

### Budgie version

10.7.2

### Operating System

Arch Linux

### Steps to reproduce the issue

1. Mute the volume via systray
2. Reboot

### Actual result

Systray shows muted icon, but the volume is not muted.

### Expected result

I see two options:

- Systray reset to unmuted state
- Volume muted to reflect the current state

The first should be more consistent: since the volume level is preserved, the mute effect should be too.

**Comment by justchen1369** [comment]
cannot reproduce

**Comment by Gaarco** [comment]
I think it has something to do with [Easy Effects](https://github.com/wwmm/easyeffects). After further investigation I found out that the system tray volume control doesn't work at all if the output device is set to Easy Effects Sink.

**Comment by JoshStrobl** [comment]
Yes, that is because EasyEffects does not respect / listen to volume changes on its sink. It's an upstream issue with EasyEffects.

https://github.com/wwmm/easyeffects/issues/1817
