### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by maximalEbooks** [BuddiesOfBudgie/budgie-desktop#419]
### Budgie version

4.4

### Use-cases

like the solus 4.4 gnome edition, a nvidia compatible mode, it uses either open source nvidia drivers, or I don't remember seeing the 3 options like gnome has in it for solus 4.4. but I might of used iso image mode to USB in rufus instead of DD mode, so if I am wrong sorry, but on the nvidia rtx 2070 card its unable to get a display on the monitor, it just goes to a black screen instead, for the display port connection on monitor. when it fails to load a display the display on my monitor will switch to either my xbox if I have it on, or my other pc connected with htmi. solus Plasma 4.4 works and loads the desktop but budgie image does not, and for the gnome one I do have to pick the NVidia compatibly mode option when booting it from the USB drive. I don't know why plasma works but Budgie doesn't work. I didn't try Budgie on my nvidia rtx 3070 device, or my laptop with the nvidia rtx 1070 , that one works with plasma and gnome, but I never check on the budgie, it might bootup on that 3D card. but Budgie and nvidia rtx 2070 is not currently works out of box, like fedora which I have to use graphics safe mode, then load the nvidia drivers after it installed its that type of problem with budgie. if I use plasma solus or gnome solus they use eopkg install -- desktop.budgie command that will work too, but it doesn't work with the iso image for me on one pc.

### Proposal

add options to the bootup when using iso image of budgie with rufus 4.1

**Comment by serebit** [comment]
This is a Solus issue, not a Budgie one. Separate projects. I'd recommend posting [on the Solus forums](https://discuss.getsol.us/).
