### ISSUE TITLE
[Request] an option for budgie-run-dialog to stay when changing focus

### ISSUE THREAD

**Issue by voidpointer0x00** [BuddiesOfBudgie/budgie-desktop#424]
### Budgie version

budgie-desktop 10.7.2

### Use-cases

I use it to start a set of applications at a time and quite often when I launch an application and start typing the next command/name, one of previous apps appear and the `budgie-run-dialog` is now closed.

So basically **the use case** is sequential launch of an application chain.

### Proposal

 I believe the most convenient way to implement this would be a cli option along the lines of `--keep-focus` or some other. This way it would be possible for the ones interested to reassign the existent `Alf+F2` shortcut to run the same command but with a different option or keep the current behaviour and assign another key combination like `Alf+F3`.

### References

At first I thought https://github.com/BuddiesOfBudgie/budgie-desktop/issues/198 was about the same thing, but it is not :) Although, hopefully, if what I request is not a complicated task, it could be implemented along the side of the referenced issue.

**Comment by JoshStrobl** [comment]
Resolved with #572. Thanks for the contribution @voidpointer0x00, much appreciated!
