### ISSUE TITLE
[Bug] Launching a VirtualBox VM crashes budgie-wm

### ISSUE THREAD

**Issue by scottfk** [BuddiesOfBudgie/budgie-desktop#425]
### Description

VirtualBox (as a host) somehow crashes budgie-wm on first launch of a VM after logging into a fresh budgie session.

When it restarts, certain icons are grouped together in the plank with a question-mark icon (notably VirtualBox Manager, Signal desktop app, and WhatsApp -- but also notably **not** Firefox), and the screensaver can no longer blank the screen.

VirtualBox also gets confused about window-placement on multiple screens (titlebar for fullscreen windows appear on different screen from the content).

I strongly suspect VirtualBox is doing something nasty and budgie is blameless, but maybe budgie could be hardened against such nastiness.

I am reasonably technical and have tried to debug, but I just don't have the chops to find the problem on my own.  I am happy to help, though! 

### Budgie version

budgie-desktop 10.7.2

### Operating System

Ubuntu 23.10 mantic (development branch)

### Steps to reproduce the issue

1. Log into a fresh budgie session
2. Launch the VirtualBox Manager
3. Run a VM

### Actual result

1. budgie-wm crashes and restarts
2. Some icons in plank are now grouped under one question-mark icon
3. Screensaver can no longer power off my screens
4. VirtualBox fullscreen windows frequently separate content from title bar

### Expected result

1. VM launches and I do my work in it sans muss, sans fuss

### Additional information

My rig is 3 physical monitors.  I most commonly work in a VM that has 3 virtual monitors (fullscreen in each of my 3 physical monitors).  The bad behavior is also triggered by VMs with only 1 virtual monitor.

Here's a snippet from syslog:

```
Aug 16 08:21:04 hydra budgie-wm[3157]: Received an X Window System error.
                                       This probably reflects a bug in the program.
                                       The error was 'BadMatch (invalid parameter attributes)'.
                                         (Details: serial 22796 error_code 8 request_code 147 (unknown) minor_code 6)
                                         (Note to programmers: normally, X errors are reported asynchronously;
                                          that is, you will receive the error a while after causing it.
                                          To debug your program, run it with the MUTTER_SYNC environment
                                          variable to change this behavior. You can then get a meaningful
                                          backtrace from your debugger if you break on the meta_x_error() function.)
Aug 16 08:21:04 hydra kernel: traps: budgie-wm[3157] trap int3 ip:7fd49c1c3727 sp:7ffd8c56e510 error:0 in libglib-2.0.so.0.7702.0[7fd49c180000+99000]
Aug 16 08:21:05 hydra gnome-session[2843]: gnome-session-binary[2843]: WARNING: Application 'org.buddiesofbudgie.BudgieWm.desktop' killed by signal 5
Aug 16 08:21:05 hydra gnome-session-binary[2843]: WARNING: Application 'org.buddiesofbudgie.BudgieWm.desktop' killed by signal 5
Aug 16 08:21:05 hydra budgie-wm[5090]: Running Mutter(Budgie) (using mutter 44.3) as a X11 window and compositing manager
Aug 16 08:21:06 hydra org.buddiesofbudgie.BudgieWm.desktop[5090]: Window manager warning: Failed to parse saved session file: Failed to open file “/home/scottfk/.config/mutter/sessions/10a813ceeb1a70c4ad1692166711382700000028430000.ms”: No such file or directory
Aug 16 08:21:06 hydra gsd-media-keys[3051]: Failed to grab accelerator for keybinding settings:playback-repeat
Aug 16 08:21:06 hydra gsd-media-keys[3051]: Failed to grab accelerator for keybinding settings:rotate-video-lock
Aug 16 08:21:06 hydra gsd-media-keys[3051]: Failed to grab accelerator for keybinding settings:hibernate
Aug 16 08:21:06 hydra gsd-media-keys[3051]: Failed to grab accelerator for keybinding settings:playback-random
Aug 16 08:21:06 hydra budgie-wm[5090]: Property 'libinput Accel Profile Enabled Default' for device 'Logitech Advanced Corded Mouse M500s' returned 3 items, expected 2
Aug 16 08:21:06 hydra budgie-wm[5090]: Property 'libinput Accel Profiles Available' for device 'Logitech Advanced Corded Mouse M500s' returned 3 items, expected 2
```

Again...  I really think this is VirtualBox doing something bad.  For grins I tried Cinnamon.  I saw the same behavior.  Cinnamon seemed to be a bit "harder", however, as it came back in better shape.

**Comment by fossfreedom** [comment]
Probably a spice driver issue. Check your vm settings. If it vmsvga then try one of the other display driver  options.

**Comment by fossfreedom** [comment]
Lets monitor this for the moment - 23.10 is going through some large changes at the moment with kernel / graphics / libc etc.

Budgie will shortly be uplifting to v10.8 and magpie.  So things should settle-down by feature freeze end of september.

I'll close this for now since this issue is probably linked to the unstable nature of the archive.

**Comment by fossfreedom** [comment]
Yeah - don't worry - you got that email before I realised you were on 23.10 - you'll be getting the magpie updates in the next few days/week or two as part of regular updates
