### ISSUE TITLE
[Bug] Something went wrong after login to arch with budgie

### ISSUE THREAD

**Issue by Firemanpl** [BuddiesOfBudgie/budgie-desktop#430]
### Description

Hi I installed Budgie via archinstall and after once log in I getting this: 
![IMG_20230825_230756](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/43400128/81d77472-24dd-42a7-8b60-fdb77cda246e)
How to fix it? 

### Budgie version

command not working

### Operating System

arch linux

### Steps to reproduce the issue

1. Install arch with budgie profile and open source graphic drivers, and default option login manager ***-lite 

### Actual result

I can not go to desktop

### Expected result

I should log in and see the desktop

**Comment by Firemanpl** [comment]
![IMG_20230825_232626](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/43400128/4cdf7c67-03ba-4009-9d1a-73a3bb20f7ce)
![IMG_20230825_232434](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/43400128/ee2a2496-75c2-4cf2-8e56-118b9a01b591)
![IMG_20230825_232436](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/43400128/036f5dea-1e66-4a6e-ae14-ec11097c7b7d)
![IMG_20230825_232436_1](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/43400128/55aec067-31a6-4d57-af76-0bce374cdd63)

**Comment by serebit** [comment]
Just installed via archinstall in a fresh VM, everything stock, no additional packages, same settings, and had no issues. I would attempt reinstall, and if you still have problems, file an issue at https://github.com/archlinux/archinstall.
