### ISSUE TITLE
[Request] Toggle to disable scaling of System Tray icons

### ISSUE THREAD

**Issue by solomongrundy6** [BuddiesOfBudgie/budgie-desktop#435]
### Description

Just updated Solus to the most recent sync that updated Budgie to 10.8, and some of the icons in my system tray are now bigger and some are not.  Screenshot below.

As a note, I do have my taskbar larger than the default, so the now enlarged tray icons match the size of my regular icon-tasklist icons.  

### Budgie version

10.8

### Operating System

Solus 4.4

### Steps to reproduce the issue

Update to 10.8 with an enlarged taskbar?

### Actual result

[Screenshot](https://i.postimg.cc/15cqr62H/taskbar-bug.png)

### Expected result

Icons to be uniform size, whether the old small size or the new larger size.

**Comment by serebit** [comment]
Icons in the System Tray applet now scale with panel size, so it's actually intended to be a feature. For now, we can add a toggle to disable scaling.

**Comment by Xrey274** [comment]
> Icons in the System Tray applet now scale with panel size, so it's actually intended to be a feature. For now, we can add a toggle to disable scaling.

If this is intended behavior, then why don't some of the applets/icons scale? For me all the default applets (volume, notifications, power, raven button, weather/time) don't scale at all.

**Comment by JoshStrobl** [comment]
> For me all the default applets (volume, notifications, power, raven button, weather/time) don't scale at all.

Because those are completely different applets. OP filed an issue related to the System Tray. You are talking about the Status applet.
