### ISSUE TITLE
[Request] ship an appropriate portals.conf for xdg-desktop-portal v1.17

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#436]
### Budgie version

10.8

### Use-cases

Define a suitable portal for budgie

### Proposal

Debian and probably other distros are going to request desktop environments to ship a suitable portals.conf file so that it chooses the appropriate xdg-desktop-portal. So for us it probably should be the gtk portal rather than the gnome portal

More information below released by debian and in the link it gives a suggestion for the budgie portal.conf file

### References

Package: cinnamon-common
Severity: normal
Tags: trixie sid
User: [xdg-desktop-portal@packages.debian.org](mailto:xdg-desktop-portal@packages.debian.org)
Usertags: portals.conf

xdg-desktop-portal 1.17.x introduces a new way to select which portals will
be used for which desktop environments, modelled on mimeapps.list:

- each desktop environment should provide a file like
  /usr/share/xdg-desktop-portal/x-cinnamon-portals.conf

- the filename is ${DESKTOP}-portals.conf where ${DESKTOP} is the desktop
  environment's entry in $XDG_CURRENT_DESKTOP (the same as the DesktopNames
  from /usr/share/{x,wayland-}sessions/*.desktop), folded to lower case

- sysadmins and users can override this via files named portals.conf or
  ${DESKTOP}-portals.conf in various locations like /etc/xdg-desktop-portal
  and ~/.config/xdg-desktop-portal

Please see portals.conf(5) or its source code
https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst
for full details.

As a backwards-compatibility mechanism, x-d-p will fall back to trying
to guess the most appropriate portals from the portals' UseIn= fields,
but it will log warnings when it does that, and anyway Debian doesn't
currently ship any portal backends that are flagged as suitable for Cinnamon
(although I see there's an ITP open for x-d-p-xapp, #1038946). Please
add an x-cinnamon-portals.conf to tell x-d-p more explicitly what backends
Cinnamon is meant to be using by default.

For example, if the intention is to try to use the -xapp backend, falling
back to -gtk if -xapp isn't installed or doesn't know how to do something,
the way to write that would be:

[preferred]
default=xapp;gtk;

The desktop environment (either cinnamon-common or some larger metapackage)
should probably also have a Recommends, or at least a Suggests, on whatever
portals would be most appropriate for it.

Thanks,
    smcv

--
This is part of a mass bug filing:
https://lists.debian.org/debian-devel/2023/08/msg00311.html

**Comment by fossfreedom** [comment]
Budgie bug report from Debian 

Bug#1050905: budgie-core: please provide a budgie-portals.conf for xdg-desktop-portal if appropriate

Package: budgie-core
Severity: normal
Tags: trixie sid
User: [xdg-desktop-portal@packages.debian.org](mailto:xdg-desktop-portal@packages.debian.org)
Usertags: portals.conf

xdg-desktop-portal 1.17.x introduces a new way to select which portals will
be used for which desktop environments, modelled on mimeapps.list:

- each desktop environment should provide a file like
  /usr/share/xdg-desktop-portal/budgie-portals.conf

- the filename is ${DESKTOP}-portals.conf where ${DESKTOP} is the desktop
  environment's entry in $XDG_CURRENT_DESKTOP (the same as the DesktopNames
  from /usr/share/{x,wayland-}sessions/*.desktop), folded to lower case

- sysadmins and users can override this via files named portals.conf or
  ${DESKTOP}-portals.conf in various locations like /etc/xdg-desktop-portal
  and ~/.config/xdg-desktop-portal

Please see portals.conf(5) or its source code
https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst
for full details.

Because budgie-desktop declares itself as being GNOME-based with
XDG_CURRENT_DESKTOP=Budgie:GNOME, it has two options:

1. Delegate its choice of portals to GNOME by accepting whatever GNOME
   does in gnome-portals.conf, and don't install a budgie-portals.conf

2. Take control over its own choice of portals by providing a
   /usr/share/xdg-desktop-portal/budgie-portals.conf

If the first option is what the Budgie maintainers want, then this bug
can be closed without further action.

From what I've seen elsewhere, in the short term Budgie probably wants to
use a mixture of -gtk and -gnome? But in the GNOME 45 cycle, it seems to be
switching away from mutter 44/45 to a fork of mutter 43, which might no
longer have the APIs that x-d-p-gnome requires? So the second option is
probably more appropriate. GNOME's gnome-portals.conf was added in
https://salsa.debian.org/gnome-team/gnome-session/-/commit/b201c9c40e3adc7bf0b1c3504bef4c8602aac31d
and might make a good basis for designing a budgie-portals.conf: it
illustrates how a different fallback order can be selected for each portal
interface.

Thanks,
    smcv

--
This is part of a mass bug filing:
https://lists.debian.org/debian-devel/2023/08/msg00311.html

**Comment by serebit** [comment]
We can't ship -gnome because we're no longer using upstream Mutter, so -gtk is the way to go.

**Comment by JoshStrobl** [comment]
Re-opening as v1.17.x is on Fedora 39 and portal is still broken when testing against git, pending further validation.

**Comment by JoshStrobl** [comment]
Local issue due to gnome package sneaking in.

Note to packagers: You really only can have one portal. Pick the gtk one only. Having both will result in breakages even if you specify gtk.
