### ISSUE TITLE
Fix Current Internal Theme

### ISSUE THREAD

**Issue by serebit** [BuddiesOfBudgie/budgie-desktop#44]
A precursor to #22.

Budgie v10.5.3's internal theme is a mess that's inconsistent across underlying GTK themes and just generally looks dated and unpolished, to such a degree that Solus actually hides the option to use the built-in theme. This issue tracks an effort to clean up the stylesheet in-place and bring it up to a reasonable standard before the full redesign in #22, along with making it consistent even when the underlying GTK theme is swapped out.

## Checklist

- [x] Panel
  - [x] Start Panel Region
  - [ ] Center Panel Region
  - [x] End Panel Region
  - [ ] Status Applet
  - [x] Icon Tasklist
  - [x] Clock Applet
  - [ ] Other Applets
  - [x] App Menu
- [x] Raven
  - [x] Raven Applets View
  - [x] Raven Notifications View
- [x] Notification Popups
- [ ] End Session Dialog
- [ ] Sound/Brightness OSD
- [ ] Polkit Dialog
- [ ] Run Dialog

**Comment by serebit** [comment]
Most of the work done so far has been done in master. The rest will be contained within a PR, so @JoshStrobl doesn't yell at me again.

**Comment by rodrigofarias77** [comment]
Thanks for your good work, @serebit.

I am not sure if this is the ideal place for this, but when the panel is at the top, Raven appears to be "denting" it, with or without the internal theme.

![image](https://user-images.githubusercontent.com/130016/152393712-45af9856-8173-4c24-aa34-48fc802c2a87.png)

**Comment by serebit** [comment]
> Replying to @rodrigofarias77

That's a separate problem. Feel free to file an issue for it.
