### ISSUE TITLE
[Bug] Budgie-panel segfault after update, reset panel now system tray icons won't show

### ISSUE THREAD

**Issue by stereotypy** [BuddiesOfBudgie/budgie-desktop#446]
### Description

I'm on Manjaro Budgie and recently a large update was pushed that included Budgie desktop 10.8. Upon rebooting I was getting a segfault on libibus on budgie-panel. Beause I also had an error about some disk stuff I decided to ran fsck but the segfault persisted.
Here is the segfault:
`budgie-panel[1277]: segfault at 30 ip 00007fa8203122d4 sp 00007ffd076ac068 error 4 in libibus-1.0.so.5.0.528[7fa8202f8000+34000] likely on CPU 2 (cop 00007ffd076ac068 error 4 in libibus-1.0.so.5.0.528[7fa8202f8000+34000] likely on CPU 2 (core 2, socket 0)
Code: 77 28 48 8b 3d b5 90 05 00 ff 15 8f 7f 05 00 48 89 df 5b ff 25 dd 7c 05 00 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 f3 0f 1e fa <48> 8b 47 30 4 df 5b ff 25 dd 7c 05 00 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 f3 0f 1e fa <48> 8b 47 30 48 8b 00 c3 0f 1f 40 00 f3 0f 1e fa 48 8b 47 30 48 8b
budgie-panel[3558]: segfault at 30 ip 00007effb82d52d4 sp 00007fff3bc43058 error 4 in libibus-1.0.so.5.0.528[7effb82bb000+34000] likely on CPU 2 (cop 00007fff3bc43058 error 4 in libibus-1.0.so.5.0.528[7effb82bb000+34000] likely on CPU 2 (core 2, socket 0)
Code: 77 28 48 8b 3d b5 90 05 00 ff 15 8f 7f 05 00 48 89 df 5b ff 25 dd 7c 05 00 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 f3 0f 1e fa <48> 8b 47 30 48 df 5b ff 25 dd 7c 05 00 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 f3 0f 1e fa <48> 8b 47 30 48 8b 00 c3 0f 1f 40 00 f3 0f 1e fa 48 8b 47 30 48 8b`

In tty I ran something like 
`startx; sleep 2; nohup budgie-panel --reset --replace &`

And this fixed the segfault. It's unclear to me what was going on with this segfault but probably something to do with system tray I'm guessing.

Now I can get into Budgie desktop but I don't see all my system Tray Icons. It's my understanding system tray was updated for this release. I can see for example Discord and Steam in system tray but I can no longer see the Guake or Gatotray icon that I saw before. Perhaps this is expected behavior as these apps are using outdated tray methods?

### Budgie version

10.8

### Operating System

Manjaro

### Steps to reproduce the issue

Unclear how to repro as it happened on updating Budgie

### Actual result

Budgie-panel segfaulted on update and after reset some tray icons do not show

### Expected result

Budgie-panel should not segfault on update and tray icons should show

**Comment by JoshStrobl** [comment]
In the case of Gatotray, it only supports XEmbed and thus won't be supported.

In the case of Guake, it will attempt to import the appindicator library and create one. When AppIndicator is not found, it will fall back to trying to create a Gtk StatusIcon, which acts similar to XEmbed. So I would make sure you have that installed. See code path at https://github.com/Guake/guake/blob/dcbf64c24e133b57d9023347bd17c13589ebb85f/guake/guake_app.py#L154 

Going to close this issue as there are no actionable items on our part related to those at this time. Feel free to re-open if you have installed appindicator and confirmed that it should be creating the indicator.

If the issue persists related to segfaults, please file a specific issue for that and follow our [Providing Backtraces](https://docs.buddiesofbudgie.org/developer/workflow/providing-backtraces) so we can get more information on it. 

Thanks!
