### ISSUE TITLE
Budgie forces Firefox into Dark Mode [Bug] 

### ISSUE THREAD

**Issue by MarjaE2** [BuddiesOfBudgie/budgie-desktop#447]
### Description

I was looking for options to customize Budgie, to see if I could get it to I opened Firefox from within Budgie. I disabled dark mode. I opened Firefox from within Budgie. It was in dark mode. I tried to find options to disable dark mode there, too, but couldn't see much because it was in dark mode.

### Budgie version

I don't know, I am reporting from Mate because I can't use Firefox in Budgie.

### Operating System

Fedora T2. I can't find the version number.

### Steps to reproduce the issue

Open Budgie. Disable dark mode. I can't recall which settings these were in. Open Firefox.

### Actual result

Firefox is in dark mode.

### Expected result

If this is going to be accessible for users who have trouble reading text in dark mode, it needs to have accessible ways to get everything out of dark mode.

**Comment by serebit** [comment]
Budgie doesn't force Firefox into dark mode, Firefox just ignores Budgie's built in dark mode gsettings key, which is expected. Regardless, this should be resolved by #444, which hooks up the "Dark theme" switch in Budgie Desktop Settings to a key that Firefox actually checks.
