### ISSUE TITLE
[Request] Window Overview (ala Mission Control) for Budgie.

### ISSUE THREAD

**Issue by fizzyizzy05** [BuddiesOfBudgie/budgie-desktop#448]
### Budgie version

10.8

### Use-cases

I really like Budgie, but for me this is a key missing feature that's stopping me using it full time. I use an overview that shows me previews of all my applications so I can quickly switch between them as part of my workflow. I'm proposing introducing a Window/Workspace overview similar to Mission Control in macOS, or the activities overview in GNOME. This will show the user a row of workspaces at the top, and below that show them their all currently open windows within that workspace. 

### Proposal

I made a draft in Figma of how this could look. If necessary, please suggest any tweaks or alterations you'd make to this design.
![OverviewBudgie ](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/85719751/a5bf4f90-8421-42c7-8fd8-8f2ca57d98e9)
This interface uses a similar design to GNOME's Activity Overview, but with the unnecessary features (in the context of Budgie) of that overview removed, namely the Dash (the panel is visible in it's place), the App Grid and the Search box. The current workspace is visible in the centre and uses a limited amount of space to create spatial awareness and make it clear to the user that this is one workspace. The workspaces on the side that are inactive sit to the sides, and are faded out to emphasise that they are currently inactive. Windows within this overview are shown in a dynamic arrangement that can show every window the user has open on that workspace. At the top, a horizontal line of workspaces is shown as a more broad overview of the current workspace count and layout.

**Comment by JoshStrobl** [comment]
Going to close this as it is not in scope for Budgie 10. Exposé is planned for some point in 11 series.
