### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by supernova874** [BuddiesOfBudgie/budgie-desktop#449]
### Description

Status Tray missing some apps (in my system xtreme download manager after 10.8 upgrade) and other Apps like Mailspring can't open via left click (need right click and open inbox) , other games from Lutris (wine) instead of adding their tray icon in the status tray as it was before now pops a Wine System Tray on the Budgie Desktop.

### Budgie version

budgie-desktop 10.8

### Operating System

Solus 4.4

### Steps to reproduce the issue

![Screenshot from 2023-09-09 15-10-02](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/46381042/bc212837-6e85-4639-9952-8c374ee0b9b8)

### Actual result

After running 2 games (Star Trek Online and Battle.net)  those are the pops i mention in my report

### Expected result

To be able to see in the system tray any app that supports it (at least worked in 10.71 version)

**Comment by JoshStrobl** [comment]
Wine does not support Status Notifier and Mailspring needs to specify `activate` in their Status Notifier implementation.

**Comment by supernova874** [comment]
Thank you for telling me that , so need to be implemented from the app , and same with the XDM (Xtreme Download Manager) i pressume
