### ISSUE TITLE
System tray menus are sometimes blank

### ISSUE THREAD

**Issue by EbonJaeger** [BuddiesOfBudgie/budgie-desktop#451]
### Description

Sometimes when opening the menu of a system tray indicator, the menu entries have no text. They're still there, and clicking them still works, just no text is displayed. So far I haven't found a reliable way to reproduce it. My initial thought is that it's related to items in the menu changing, but that's mostly just a guess at this point.

### Budgie version

10.8

### Operating System

Solus 4.4

### Steps to reproduce the issue

1. Right click network-manager indicator
2. Disconnect from or connect to a network
3. Re-open indicator menu

### Actual result

Got it to happen once after disconnecting from the network:

![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/5157277/7e737171-7cbd-4265-a909-39978b16b691)

### Expected result

![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/5157277/587c1c78-7962-42f9-90a6-6fe90e37403b)

**Comment by serebit** [comment]
Saw this myself with nm-applet, so marking as verified. Will investigate.

**Comment by dassuan** [comment]
Same here also with copyQ applet.

**Comment by jahoyne** [comment]
`budgie-panel --replace &disown`, restored the invisible text to the menu here.

AFAIR, I previously logged off and back on, and then did a full reboot with the problem persisting—although it doesn't make sense to me why replacing the current panel is any different from initially creating it?  ¯\_(ツ)_/¯

**Comment by Yannnd** [comment]
Same here, but then with the systray icon of Variety, the rest is okay.

After issuing `budgie-panel --replace &disown` I got the texts back. Though, almost 2 minutes after returning to the prompt, doing nothing at all in the mean time, a message `GLib-GIO-WARNING` appeared in the terminal. Immediately tried the Variety menu: the texts had disappeared again. Tried the `budgie-panel` several times, consequently getteing the same results. Even after logging out and/or reboot exactly the same happened. 

Terminal output:
```
yannnd@solus-box ~ $ budgie-panel --replace &disown
[1] 1943
yannnd@solus-box ~ $ ** Message: 17:10:09.543: libsession.vala:45: DESKTOP_AUTOSTART_ID not set, session registration may be broken (not running budgie-desktop?)

(budgie-panel:1943): Gtk-CRITICAL **: 17:10:09.559: gtk_toggle_button_set_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed

(budgie-panel:1943): GLib-GIO-WARNING **: 17:10:09.685: Received property WindowId with type i does not match expected type u in the expected interface

yannnd@solus-box ~ $ 
(budgie-panel:1943): GLib-GIO-WARNING **: 17:11:01.436: Dropping signal PropertiesChanged of type (sa{sv}as) since the type from the expected interface is ()

yannnd@solus-box ~ $ 
```

**Comment by JoshStrobl** [comment]
Thanks @serebit for the fix.
