### ISSUE TITLE
[Bug] Budgie freezes monitor refresh rarte to 60hz when it is 75hz

### ISSUE THREAD

**Issue by FaisalAhmedAlghamdi** [BuddiesOfBudgie/budgie-desktop#453]
### Description

Title

### Budgie version

budgie-desktop 10.8

### Operating System

Arch linux

### Steps to reproduce the issue

Im not sure, this is a fresh install with only firefox and nvidia drivers installed

### Actual result

stuck on 60hz

### Expected result

hz should be unlocked

**Comment by serebit** [comment]
Refresh rate setting isn't something handled by budgie-desktop—it's handled by gnome-settings-daemon, and applied in magpie. Without reproduction steps or any detailed information on what's going on that would point to this being a Budgie issue, I'm going to close this as invalid. If you have more information that points to this being specifically a Budgie problem—e.g. trying GNOME's X session and finding that it doesn't have this problem—I'll reopen the issue.
