### ISSUE TITLE
[Bug] Horiz. stripes after update of EndeavourOS (Arch Linux) / Budgie

### ISSUE THREAD

**Issue by p-o-seidon** [BuddiesOfBudgie/budgie-desktop#454]
### Description

I'm on EndeavourOS and have done a system update today (last update in June). After reboot the login screen (lightdm) is shown. I enter my creds and bam, the screeen shows coloured stripes only, the system is unusable (this image I found on the net may give you a impression: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMRJe8_UdxlfZ4oFaNY1K6X5iJjHx1NRp3vv9Z7T2P9w&s). 

I found Mate, Cinnamon (Software Rendering) and Openbox working. Cinnamon does not.

On my system Budgie is of version 10.8-1. I then installed the git-version budgie-desktop-git 10.8.r1.ga8df6722-1, which hasn't changed anything for the better.

Hardware: HP EliteBook, Intel Graphics.

Any advise to overcome my situation?

### Budgie version

10.8.r1.ga8df6722-1

### Operating System

EndeavourOS (based on Arch Linux)

### Steps to reproduce the issue

1. Reboot system
2. Enter user name and password
3. Screen changes into coloured, horizontal stripes.

### Actual result

Impossible to place a screenshot here, as the system becomes unusable.

### Expected result

Budgie desktop.

**Comment by serebit** [comment]
If it's also happening on Cinnamon, it's probably a driver issue and not a Budgie one. I would recommend creating a thread on the [EndeavourOS forums](https://forum.endeavouros.com/) asking for support—I've heard that they're generally pretty helpful over there. If investigation through that channel turns up evidence that this is a Budgie issue, comment here and I'll reopen the issue.
