### ISSUE TITLE
Raven is covering part of the top panel

### ISSUE THREAD

**Issue by rodrigofarias77** [BuddiesOfBudgie/budgie-desktop#46]
## Description
When the panel is at the top, Raven apparently covers part of the panel when expanded.

## Budgie version
10.5.3 (compiled at 53515808589d78aa733c797f2284efcf277cb130)

## Operating system
Fedora 35

## Steps to reproduce the issue
1. Move the panel to the top
2. Expand Raven

## Actual result
![image](https://user-images.githubusercontent.com/130016/152393712-45af9856-8173-4c24-aa34-48fc802c2a87.png)

## Expected result
The previous behavior was to expand aligned with the bottom of the panel.

## Additional information
I did not do a proper bisect, but the new behavior was introduced between 361913cb2684ce623d266263356fc07e04eebefa and 239b5c2013a66c6605590c1016b40c53a80a793b

**Comment by serebit** [comment]
Did a proper bisect, and your range actually didn't match what I found. As far as I can tell, the behavior was introduced in 0c802f3.

**Comment by rodrigofarias77** [comment]
Thank you for fixing this!

I think 0c802f31336ef5e056fe5164cee729caa0cc5552 is in that range though:

`$ git log --graph --oneline 239b5c2 ^361913c`
