### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mbevks** [BuddiesOfBudgie/budgie-desktop#462]
### Description

Using an updated Budgie on Solus, the Veracrypt icon does not show-up in the tray after Veracrypt is opened and minimized to tray. 

### Budgie version

10.8

### Operating System

Solus 4.4

### Steps to reproduce the issue

1. Open Veracrypt.
2. Open container file.
3. Click X to minimize to tray.
4. Notice that the icon doesn't show-up in tray.
5. Re-open Veracrypt only to see message "Veracrypt is already running."

### Actual result

No icon in the tray.

### Expected result

Icon in tray.

**Comment by JoshStrobl** [comment]
This should be filed with Solus, as their package does not enable appindicator support. Without that support, it will use a legacy system tray (XEmbed) system that is not supported anymore.

- https://github.com/veracrypt/VeraCrypt/blob/662b8d1b2fd37cac35c2c48539e846c93ad17f7d/src/Build/CMakeLists.txt#L257
- https://github.com/getsolus/packages/blob/main/packages/v/veracrypt/package.yml
