### ISSUE TITLE
[Bug] gnome45 use mutter-13 and clutter-13

### ISSUE THREAD

**Issue by Pro-pra** [BuddiesOfBudgie/budgie-desktop#464]
### Description

gnome45 now use mutter-13 and clutter-13
need regenerate vapi files

### Budgie version

budgie-desktop 10.8

### Operating System

Fedora Rawhide

### Steps to reproduce the issue

.

### Actual result

.

### Expected result

.

**Comment by fossfreedom** [comment]
Our recommendation is to use our mutter fork called magpie from mutter v45 and later. We will not be adding direct mutter support this or future versions. 

https://github.com/buddiesOfBudgie/magpie
