### ISSUE TITLE
Implement Wayland support in TabSwitcher

### ISSUE THREAD

**Issue by JoshStrobl** [BuddiesOfBudgie/budgie-desktop#474]
This is a meta-tasklist for implementation of Wayland support in our Alt+Tab switcher, such as via use of [libxfce4windowing](https://gitlab.xfce.org/xfce/libxfce4windowing). Strict usage of Wnck is not viable as that is limited to X11. libxfce4windowing is designed to support both X11 and Wayland.

**Comment by JoshStrobl** [comment]
Assigned to self, volunteered to work on this in Matrix.

**Comment by EbonJaeger** [comment]
The Windowing portion of this is likely very similar to Simple Tasklist. Maybe that branch can be of some use for figuring out how to leverage libxfce4windowing for this.
