### ISSUE TITLE
Notification icons broken [Bug] 

### ISSUE THREAD

**Issue by solomongrundy6** [BuddiesOfBudgie/budgie-desktop#477]
### Description

I mentioned this in a comment in [the old issue](https://github.com/BuddiesOfBudgie/budgie-desktop/issues/450), but it didn't seem to get noticed and it wouldn't let me re-open the issue, so I'm posting a new one for visibility.  After updating to 10.8.1, notification icons in raven's notification widget are more broken than before.  More icons do not work properly now and give the default GTK missing icon image.   None of the broken icons that I'm encountering now are custom or referencing something I've modified, so I'm fairly certain it's not a naming issue this time - even nemo's notification about ejecting a USB drive has a broken image.  And many of the icons that are broken are not referencing a file on disk anyway, as they are only data streams sent through dbus. (streamlink-twitch-gui notifying you of a channel coming online is an example.)  The icons used by the actual notification that pops up are fine, this is only in the Raven notification widget.

If it matters, I use the Papirus-Light icon theme, but changing themes doesn't seem to change anything with this bug.

[screenshot](https://i.postimg.cc/HnWv5JSs/notificationbug.png)

### Budgie version

10.8.1

### Operating System

Solus 4.4

### Steps to reproduce the issue

Trigger a notification by ejecting a USB drive in nemo or doing various things in lots of apps, then check Raven.

### Actual result

[screenshot](https://i.postimg.cc/HnWv5JSs/notificationbug.png)

### Expected result

correct icon being used

**Comment by EbonJaeger** [comment]
Can you give more examples of broken notifications? I think I just fixed this locally (Nemo works now), but I would like more testing data.

**Comment by solomongrundy6** [comment]
I can't think of any immediately off the top of my head, but if I come across them again I'll mention them here.  Nemo and streamlink-twitch-gui were the two big ones.  All of my notify-send ones are working fine.

**Comment by solomongrundy6** [comment]
The only other broken tooltip I've come across that I forgot about was the Mullvad VPN client, and just glancing at the notification it makes with dbus-monitor makes me think your fix will correct that one too. (It's another one that passes an icon over dbus instead of referencing a file.)  Thanks for all the help and patience!
