### ISSUE TITLE
[Request] "Enable window focus change on mouse enter and leave" behaves unexpectedly on shutdown

### ISSUE THREAD

**Issue by kenhys** [BuddiesOfBudgie/budgie-desktop#483]
### Budgie version

10.8.1

### Use-cases

1. Enable "Enable window focus change on mouse enter and leave" in budgie desktop settings
2. Type win key and popup budgie desktop start menu
3. Click power icon to shutdown on right bottom of start menu

If you enabled "Enable window focus change on mouse enter and leave", can't switch to shown dialog because focus is still remained at same place (this is expected if you didn't move mouse cursor). As a result, reboot,poweroff menu disappear immediately and  you can't click shutdown.

### Proposal

It is useful not showing poweroff dialog in center when "Enable window focus change on mouse enter and leave" is enabled and show it near budgie desktop start menu not to hide dialog immediately.

**Comment by kenhys** [comment]
Here is the screenshot of the actual behavior.

![Peek 2023-10-21 16-03](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/225841/41cdd921-f05c-47f7-95ab-593309ce3668)

**Comment by JoshStrobl** [comment]
> It is useful not showing poweroff dialog in center when "Enable window focus change on mouse enter and leave" is enabled and show it near budgie desktop start menu not to hide dialog immediately.

I don't think that's the correct solution. At first I was suspecting that maybe it was Budgie Desktop View stealing focus, but after enabling the option it still works fine and Budgie Desktop View isn't stealing focus. I'm curious if this is an issue with using an IME?

**Comment by JoshStrobl** [comment]
Closing due to lack of response.
