### ISSUE TITLE
Start budgie-desktop from windows terminal!

### ISSUE THREAD

**Issue by Lurixswe** [BuddiesOfBudgie/budgie-desktop#487]
### Budgie version

budgie-desktop 10.5.1

### Use-cases

Want to start budgie-desktop from windows 11 WSL2

How can i do that ? 

This one works - sudo budgie-desktop --disable-acceleration-check - but i start as root user.

budgie-desktop - startx <-- not working.

**Comment by JoshStrobl** [comment]
We have no plans on supporting Windows. It is expecting that you are using an operating system that has properly packaged Budgie Desktop, various parts of the GNOME stack, and more.
