### ISSUE TITLE
[Bug] Some notifications trigger 'click' action when you close them

### ISSUE THREAD

**Issue by solomongrundy6** [BuddiesOfBudgie/budgie-desktop#496]
### Description

First mentioned by someone on [the Solus forum](https://discuss.getsol.us/d/10013-nemo-bug-after-removing-external-drive), when nemo pops a notification after removing an external drive, if you click on the X to close the notification it opens a second copy of nemo.

I have also had this happen with handbrake - the "put down your cocktail" notification when handbrake finishes an encode will open a second copy of handbrake if you click on the X to close the notification.

### Budgie version

10.8.2

### Operating System

Solus 4.4

### Steps to reproduce the issue

Remove external drive while using Nemo
Click on 'x' on the notification that says the device can be removed
-or-
Encode a short video in handbrake with notification open turned on
Click on 'x' on the notification that says 'put down your cocktail'

### Actual result

Second copy of the program opens

### Expected result

Notification just closes

**Comment by JoshStrobl** [comment]
Resolved with #552
