### ISSUE TITLE
Issue with multiple displays (zenity 4.0.0)

### ISSUE THREAD

**Issue by marek287** [BuddiesOfBudgie/budgie-desktop#497]
https://github.com/BuddiesOfBudgie/budgie-control-center/issues/51

Same issue after updating zenity to verison 4.0.0-1. Downgrading zenity-3.44.2-1 confirmation dialog works.

OS: Arch Linux

**Comment by serebit** [comment]
Should be fixed. Thanks for the report, didn't realize the zenity package got bumped.
