### ISSUE TITLE
[Bug]  sonewconn in `dmesg` while using Budgie 

### ISSUE THREAD

**Issue by littlelevi** [BuddiesOfBudgie/budgie-desktop#498]
### Description

My `dmesg` get spammed while using Budgie desktop. The buffer is literally filled out with it.

```
sonewconn: pcb 0xfffff80010292400 (local:/var/run/devd.seqpacket.pipe): Listen queue overflow: 1 already in queue awaiting acceptance (58 occurrences), euid 0, rgid 0, jail 0
sonewconn: pcb 0xfffff80010292400 (local:/var/run/devd.seqpacket.pipe): Listen queue overflow: 1 already in queue awaiting acceptance (59 occurrences), euid 0, rgid 0, jail 0
sonewconn: pcb 0xfffff80010292400 (local:/var/run/devd.seqpacket.pipe): Listen queue overflow: 1 already in queue awaiting acceptance (58 occurrences), euid 0, rgid 0, jail 0
sonewconn: pcb 0xfffff80010292400 (local:/var/run/devd.seqpacket.pipe): Listen queue overflow: 1 already in queue awaiting acceptance (58 occurrences), euid 0, rgid 0, jail 0
sonewconn: pcb 0xfffff80010292400 (local:/var/run/devd.seqpacket.pipe): Listen queue overflow: 1 already in queue awaiting acceptance (58 occurrences), euid 0, rgid 0, jail 0
sonewconn: pcb 0xfffff80010292400 (local:/var/run/devd.seqpacket.pipe): Listen queue overflow: 1 already in queue awaiting acceptance (59 occurrences), euid 0, rgid 0, jail 0
```

It only happens when I'm logged into Budgie. Under Gnome desktop, it doesn't happen. It also doesn't happen when I'm logged out of X.
Maybe some notifier is spamming `devd`

### Budgie version

10.8.2

### Operating System

FreeBSD 14.0-RELEASE-p3

### Steps to reproduce the issue

Compile Budgie from ports. Log in to budgie desktop(in my case using lightdm), open terminal and check `dmesg` No application is needed, either in autostart or running. Just terminal emulator.

### Actual result

So far, the only problem is that I can't comfortably view my `dmesg`. But spamming the daemon that handle devices, can't be a good thing.
So far, I haven't noticed any major problems, which doesn't mean they aren't there.

### Expected result

No previously mentioned spam in `dmesg`

### Additional information

As far as I know, under FreeBSD, `devd`  perform the same function to `udev` under Linux. X org under FreeBSD is compiled with https://www.freshports.org/devel/libudev-devd providing common interface between these two. This may be edge case related only to FreeBSD, but Linux may have similar behavior.
It is possible that `udev` is smarter than `devd` providing protection against such things.

**Comment by JoshStrobl** [comment]
Budgie Desktop doesn't directly use. You may want to check some of the following since this seems to be common in the BSDs:

- https://forums.freebsd.org/threads/sonewconn-pcb-0xfffff800463fc000-listen-queue-overflow.68674/
- https://forum.netgate.com/topic/178995/pfsense-panic-after-sonewconn-pcb-address-listen-queue-overflow
- https://forums.freebsd.org/threads/sonewconn-pcb-0xff-listen-queue-overflow-already-in-queue-awaiting-acceptance.54597/

Closing pending details that indicate it's an actual Budgie issue.
