### ISSUE TITLE
Live Wallpaper

### ISSUE THREAD

**Issue by GZGavinZhao** [BuddiesOfBudgie/budgie-desktop#50]
### Current Budgie version

budgie-desktop 10.5.3 (git-26cde8fd300a87aba0d085ca50c89728150138d2)

### Use-cases

Linux DEs have traditionally lacked the ability to have live wallpaper like Windows (Wallpaper Engine) and Android. It would be great if Budgie Desktop can add native support for live/animated wallpaper.

The usual process is that the user provides a video file (*.mp4, etc.) and the video will be looped (without sound) on the desktop as the wallpaper.

### Proposal

I'm not really sure how to achieve that, as to my knowledge no DE provides a convenient and intuitive support for live wallpaper. [References](#references) might be helpful, and I have a few ideas about it:

1. There used to be a tool that slices the video files into a lot of images in advance and uses `feh` continuously to set the wallpaper. This is definitely not the way to approach. We should probably use something like `ffmpeg` and pipe the stream to the desktop in some way.
2. Komorebi has a good feature that as soon as the desktop is completely covered by other window(s), it will stop playing the video; the moment you close all the windows or a part of the desktop is not covered, it starts playing again. This can reduce the performance impact and in many cases the user doesn't even realize.

### References

[Komorebi](https://github.com/Komorebi-Fork/komorebi) is a live wallpaper engine that works on Budgie Desktop, so maybe it can be a good starting point. The problem with it is that it changes the layout of the desktop icons and I've found no way to modify that.

**Comment by GZGavinZhao** [comment]
It's just a silly idea. I have no knowledge on this area so it's just a random guess. Sorry if it's misleading.

Komorebi doesn't seem to use `ffmpeg`. It only depends on the following:
```
dependencies = [
      dependency('glib-2.0', version: '>=2.38'),
      dependency('gobject-2.0'),
      dependency('gtk+-3.0', version: '>=3.14'),
      dependency('gee-0.8'),
      dependency('webkit2gtk-4.0'),
      dependency('clutter-gtk-1.0'),
      dependency('clutter-1.0'),
      dependency('clutter-gst-3.0'),
]
```

**Comment by JoshStrobl** [comment]
Going to close this as it isn't going to be in scope for Budgie 10 series. We have to take into consideration the time investment required for this feature and the fact we would need to port it over to Budgie 11 series for feature parity.

**Comment by Anachron** [comment]
Just sneaking in here:

Live wallpapers also have some significant issues that are hard to explain to users, especially newcomers.

Lets say one user has beefy hardware and has hardware acceleration for the video played, the next one is a friend of him, installs Budgie on his netbook and wonders why its crawlingly slow for him, because he has no idea that such a thing exists and how to set it up correctly.

While we can make UI to try to work around this issue, animated wallpapers in linux are imo still a bad idea even today.
