### ISSUE TITLE
Switch to budgie-session

### ISSUE THREAD

**Issue by bobby285271** [BuddiesOfBudgie/budgie-desktop#505]
### Description

Currently we have these lines:

https://github.com/BuddiesOfBudgie/budgie-desktop/blob/74b65648250deae4277f83fe0dc38eb876cdf39b/src/session/budgie-desktop.in#L16

With [gnome-session!93](https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/93) the `--builtin` option was removed. From what I saw gnome-session will fail [when unknown options are given](https://gitlab.gnome.org/GNOME/gnome-session/-/blame/46.alpha/gnome-session/main.c?ref_type=tags#L445):

![](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/20080233/336a4d5c-f3cd-47b8-9856-ce64440523ca)

I am aware of [budgie-session](https://github.com/BuddiesOfBudgie/budgie-session) and I wonder if we can start using that :bow: 

### Budgie version

10.8.2

### Operating System

NixOS (using custom checkout)

### Steps to reproduce the issue

1. Update gnome-session to 46.alpha
2. Try to login

### Actual result

The session does not start (i.e. stuck at lightdm login screen).

### Expected result

The session starts.

**Comment by fossfreedom** [comment]
budgie-session can be used. You are correct that the budgie-desktop.in file needs to be changed to "budgie-session".

budgie-desktop v10.9 will tidy all of this up with revised dependencies such as budgie-session.
