### ISSUE TITLE
[Bug] NetworkManager applet doesn't popup password dialog connecting to WiFi on raspberry pi OS bookworm

### ISSUE THREAD

**Issue by mgrouch** [BuddiesOfBudgie/budgie-desktop#508]
### Description

NetworkManager applet doesn't popup password dialog connecting to WiFi on raspberry pi OS bookworm

### Budgie version

10.7.1

### Operating System

Raspberry Pi OS Bookworm arm64

### Steps to reproduce the issue

Try connecting to a new WiFi networm from menu 'Available Networks'

Actual result
No password popup window

Expected result
password popup window

### Actual result

No password popup window

### Expected result

password popup window

### Additional information

````
Jan 16 05:25:22 lysmarine NetworkManager[925]: <warn>  [1705382722.5383] device (wlan0): no secrets: No agents were available for this request.
Jan 16 05:25:22 lysmarine NetworkManager[925]: <warn>  [1705382722.5391] device (wlan0): Activation: failed for connection 'Home Wi-Fi Network'
````

**Comment by JoshStrobl** [comment]
network-manager-applet is developed by GNOME and not by Budgie Desktop. Please report your issue at https://gitlab.gnome.org/GNOME/network-manager-applet

Budgie 10.7.1 is not a supported Budgie release either. If you have the option to install anything more modern that supports the latest Budgie and GNOME stack, I would suggest doing that.

**Comment by mgrouch** [comment]
What is the supported budgie desktop version on Debian bookworm?

**Comment by JoshStrobl** [comment]
We only support the latest release of Budgie Desktop, which is currently 10.8.2. We don't do backports to old versions of Budgie Desktop, that is done separately by package maintainers such as @fossfreedom. trixie and sid have the latest release of Budgie Desktop.

Probably just easier for you to fire up Budgie Control Center and set up your wifi from there :)

**Comment by JoshStrobl** [comment]
budgie-wm is the expected window manager for Budgie.

**Comment by mgrouch** [comment]
Same issue with budgie 10.8.2

**Comment by fossfreedom** [comment]
What is your login manager?  lightdm? GDM? 

Please detail what is your starting point and how you installed budgie.  With apt recommendations?

I've tried from a testing image on real hardware - installed with no additional options such as the default desktop environment nor any other optional installs.

Then  installed slick-greeter & budgie-desktop, arc-theme and papirus icons packages - accepted all recommendations.  Wifi pop-up was observed.

**Comment by mgrouch** [comment]
It is used without login manager.

To reproduce you can install  lite bookworm version of BBN OS for Raspberry

https://cloudsmith.io/~bbn-projects/repos/bbn-repo/packages/?q=lysmarine

**Comment by fossfreedom** [comment]
That isn't a recognised distro by the team, nor do we recommend using budgie without lightdm.  I would first test from a proper Debian system so that its easier to compare and contrast what is installed.

The password dialog requires policykit and this initiated correctly from a login manager + kicking gnome-session + budgie-desktop.

**Comment by fossfreedom** [comment]
Probably systemd related - much of the gnome stack moved over to using systemd to initialise things.  

This is going to take some investigatory work - look at 

    journalctl -ae --full

Scroll back to look at what's being kicked off around the time of running /usr/bin/budgie-desktop - compare this from a standard Debian budgie install.  

Remember a login manager would ensure firing up all of these in the correct order starting with the xsession stuff https://github.com/BuddiesOfBudgie/budgie-desktop/tree/main/src/session
