### ISSUE TITLE
[Request] Win+Q should open search

### ISSUE THREAD

**Issue by koppor** [BuddiesOfBudgie/budgie-desktop#509]
### Budgie version

10.8.2

### Use-cases

I want to quickly open the search menu. I am used to Windows UX.

### Proposal

When pressing <kbd>Win</kbd>+<kbd>Q</kbd>, the search of the "start menu" should opened.

### References

Explanation by Microsoft:

![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/1366654/38cff13e-d596-41a7-9fb3-6df1dba0860e)

**Comment by serebit** [comment]
Pressing the Win key by itself already opens search within the Budgie Menu, and if you want it to be bound to something else, the shortcuts are customizable in Budgie Control Center.

**Comment by koppor** [comment]
@serebit Thank you for the feedback. I think, the underlying issue was to make Budgie more Windows-immigrant friendly. Maybe, a NixOS configuration could do that.
