### ISSUE TITLE
[Bug] Alt tab not working properly

### ISSUE THREAD

**Issue by durken1** [BuddiesOfBudgie/budgie-desktop#515]
### Description

When alt tabbing between applications the correct window is displayed but it seems the current active window is reverted back to the last used.

### Budgie version

10.9

### Operating System

EndeavourOS (Linux 6.7.2-arch1-1)

### Steps to reproduce the issue

1. Open a browser
2. Open a terminal emulator 
3. Alt tab back to the browser

### Actual result

The browser shows up, but the terminal is still active. Keyboard shortcuts for the browser does not work and typing results in the text showing up in the terminal.

### Expected result

The browser showing up as well as being the active window, with keyboard shortcuts affecting the browser.

**Comment by JoshStrobl** [comment]
Validated. Working on fix.
