### ISSUE TITLE
[Bug]  Tab Switcher doesn't work when "Show all windows" is off

### ISSUE THREAD

**Issue by Solarunit** [BuddiesOfBudgie/budgie-desktop#517]
### Description

Tab Switcher doesn't work correctly when "Show all windows in Tab Switcher"  toggle set to **off**
You can't switch windows per workspace independently like it was in 10.8.

### Budgie version

10.9

### Operating System

Arch

### Steps to reproduce the issue

1. set "Show all windows in Tab Switcher" off
2. open some windows on different workspaces, and see how Tab Switcher doesn't work correctly when you trigger it per workspace

### Actual result

it doesn't work

### Expected result

like in 10.8

**Comment by JoshStrobl** [comment]
I'm able to reproduce this in specific scenarios, including re-filtering not occurring on workspace change. Working on a fix.
