### ISSUE TITLE
[Bug] Problem with 'Switch Window' shortcut. Front window is not focused.

### ISSUE THREAD

**Issue by jjvazro123** [BuddiesOfBudgie/budgie-desktop#520]
### Description

The "switch window" keyboard shortcut raises the selected window to the front, but it does not focus it. So I can still type within the original window as shown in the first video. Additionally, if the focused window is clicked, windows in front of it that are not focused are not pushed back (or the focused window brought forward) - video 2

seems to be the same as this unresolved issue https://forum.endeavouros.com/t/alt-tab-shortcut-getting-stuck-on-the-focused-application/41090

(sorry for any errors, first time submitting one of these)

### Budgie version

10.9

### Operating System

Arch Linux

### Steps to reproduce the issue

cycle through the 'switch window' keyboard shortcut.
select the window you want

### Actual result

![1](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/158523275/01b4fe83-d734-4d4d-973d-d7c81c82f643)
![2](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/158523275/37dfd111-d269-408c-9640-170cc0ed7404)

### Expected result

tab selected is brought forward and focused

**Comment by GZGavinZhao** [comment]
Also seeing this on Solus Budgie.

**Comment by GZGavinZhao** [comment]
Probably duplicate with #515, seems to be fixed in 00ed13f2.

**Comment by JoshStrobl** [comment]
Yes this is a duplicate and already fixed.
