### ISSUE TITLE
[Bug] DeadBeef does not appear in the system tray

### ISSUE THREAD

**Issue by AlexanderZhirov** [BuddiesOfBudgie/budgie-desktop#527]
### Description

DeadBeef does not appear in tray

### Budgie version

10.9.1

### Operating System

Solus 4.5

### Steps to reproduce the issue

Launch DeadBeef

### Actual result

The running DeadBeef icon is not displayed in the tray

![изображение](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/37277056/15d99a10-6862-42fb-abf8-fe76544c4e80)

### Expected result

Displaying the DeadBeef icon in the tray

**Comment by serebit** [comment]
Not a bug on our end: https://github.com/DeaDBeeF-Player/deadbeef/issues/1606. I'd suggest commenting over there and affirming your desire for a tray icon that can work on modern desktop environments.
