### ISSUE TITLE
"Window grouping" incompatible with "Restrict to workspace" for Icon Task List

### ISSUE THREAD

**Issue by zmenciso** [BuddiesOfBudgie/budgie-desktop#53]
Hi there! This is pretty low on the priority list, but it has been urking me for a little while.  I might attempt a solution myself, but I have a ways to go before understanding the `budgie-desktop` codebase.  Thanks for all the love that's gone into this beautiful piece of software <3

## Description
When using both "Window grouping" and "Restrict to workspace," the resulting groups contain windows that are not on the active workspace.

## Budgie version
Behavior seen on the following Budgie versions:
```
budgie-desktop 10.5.1
budgie-desktop 10.5.3
```

## Operating system
Behavior seen on the following operating systems:
```
CentOS Stream release 8 (kernel 4.18.0-358.el8.x86_64)
Arch Linux (kernel 5.16.8-arch101)
```

## Steps to reproduce the issue
Use multiple workspaces, enable but "Window grouping" and "Restrict to workspace" in the Icon Task List, and open different instances of the same application on different workspaces.

## Actual result
Grouped applications contain windows from all workspaces.  In the following screenshot, there is only one instance of GNOME file manager running on Workspace 2 (`~/`), but the Icon Task List shows both the current instance and the instance running on Workspace 1 (`~/Downloads/`).
![image](https://yld.me/raw/ciMO.png)

## Expected result
Grouped applications only contain windows from the active workspace.

**Comment by JoshStrobl** [comment]
This is not a bug but rather an intentional design decision. See #47
