### ISSUE TITLE
[Bug] Tab switcher doesn't loop back to the first window when "Show all windows in tab switcher" is off

### ISSUE THREAD

**Issue by GZGavinZhao** [BuddiesOfBudgie/budgie-desktop#531]
### Description

When "Show all windows in tab switcher" is turned off, tab switcher doesn't loop around to select the first window when the last window is selected.

### Budgie version

10.9.1

### Operating System

Solus 4

### Steps to reproduce the issue

1. Disable "Show all windows in tab switcher" in Budgie Desktop Settings.
2. Open two windows.
3. Hit Alt+tab to open a tab switcher and keep hitting Alt+tab to select the second window.

### Actual result

After the second window is selected, you're stuck. Hitting Alt+Tab doesn't move the selection.

### Expected result

After reaching the second window, hitting Alt+tab should loop around and select the first window.

**Comment by GZGavinZhao** [comment]
Note: it seems like this issue doesn't happen on the first workspace.

**Comment by Solarunit** [comment]
Just wanted to create the same issue :+1: 
I also noticed that focus is shifted to the background window every time you pressing Alt+Tab, here is a video:

https://github.com/BuddiesOfBudgie/budgie-desktop/assets/20891064/9f3c741a-e29f-4bfb-b4d5-a4ef50ffd69a

**Comment by GZGavinZhao** [comment]
This is fixed for me as of 10.9.2, so closing.

**Comment by anon0824** [comment]
Hi, I'm experiencing this issue in 10.9.2:
* Alt+Tab won't loop back past the last window.
  * ...Sometimes. For just one of my virtual workspaces, it works fine, for some reason. All the other ones don't work.
* If "show all windows in tab switcher" is checked on, the issue doesn't seem to occur.

Could I kindly ask for this issue to be re-opened?
(Or should I open my own separate issue?)
