### ISSUE TITLE
[Request] Hide a panel completely

### ISSUE THREAD

**Issue by Hexality** [BuddiesOfBudgie/budgie-desktop#535]
### Budgie version

budgie-desktop 10.8.2

### Use-cases

Some applets are required to be in the panel to start, this would allow applets like WindowShuffler to work without having to have a panel on the screen (useful for people who replaced the panels with custom bars like polybar).

The other use-case would be so people can use custom bars without having an obligatory budgie panel on the screen.
> "oh but you can just set it to automatically hide itself"
Not the same thing, people like me would sometimes pass the mouse over it and simply break the immersion of a clean desktop. Why not simply add an option to have a 0h/w panel if it's process is obligated to be always started?

I tried forcefully hiding it with an workaround but it only works when there's no applets on it, hence why I came here to open this feature request.
![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/17398632/4e816fa2-8dc7-44cf-8ab3-0f0c11c674b5)

### Proposal

An extra option to make a panel always hidden (non-unhideable) to be used with applets like the one mentioned above.

### References
 _No response_

**Comment by JoshStrobl** [comment]
Replacing Budgie panel with alternatives like polybar and completely getting rid of our panels isn't really a feature I'm interested in being supported in Budgie at this time.  You would be better off using a purpose-built tiling window manager with floating window capabilities than trying to shoehorn Budgie into that :)

**Comment by Hexality** [comment]
I use budgie mainly due to raven and it being a lighter window manager, and
there's no easy window manager that can replace it at all.
