### ISSUE TITLE
[Bug] Panel with custom clock format shows (null) when using %v for week of the year

### ISSUE THREAD

**Issue by bjo81** [BuddiesOfBudgie/budgie-desktop#537]
### Description

The clock in the panel should show `14:15:20 19.02.2024 08` when using `%H:%M:%S %d.%m.%Y %W` assuming it uses the output from date - 08 is the week of the year. Instead it only shows (null) as the whole output.

### Budgie version

10.9.1-

### Operating System

Arch

### Steps to reproduce the issue

Edit the settings of the clock in the panel, set it to `%H:%M:%S %d.%m.%Y %W`

### Actual result

(null)

### Expected result

14:15:20 19.02.2024 08

**Comment by fossfreedom** [comment]
Think it should be %u not %W

https://valadoc.org/glib-2.0/GLib.DateTime.format.html

**Comment by bjo81** [comment]
According to your URL, it's %v or %g for "week of the year". Your mentioned %u is day of the week. But thanks for the clarifcation which docs to search.

**Comment by bjo81** [comment]
But with %v also (null) is shown.

**Comment by bjo81** [comment]
Some testing with DateTime showed that the linked docs were wrong. According to https://docs.gtk.org/glib/method.DateTime.format.html it's `%V` which works for number of the week.
