### ISSUE TITLE
[Bug] Workspace Switcher applet doesn't correctly react to mouse wheel.

### ISSUE THREAD

**Issue by pillmuncher** [BuddiesOfBudgie/budgie-desktop#541]
### Description

When I put my mouse cursor over the Workspace Switcher applet and turn the mouse wheel down, the workspace switches to the one on the right. OTOH, when I then turn the mouse wheel up (away from me), then nothing happens.

### Budgie version

Budgie 10.9.1

### Operating System

Solus 4.5

### Steps to reproduce the issue

1. Change to the workspace on the right.
2. Put the mouse cursor over the Workspace Switcher applet.
3. Turn the mouse wheel up (away from you).

### Actual result

Nothing happens.

### Expected result

The workspace should switch to the one on the left.

**Comment by stroodlepup** [comment]
Fixes for this issue may have regressed. Observed same behavior when navigating workspaces with scroll wheel

**Comment by serebit** [comment]
We haven't put out a release with the fix yet, but it's been committed.

**Comment by stroodlepup** [comment]
Thanks. will confirm once it reaches upstream
