### ISSUE TITLE
[Bug] Window switcher instantly closes if "Run Previews" is checked

### ISSUE THREAD

**Issue by CPU-Blanc** [BuddiesOfBudgie/budgie-desktop#543]
### Description

When using Alt+Tab, if `Run Previews` is checked in Previews Control, the window will briefly open, switch to the next available window, then _instantly_ close, making it impossible to actually select what window you want to switch to; you're only able to switch between the 2 most recent.
Disabling the previews returns the expected behaviour - The window remains open and you can select which window to navigate to

### Budgie version

10.9.1

### Operating System

EndeavourOS 6.7.5

### Steps to reproduce the issue

- Open 3 or more different windows
- Ensure `Run Previews` is checked in Previews Control
- Hit ALT+TAB
- Observe the switcher instantly closing

### Actual result

Window switcher closes instantly, despite ALT still being depressed.

### Expected result

The switcher to remain open so long as ALT is depressed

### Additional information

These lines are present in the journal logs. Seem to be related.
```
Feb 24 00:53:36 Linux-PC budgie-wm[1280]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x653268023d00] is on because it needs an allocation.
Feb 24 00:53:36 Linux-PC budgie-wm[1280]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x653265035ed0] is on because it needs an allocation.
```

**Comment by fossfreedom** [comment]
This is not a budgie-desktop project. https://github.com/ubuntubudgie/budgie-extras
