### ISSUE TITLE
[Bug] HotCorners doesn't seem to be working

### ISSUE THREAD

**Issue by thumDer** [BuddiesOfBudgie/budgie-desktop#550]
### Description

Hot Corners applet not working, can't even open it's settings. Clicking on the settings icon does nothing. Same after restart. Don't know where to look for the reason.

### Budgie version

10.9.1

### Operating System

EndevourOS

### Steps to reproduce the issue

1. Add HotCorners applet to panel
2. Click Settings icon

### Actual result

Nothing happens

### Expected result

Settings panel to show up

**Comment by EbonJaeger** [comment]
The HotCorners applet is developed by UbuntuBudgie. You can find the repo for it [here](https://github.com/UbuntuBudgie/budgie-extras). :)

**Comment by thumDer** [comment]
Oh, you are right, I'm sorry :D Will head there, thank you! :)
