### ISSUE TITLE
[Bug] Google Calendar Notifications

### ISSUE THREAD

**Issue by rob-lachapelle** [BuddiesOfBudgie/budgie-desktop#558]
### Description

When receiving a meeting notification via Google Calendar from Chrome. The notification includes "snooze" and "join" buttons that overflow outside the notification window.

### Budgie version

10.9.1

### Operating System

Solus 4.5

### Steps to reproduce the issue

Create a meeting in google calnedar and wait for the notification to come in.

### Actual result

Content of notification overflow outside the notification window.

### Expected result

Notification window should dynamically resize to fit content.

### Additional information

![Snapshot_2024-04-11_07-55-11](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/18560087/2565f2a0-356b-41d7-9aff-7fe55cdfc576)

**Comment by serebit** [comment]
What GTK theme are you using?

**Comment by rob-lachapelle** [comment]
Ah, sorry I should have mentioned that. I am using Colloid. https://github.com/vinceliuice/Colloid-gtk-theme

**Comment by serebit** [comment]
Does this still happen when using a different GTK theme, like Materia or Matcha?

**Comment by sofrlachapelle** [comment]
It does not. Sorry for wasting your time. I'll submit this to vinceliuice for review. Thanks for your help!

**Comment by rob-lachapelle** [comment]
It does not. Sorry for waisting your time. I'll submit this to vinceliuice for review. Thanks for the help!

**Comment by serebit** [comment]
Hey, no problem! This can happen when user and system theming is officially supported. Thanks for reporting :)
