### ISSUE TITLE
[Bug] disabled notifications re-enabled after restart

### ISSUE THREAD

**Issue by system-shock** [BuddiesOfBudgie/budgie-desktop#559]
### Description

I want to disable (mute) all notifcations. When I log out and back in, notifications are enabled again.

### Budgie version

10.9.1

### Operating System

Solus 4.5

### Steps to reproduce the issue

1. Click on the bell icon in the panel.
2. In the notifications window, click on the bell icon to disable (mute) all notifications.
3. Log out of Budgie and log back in.

### Actual result

Notifications are enabled.

### Expected result

Notifications should be disabled.

**Comment by JoshStrobl** [comment]
The feature you are referring to is session-specific. To disable notifications persistently, turn them off via the Notifications section in Budgie Control Center.

**Comment by system-shock** [comment]
In Budgie Control Center under "Notifications" I can only disable notifications for selected applications. I'm getting notifications from Firefox, for example, which is not even on the list. How do I disable notifactions globally?
