### ISSUE TITLE
Switch Input Source Alt+Shift_L crashes budgie-wm when not using ibus

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#56]
## Description
Raised from Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=999609

## Budgie version
10.5.3

## Operating system
Debian Testing/Ubuntu 21.10

## Steps to reproduce the issue

Dear Maintainer,

   * What led up to the situation?

     Typing specific combination key causes budgie-wm segfault.
     At most twice or so is enough to reproduce this issue.

   * What exactly did you do (or not do) that was effective (or
     ineffective)?

     Typing Alt+Shift_L twice or more.
     Digging a bit, it seems that changing input source is related
     and there are some prerequisite conditions.

      * Step1: Using non ibus as input method
        * For example, set fcitx5 by im-config (Using ibus-mozc)
      * Step2: budgie-desktop keboard layout applet does not show any
          keyboard layouts.
      * Step3: Type Alt+Shift_L some times (twice or so)
           It kills budgie-wm. Note that Shift_L+Alt does not cause it.

     I've found two workarounds:

      * Workaround1: As noted above, use Shift_L+Alt.

      * Workaround2: Launch dconf-editor and remove Alt+Shift_L from
   /com/solus-project/budgie-wm/switch-input-source property.
  
      Before: ['<Alt>Shift_L', '<Super>space', 'XF86Keyboard']
      After: ['<Super>space', 'XF86Keyboard']

* note from 19th Feb 2022

As for 10.5.3+git20220217a-1, it seems that Workaround 2 is not effective anymore.

## Actual result

* What was the outcome of this action?

     It kills budgie-wm process, so desktop session is lost.
     Need to login again.

## Expected result

  * What outcome did you expect instead?

     Alt+Shift_L does not kill budgie-wm process.

## Additional information

Debian Release: bookworm/sid
  APT prefers unstable
  APT policy: (500, 'unstable')
Architecture: amd64 (x86_64)

Kernel: Linux 5.14.0-4-amd64 (SMP w/4 CPU threads)
Locale: LANG=ja_JP.UTF-8, LC_CTYPE=ja_JP.UTF-8 (charmap=UTF-8), LANGUAGE=en_US:en
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages budgie-desktop depends on:
ii  budgie-core                                  10.5.3-4
ii  dconf-gsettings-backend [gsettings-backend]  0.40.0-2
ii  gnome-control-center                         1:41.1-1
ii  gnome-menus                                  3.36.0-1
ii  network-manager-gnome                        1.24.0-1

Versions of packages budgie-desktop recommends:
ii  budgie-desktop-view  1.1.1-1
ii  gir1.2-budgie-1.0    10.5.3-4

Versions of packages budgie-desktop suggests:
ii  gnome-terminal  3.42.0-1
ii  nautilus        41.1-1
pn  slick-greeter   <none>

----

Note from DM:

as far as I can see looking at the code, budgie only supports ibus
directly - as far as the upstream applet is concerned.

I agree budgie shouldn't crash - I've reproduced the crash and it is
crashing at this point in the code.

As to why - not sure.

https://github.com/solus-project/budgie-desktop/blob/master/src/wm/keyboard.vala#L105

**Comment by EbonJaeger** [comment]
Glancing at the linked code, I would guess that the array of input sources is never getting initialized for some reason.

It looks like the code that initializes it only gets called when there's a setting change on the sources key. Maybe it would be safer if the array was initialized on construction, and populated in the update function? Not familiar enough with thst area to say for sure.
