### ISSUE TITLE
[Request] Disable window grouping in Icon Tasklist

### ISSUE THREAD

**Issue by pipe01** [BuddiesOfBudgie/budgie-desktop#564]
### Budgie version

10.9.1

### Use-cases

I usually have multiple windows of the same app open and for me it's quite annoying having to right click, looking for which window I want to open, then clicking on it. I would prefer if each window was instead a separate button, like how the legacy task list works.

**Comment by serebit** [comment]
We had this for a long time, and we ended up getting rid of the option because of how difficult it was to manage both behaviors in a single applet. The rewrite of the simple tasklist applet is planned to allow hiding the window label to effectively accomplish this feature.

**Comment by makitso** [comment]
Really miss this option.  Any thoughts about using the xfce window button solution?
