### ISSUE TITLE
[Bug] Screen brightness dims while i am watching a YouTube video

### ISSUE THREAD

**Issue by reefsoft2** [BuddiesOfBudgie/budgie-desktop#570]
### Description

I switched my old mid-2011 iMac to Ubuntu Budgie. Since then, when i watch a YouTube video, randomly, my screen's brightness dims. When i brighten the screen again, i can see in the overlay that the brightness reduced, sometimes even to 0. 

### Budgie version

10.6.1

### Operating System

Ubuntu Budgie

### Steps to reproduce the issue

The bug happens randomly, i can just recommend watching a YouTube video and to hope it happens.

### Actual result

Fully described in the description

### Expected result

The screen's brightness should stay user controlled.

### Additional information

neofetch specs

           ./oydmMMMMMMmdyo/.              user@iMac 
        :smMMMMMMMMMMMhs+:++yhs:           ---------------------- 
     `omMMMMMMMMMMMN+`        `odo`        OS: Ubuntu Budgie 22.04.4 LTS x86_64 
    /NMMMMMMMMMMMMN-            `sN/       Host: iMac12,1 1.0 
  `hMMMMmhhmMMMMMMh               sMh`     Kernel: 6.5.0-28-generic 
 .mMmo-     /yMMMMm`              `MMm.    Uptime: 9 hours, 25 mins 
 mN/       yMMMMMMMd-              MMMm    Packages: 2686 (dpkg), 26 (snap) 
oN-        oMMMMMMMMMms+//+o+:    :MMMMo   Shell: bash 5.1.16 
m/          +NMMMMMMMMMMMMMMMMm. :NMMMMm   Resolution: 1920x1080 
M`           .NMMMMMMMMMMMMMMMNodMMMMMMM   DE: Budgie 10.6.1 
M-            sMMMMMMMMMMMMMMMMMMMMMMMMM   WM: Mutter(Budgie) 
mm`           mMMMMMMMMMNdhhdNMMMMMMMMMm   Theme: QogirBudgie-dark [GTK2/3] 
oMm/        .dMMMMMMMMh:      :dMMMMMMMo   Icons: TelaBudgie-dark [GTK2/3] 
 mMMNyo/:/sdMMMMMMMMM+          sMMMMMm    Terminal: tilix 
 .mMMMMMMMMMMMMMMMMMs           `NMMMm.    CPU: Intel i5-2400S (4) @ 3.300GHz 
  `hMMMMMMMMMMM.oo+.            `MMMh`     GPU: AMD ATI Radeon HD 6630M/6650M/6750M/7670M/7690M 
    /NMMMMMMMMMo                sMN/       GPU: Intel 2nd Generation Core Processor Family 
     `omMMMMMMMMy.            :dmo`        Memory: 1955MiB / 5894MiB 
        :smMMMMMMMh+-`   `.:ohs:
           ./oydmMMMMMMdhyo/.

**Comment by serebit** [comment]
Budgie 10.6.1 is well out of date—it came out two years ago. Regardless, this is unlikely to be an issue with Budgie itself, and more likely to be an issue with the GNOME stack and Mutter and gnome-settings-daemon. Budgie itself doesn't handle screen dimming on idle. I would be interested to see if this still happens if you upgrade to Ubuntu 24.04, though, since that has a much newer Budgie and GNOME.

**Comment by reefsoft2** [comment]
> upgrade to Ubuntu 24.04
for me means "remove flatpak, install snap..."
Let's try it out still, if it might fix this problet
