### ISSUE TITLE
[Bug] Keyboard shortcuts do not work when a menu in a panel applet is open

### ISSUE THREAD

**Issue by JustSoup312** [BuddiesOfBudgie/budgie-desktop#571]
### Description

If a menu applet panel is open, attempting any keyboard shortcut, even the super key, does nothing.

### Budgie version

10.9.1

### Operating System

Fedora Rawhide

### Steps to reproduce the issue

1. Click on any applet in the panel other than the `Budgie Menu`
2. Attempt to use a keyboard shortcut

### Actual result

Keyboard shortcuts do not work while having a Budgie panel applet open.

### Expected result

Keyboard shortcuts work while having a Budgie panel applet open.

**Comment by JoshStrobl** [comment]
Yes, this is intentional as the popovers capture input.
