### ISSUE TITLE
NordVPN for Linux meshnet + Budgie = Unable to Start System. 

### ISSUE THREAD

**Issue by justresisting** [BuddiesOfBudgie/budgie-desktop#580]
### Description

The new NordVPN for Linux caused me to lose access to the internet. When I was able to access the internet again I turned meshnet back on. This caused my system to crash before it fully loaded up 5 times in a row. It wasn't until I logged in from Ubuntu's vanilla Gnome that the system stopped crashing. 

I outlined everything fully with NordVPN [here](https://github.com/NordSecurity/nordvpn-linux/issues/426). This is definitely a problem that was caused by their code. 

However I am certain that using Gnome made me able to access my system again. 

I don't know how to do a stack trace but if you tell me how I will try. 

I wanted to do my due diligence and report the problem here. My explanation was more thorough in the issue I left over at NordVPN. 

### Budgie version

10.8

### Operating System

Ubuntu 23.10

### Steps to reproduce the issue

1. Upgrade to NordVPN Version 3.18.1
2. type `nordvpn set meshnet enabled`.

### Actual result

Turning meshnet on completely borked my system when using Budgie.

### Expected result

Turning meshnet on should have connected all of my devices. 

### Additional information

This is probably all on NordVPN to fix but because this happened on Budgie but did NOT happen on Gnome I thought I would report the bug here as well.

**Comment by JoshStrobl** [comment]
Without logs (journalctl, running budgie-panel in a terminal and starting NordVPN, etc). there isn't any actual way to know / assert that it's Budgie Desktop. We don't really do anything related to the network stack, the closest we get is showing network-manager-applet using our System Tray applet (which uses StatusNotifier).

**Comment by JoshStrobl** [comment]
Also I just noticed that you are on 10.8, which is not a supported version of Budgie Desktop. You should be on 10.9, which should be in the latest Ubuntu LTS, so I would recommend updating to that.

I'm going to close this issue. Should you upgrade to the latest release of Ubuntu with latest Budgie and still be experiencing this, feel free to re-open this with logs.
