### ISSUE TITLE
[Bug] Budgie global menu applet crashes session

### ISSUE THREAD

**Issue by PennyFarthing-GH** [BuddiesOfBudgie/budgie-desktop#583]
### Description

Recently, I installed the `vala-panel-appamenu` and `vala-panel-appmenu-budgie-desktop` packages so that an open application window displays its menu in the top left-hand corner, just like in the older version of Ubuntu Unity 16.04.

I tested this on a user account opened in Solus Budgie and everything seemed to work fine.
Except for the occasional "Oh mince ! Quelque chose s'est mal passé." (“Oops! Something went wrong.”).
![Snapshot_2024-05-30_00-32-29](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/146464942/80540e18-088d-4a82-be83-038d9ce2c5b4)

For me, this happens sometimes when using the `CopyQ` application (it's used to store copy-paste), the session freezes for a moment and ends up producing the above error message. I have no choice else until to close the user session.
When I connect again, the anomaly does not reproduce, it is something punctual.

### Budgie version

10.9.1

### Operating System

Solus 4.5

### Steps to reproduce the issue

This error message happens sometimes when using the `CopyQ` application, for example, to copy and paste data to open a post on the Solus forum. the session is freezing for a moment and then, ends up producing the error message above. And I have not other choice than to close the user session.
When I connect again, the anomaly does not reproduce, it is something punctual.

### Actual result

The session is freezing for a moment (no response) and then, ends up producing the error message above. And I have no choice but to validate the closure of the user session.

### Expected result

For example here, being able to continue writing this post.

### Additional information

Another user in Solus forum  (@asdhio) pointed out a similar problem and @Alfisya of the Solus Team asked to create an issue on GitHub.

**Comment by PennyFarthing-GH** [comment]
Correction: this becomes a recurring problem when you open the `CopyQ` application and click on the `Recycle Bin` icon to delete unnecessary items.

**Comment by EbonJaeger** [comment]
Budgie does not develop that applet. The correct place to report this issue is on the [Vala Panel Appmenu tracker](https://gitlab.com/vala-panel-project/vala-panel-appmenu).
