### ISSUE TITLE
[Bug] Ukrainian keyboard not working properly

### ISSUE THREAD

**Issue by Anjo1920** [BuddiesOfBudgie/budgie-desktop#586]
### Description

After adding the Ukrainian keyboard layout it shows up, but types out on English.

### Budgie version

budgie-desktop 10.6.1

### Operating System

Ubuntu 22.04

### Steps to reproduce the issue

1. Add the Ukrainian keyboard layout
2. Select it
3. Types in English

### Actual result

Types in English

### Expected result

Type normally

### Additional information

https://github.com/BuddiesOfBudgie/budgie-desktop/assets/100439636/f059e2c7-49e6-4c42-9dfa-f1e250368cec

**Comment by Anjo1920** [comment]
Plus, Russian works normally

**Comment by serebit** [comment]
Budgie 10.6.1 is long obsoleted and is no longer supported. If you upgrade to Ubuntu 24.04 and this is still happening, please comment and I'll reopen the issue.

**Comment by Anjo1920** [comment]
> Budgie 10.6.1 is long obsoleted and is no longer supported. If you upgrade to Ubuntu 24.04 and this is still happening, please comment and I'll reopen the issue.

how do i do that?
