### ISSUE TITLE
Unable to build project on Debian

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#6]
## Description
The git project at the moment cannot be built on Debian (or Ubuntu) due to the dependency on budgie-screensaver.

As is - budgie-screensaver is not acceptable for inclusion into their repos due to perceived 'vulnerabilities' of dbus-glib-1 (https://github.com/getsolus/budgie-screensaver/issues/8)

Whether we need to worry  about the current budgie-screensaver is another story - probably is part of the budgie 11 roadmap here.  Mate and XFCE screensavers have exactly the same issue but these are legacy and already in the repos - new software like budgie-screensaver is subject to this ruling.

Request here is to add a meson-option (default is budgie-screensaver) and requisite #ifdef's to allow building against gnome-screensaver

If agreed - I'll do the tweaks.  

Note - This request is to remove the technical debt debian currently carries in its packaging - should allow other debian devs to come onboard without hitting this first roadblock.

## Budgie version
10.5.3

## Operating system
debian sid (3 Jan 2022)

## Steps to reproduce the issue
meson --prefix=/usr --libdir=/usr/lib

## Actual result
Stops at meson.build assert.

## Expected result
build successful.

**Comment by JoshStrobl** [comment]
> Request here is to add a meson-option (default is budgie-screensaver) and requisite #ifdef's to allow building against gnome-screensaver

Note that in addition to this, the User Indicator applet and Raven Powerstrip will also need the respective changes to ensure any dbus communication goes to the interfaces for the respective screensavers.

Seems reasonable though.
