### ISSUE TITLE
[Bug] Zombie Icons on Desktop

### ISSUE THREAD

**Issue by kwalker99** [BuddiesOfBudgie/budgie-desktop#608]
### Description

After logging in the desktop icons appear but are unclickable/sectable, also the desktop (primary) right mouse menu has reduced to just two entries, Budgie Desktop Settings and System Settings.

I am unable to set the primary monitor correctly in a triple monitor setup. However, the right mouse menu is working correctly (full list of entries) on the second and third monitors

This bug or something similar has been around since 2017, as detailed on the Solus github repo.

### Budgie version

10.9.1

### Operating System

Ubuntu Budgie 24.04.1

### Steps to reproduce the issue

Login
try and click on an icon

### Actual result

unable to select or use displayed desktop icons

### Expected result

able to select or use desktop icons

### Additional information

Fresh install, 1 week of setting up. 

Running 6.10.7-1-liquorix-amd64  kernel

Having to use Xorg due to application requirements

**Comment by kwalker99** [comment]
Further testing:

I can create a text file via the right click menu on monitor 2 or 3, when drag this to the primary monitor it makes a copy of the file and it is unselectable

**Comment by JoshStrobl** [comment]
Are you using Budgie Desktop View or Ubuntu Budgie's default, which is Nemo as the desktop icons manager (not something we develop)?

If it isn't Budgie Desktop View, then you should report the issue to the Ubuntu Budgie folks and they can investigate further from there.

> I am unable to set the primary monitor correctly in a triple monitor setup

This wouldn't necessarily be a Budgie Desktop issue but more information should be provided in a separate issue filed against Budgie Control Center.

**Comment by JoshStrobl** [comment]
> I can create a text file via the right click menu on monitor 2 or 3, when drag this to the primary monitor it makes a copy of the file and it is unselectable

Given Budgie Desktop View doesn't provide an option to create files, this isn't an issue with our desktop icons implementation as you're likely using the one from Nemo (file manager).

**Comment by kwalker99** [comment]
I have resolved the issue, i removed budgie-desktop-view and replaced it with nemo-desktop, now everything is workimg perfectly.
