### ISSUE TITLE
[Bug]  changing style->widget to a broken theme and user will be forced to logout; some broken theme missing icon then DE will keep crashed after login

### ISSUE THREAD

**Issue by skygunner** [BuddiesOfBudgie/budgie-desktop#621]
### Description

session crashed while changing style->widget and user will be force to logout

### Budgie version

10.9.2

### Operating System

EndeavourOS

### Steps to reproduce the issue

1 open style, by default widgets is empty here
2 select one for example adept, works
3 change widget to any other widget

### Actual result

session crashed and user will be forced to log out.
after login again, the selected widget is working. 

### Expected result

should not crash here

### Additional information

```shell
                 `:osssssss+-               OS: EndeavourOS x86_64
             `-/ossssssssssssso/.           Kernel: Linux 6.10.11-1-clear
       `.://osssssssssssssssssssso++-       Shell: bash 5.2.37
      .://+ssssssssssssssssssssssso++:      Display (4K MONITOR): 3840x2160 @ 60 Hz in 32″ [External]
    .:///ossssssssssssssssssssssssso++:     DE: Budgie 10.9.2
  `:////ssssssssssssssssssssssssssso+++.    WM: Mutter(Budgie) (X11)
`-////+ssssssssssssssssssssssssssso++++-    Theme: Agualemon [GTK2/3/4]
 `..-+oosssssssssssssssssssssssso+++++/`    Icons: Tela [GTK2/3/4]
   ./++++++++++++++++++++++++++++++/:.      Font: Sans (9pt) [GTK2/3/4]
  `:::::::::::::::::::::::::------``        Cursor: breeze (24px)
                                            Terminal: konsole 24.8.1
                                            CPU: AMD Ryzen 5 5600X (12) @ 4.76 GHz
                                            GPU: AMD Radeon RX 570 Series [Discrete]
                                            Memory: 2.28 GiB / 15.53 GiB (15%)
                                            Swap: Disabled
                                            Locale: en_GB.UTF-8
```

**Comment by JoshStrobl** [comment]
Need to provide some logs e.g. from journalctl.

**Comment by skygunner** [comment]
I believe there could be some bug in Mate desktop's appearence, install them function. So that theme was downloaded and installed via Mate. 
When I testing Budgie, I selected one of the downloaded and installed theme, then Budgie will crash. 
Up on further testing, I did try the whole process again:

I downloaded this theme to local https://www.mate-look.org/p/1230631
and icon theme package https://www.opendesktop.org/p/1296407/
open apperance and install this theme via clicking the install... button and browser to the downloaded archive, done the same with icon theme package.
Program says installed ok, though the theme doesn't have a face cover.
Applying the Qogir dark/light is ok, however late when I try to apply the Qogir theme, desktop crashed immediately.
And in Budgie it is same it crashed while selected the incomplete theme(missing theme icon). 

session error log for mate desktop:
https://pastebin.com/8BY6qVB2
for budgie desktop:
https://pastebin.com/ckLydF2P

it turns out though icon theme reported installed ok in Mate desktop, but in
/home/user1/.icons/Qogir/ folder there's no icon at all.
Icons only exists in Qogir-dark and Qogir-Light folder.
While extract the original icon theme archive, there are icons in the Qogir folder. Wonder why when it gets installed, some icons are missing. It could be a bug of the installing feature. And this causing the /gtk/gtk/gtkiconhelper.c part error out and mate crashed. Not sure if this should report here or report to GNOME , it seems the job of GNOME gtk theme engine to properly parse such situation. 

But also maybe the DE should do something, as I believe download a theme and install it is a fairly normal thing to do, the end user shouldn't left with a completely crashed DE with some theme file problem. After the de crashed, logout and login the de still crash. Only way to fix it is go to tty, read the session error log, figure out what has happened, then go to fix the theme file on the disk. This is a fairly complex and hard fix for non-techy end user, almost impossible.

**Comment by JoshStrobl** [comment]
I'm going to close this issue as I see no actions required on our part.

Qogir GTK theme is known to work with Budgie Desktop and members like @EbonJaeger have used it in the past IIRC. I can't speak for the Qogir icon theme, I would reach out to the icon developer regarding your issue as it is either an issue with the theme or a user error with installing the theme and as a result breaking icon lookups in GTK.

**Comment by skygunner** [comment]
![photo_2024-10-22_09-10-03](https://github.com/user-attachments/assets/f66198ad-a0b0-46c2-8e9f-35e014db09f5)
Yes it could be the theme itself has issue, or the mate de installing the theme package has issue. Those are thrid party issues. 

What I mean is, when such user files(files reside in the user's home folder) gone missing or corrupt, maybe the desktop enviroment could handle this much more graceful instead of just giving up and stopped working.
 
We can assume critical third party components like libs etc to be robust and working as expected, we can't rely on non-critical files/components, user touchable files outside root permission to be always well tested and rock solid. 

In this particular case, 
the de could restore to use the previous working theme and give a notification saying the selected theme is corrupted, instead of stopped here, and stopped working right after login. 

A missing theme icon should not crash the desktop environment and require tech to help recover it.

**Comment by EbonJaeger** [comment]
Without any kind of logs, usually from the system journal, we can't tell what part of the stack is crashing; it could be a part from Budgie, or it could be something else entirely. Without logs, there is no way to know.

**Comment by skygunner** [comment]
would this xsession error log work? It's already in the top post:
for budgie desktop:
https://pastebin.com/ckLydF2P

I believe in it, this particular moment caused the issue:
```shell
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/user1/.icons/Qogir/16@2x/panel/image-missing.svg: Error opening file /home/user1/.icons/Qogir/16@2x/panel/image-missing.svg: No such file or directory (g-io-error-quark, 1)
budgie-session-binary[838]: WARNING: Application 'org.buddiesofbudgie.BudgiePanel.desktop' killed by signal 6
 
** (budgie-daemon:1149): WARNING **: 19:12:35.617: statusnotifier.vala:155: Unregistered status notifier host org.freedesktop.StatusNotifierHost-budgie_24964132-8f0b-11ef-a3e3-b42e9996fb4f
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/user1/.icons/Qogir/22/panel/image-missing.svg: Error opening file /home/user1/.icons/Qogir/22/panel/image-missing.svg: No such file or directory (g-io-error-quark, 1)
 
(budgie-control-center:1743): Gtk-WARNING **: 19:12:35.622: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/user1/.icons/Qogir/16@2x/panel/image-missing.svg: Error opening file /home/user1/.icons/Qogir/16@2x/panel/image-missing.svg: No such file or directory (g-io-error-quark, 1)
 
(budgie-wm:1068): Gdk-CRITICAL **: 19:12:35.679: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
 
(budgie-wm:1068): Gdk-CRITICAL **: 19:12:35.679: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
 
(budgie-wm:1068): Gdk-CRITICAL **: 19:12:35.679: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
 
(budgie-panel:2522): GLib-GObject-CRITICAL **: 19:12:35.744: ../glib/gobject/gsignal.c:1665: parameter 1 of type 'SynapseResultSet' for signal "SynapseDataSink::search-done" is not a value type
 
(budgie-panel:2522): Gtk-WARNING **: 19:12:35.767: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
 
** (budgie-panel:2522): WARNING **: 19:12:35.767: NotificationsApplet.vala:69: Failed to generate our DND pixbuf: Failed to load /home/user1/.icons/Qogir/symbolic/status/notification-disabled-symbolic.svg: Error opening file /home/user1/.icons/Qogir/symbolic/status/notification-disabled-symbolic.svg: No such file or directory
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/user1/.icons/Qogir/16@2x/panel/image-missing.svg: Error opening file /home/user1/.icons/Qogir/16@2x/panel/image-missing.svg: No such file or directory (g-io-error-quark, 1)
```
