### ISSUE TITLE
[Bug] When using compact mode, budgie menu's user menu is ugly/difficult to read

### ISSUE THREAD

**Issue by solomongrundy6** [BuddiesOfBudgie/budgie-desktop#625]
### Description

When using the 'Compact Mode' option for Budgie Menu, it is difficult to read/see the options in Budgie Menu's user menu.  This is not apparent outside of using Compact Mode because the categories listed on the left in the normal mode don't go down that far.  The user menu does slightly darken the entirety of the Budgie Menu when it opens, but is slight enough that it still looks like an unintended bug as if some part of the UI is missing.  I checked with a vanilla solus install in a VM to make sure it wasn't my local theme settings and it does it there too.  It looks even more pronounced when using a light theme.

### Budgie version

10.9.2

### Operating System

Solus 4.5

### Steps to reproduce the issue

Turn on Compact Mode in Budgie Menu Settings
Open User Menu

### Actual result

[screenshot from vanilla install](https://i.postimg.cc/sXy8kQQv/Screenshot-from-2024-10-14-11-19-33.png)
[screenshot in light mode](https://i.postimg.cc/L6N1frB7/foo.png)

### Expected result

something more readable

### Additional information

Probably thousands of ways this could be improved, from a little panel sliding out as a backdrop or a much darker brightness change of the menu behind it among others.

**Comment by solomongrundy6** [comment]
Which CSS class in particular?

Also, the screenshot using a light theme, that is an up-to-date Qogir theme (one of vinceliuice's themes) so I'm not sure I understand why it's still happening there if what you're saying is the case.

You're right about Materia, though, I hadn't realized how old that VM had gotten.  I updated it, made sure it was using Flat-Plat, and the exact same bug appears.

**Comment by EbonJaeger** [comment]
I was mistaken about the CSS class, but the widgets are still selectable. On Solus with Qogir, the popup menu does have a background, in both light and dark mode.

**Comment by solomongrundy6** [comment]
Bizarre.  I installed Qogir in the VM and it does have a background.  But the theme I'm using is the same one and it doesn't?  I must have something odd somewhere.  I'll reopen this later if it turns out it's still a bug, but I don't think that will be the case now.  Thanks for the help.

**Comment by solomongrundy6** [comment]
Turns out I had a second (old) copy of Qogir in my .themes directory, when I thought I was using the one installed as a system package.  Mystery solved.
