### ISSUE TITLE
[Bug] No tray icons for certain apps

### ISSUE THREAD

**Issue by irisdominguez** [BuddiesOfBudgie/budgie-desktop#642]
### Description

I'm not getting tray icons for claws-mail (notifier plugin) and aMule (has to be enable on configuration). It's not a case of having a placeholder icon, there's simply nothing on the system tray for these two apps, which are working properly on an xfce session (on the same system).

### Budgie version

10.9.2

### Operating System

EndeavourOS (rolling)

### Steps to reproduce the issue

1. Install aMule (currently 2.3.3)
2. On settings, general, check "Enable Tray Icon"
3. Listen to the sound of silence, as absolutely nothing happens on the system tray.
4. Close aMule and reopen it.
5. Cry as no new system tray icons appear.

### Actual result

No icons or placeholder appear

### Expected result

An icon or at least a placeholder should appear

### Additional information

I have provided steps for amule as that's faster. For claws mail it's the same, but first you have to install the notifier plugin, which includes between its options a system tray icon.

**Comment by fossfreedom** [comment]
I'm not familiar with amule - but if that system tray icon is trying to display an icon in the X11 only xembed format that will not work on budgie.  That old format has been dropped in recent releases because it will not work under wayland.

**Comment by irisdominguez** [comment]
Agh, that's almost surely the answer, both are pretty old programs. I'm still on X11, so I didn't even thought about it being related to X11/wayland.

I guess there's no workaround for something like this, then, while these communities fix it? Amule is popular enough that will surely be updated at some point, but something like claws mail... its less likely.
