### ISSUE TITLE
No items in application menu

### ISSUE THREAD

**Issue by reppard** [BuddiesOfBudgie/budgie-desktop#65]
I've installed budgie and all the extras via the apt package manager on a system running Pop_OS (basically Ubuntu). Both the App Launcher and Application Menu have no application data.  I have a few other desktop environments installed and they all pull in menu data just fine. Anyone else seeing this?

**Comment by fossfreedom** [comment]
This is an upstream tracker.  For distro specific issues please use your distro support forums.
