### ISSUE TITLE
[Multi Monitor][Firefox] Wrong window position and buttons are actually somewhere else

### ISSUE THREAD

**Issue by dtrunk90** [BuddiesOfBudgie/budgie-desktop#67]
## Description

Firefox always opens on my left monitor maximized. Sometimes it happens that the window isn't maximized and the buttons are somewhere else on the screen. When I found them I'm able to click restore once to get the screen and buttons back to a normal state. Clicking maximize again afterwards and everything is fine. Until it happens again.

## Budgie version

```
$ budgie-desktop --version
budgie-desktop 10.5.1
Copyright © 2014-2019 Budgie Desktop Developers
```

## Operating system

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

## Steps to reproduce the issue

Happens randomly. Not able to reproduce it.

## Actual result

![154534016-fd833fce-67c7-418e-962d-24a51a923bd0](https://user-images.githubusercontent.com/636557/156938585-6f8ee2b1-42fa-4665-bcc0-5b0113a6f9e5.png)

## Expected result
Firefox should be maximized on the left monitor.

**Comment by fossfreedom** [comment]
the correct bug tracker is here for firefox issues.

https://bugzilla.mozilla.org/home

**Comment by dtrunk90** [comment]
Uh, I guess this problem is related to the window manager?!

**Comment by fossfreedom** [comment]
The window manager underpinning budgie is GNOME mutter.  I'm doubtful mutter itself has specific application specific stuff - why firefox opens always on the left monitor is best pursued by that org.
