### ISSUE TITLE
support the freedesktop colour spec

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#74]
For GNOME 42 the latest versions of libhandy and libadwaita support the freedesktop spec to
color apps according to the user preference.

Obviously GNOME 42 apps are not forced to support this - but most do. The theme-styling for
"prefer-dark" is the style-sheet defined by libhandy/libadwaita unfortunately but we'll have to
see how this pans out in the future.

I had a quick look-see to-do this on this (now closed) PR - https://github.com/BuddiesOfBudgie/budgie-desktop/pull/60

This PR built on the existing budgie "dark theme" flag - if set, the freedesktop
color-scheme is set to "prefer-dark". If unticked, the color-scheme is reset to the distro default.

I closed the PR because GNOME state we should not be using the gsettings key but should use dbus on the requisite dbus key to-do all of this - this I'm guessing ensures flatpaks/snaps with the requisite portal will work correctly (https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/) & https://github.com/elementary/granite/pull/529/files

In GNOME Shell there is a prefer dark settings in GNOME 42 version of gnome-control-center.  Our UI is via budgie-desktop-settings so doesnt make sense to copy & implement via budgie-control-center.

Anyway - raising this as a tracker - we as a desktop need to decided if to support these apps that have these forced styling / and how we should support a "prefer dark" / "prefer light" type setting.  We'll see more and more of these types of apps in the near future - GNOME 42 is just the precursor of a larger tranche of apps moving this way.

**Comment by jbicha** [comment]
Specifically, you'll see issues with GNOME 42 apps using GTK3 once you get a version of libhandy that includes https://gitlab.gnome.org/GNOME/libhandy/-/commit/14bd98a0

**Comment by JoshStrobl** [comment]
I already have an issue filed where this is discussed. See #27
