### ISSUE TITLE
Raven's "Clear Notifications" keyboard shortcut no longer working after 10.6 update

### ISSUE THREAD

**Issue by nathanpainchaud** [BuddiesOfBudgie/budgie-desktop#75]
## Description

The keyboard shortcut for clearing notifications in Raven (`Super+C` by default) no longer works. Only the notifications' applet gets reinitialized, but the notifications still are not cleared in Raven. The shortcut was working fine up until Budgie 10.5, but stopped working for me with the recent Budgie 10.6 update (on Solus).

## Budgie version

Budgie 10.6

## Operating system

Solus 4.3

## Steps to reproduce the issue

Receive a notification in Raven. Try to clear it using the keyboard shortcut. Look to see if the notification is still there.

EDIT: Added screenshot of notifications before clear.
![new_notification](https://user-images.githubusercontent.com/23144457/158993914-80db433e-2501-45d5-98d5-6810703fe01a.png)

## Actual result

The notifications are still there.

EDIT: Added screenshot of notifications after clear.
![after_clearing_notifications](https://user-images.githubusercontent.com/23144457/158993951-560b6f1c-7b25-4f88-9f28-b60239654acd.png)

## Expected result
The notifications should have been removed, just as they are when manually clicking on the clear notifications button in Raven.

## Additional information
![image](https://user-images.githubusercontent.com/23144457/158990575-9c52a445-13c7-48ff-aef0-c4372150c514.png)

**Comment by JoshStrobl** [comment]
Unable to reproduce under EndeavourOS.

**Comment by fossfreedom** [comment]
hmm - yep - reproducible under UB 22.04

**Comment by fossfreedom** [comment]
umm.... maybe mistaken ... but I'm guessing nothing is now connected to this signal? https://github.com/BuddiesOfBudgie/budgie-desktop/blob/master/src/raven/raven.vala#L68 which is invoked from a super+C

**Comment by JoshStrobl** [comment]
@fossfreedom Super+C invokes the DBus signal via https://github.com/BuddiesOfBudgie/budgie-desktop/blob/master/src/wm/wm.vala#L302

Code is unchanged in those areas.
