### ISSUE TITLE
Discord splash screen window remains in taskbar

### ISSUE THREAD

**Issue by baraclese** [BuddiesOfBudgie/budgie-desktop#78]
## Description
Discord splash screen (named Discord Updater) remains as taskbar icon even after exiting discord. No discord processes can be seen with ps at that point. When starting and closing discord each time one more discord icon will remain in the taskbar.

## Budgie version
10.6

## Operating system
Arch Linux

## Steps to reproduce the issue
Open discord.

## Actual result
![Screenshot from 2022-03-19 19-32-22](https://user-images.githubusercontent.com/1628879/159134248-882e9bfd-6744-490b-b61f-fdee36ed11cd.png)

**Comment by serebit** [comment]
I can't seem to reproduce this on Arch using the `discord` package. Since there's a few different available Discord packages on Arch (Flatpak, several AUR packages), which one are you seeing this issue with?

**Comment by baraclese** [comment]
I'm using the package from the official repo https://archlinux.org/packages/community/x86_64/discord/
The same issue happens when I start minecraft 1.6.4 via multimc. It does not happen with recent minecraft versions.
When I try to close the discord updater from the taskbar the following gets logged:

budgie-panel[46764]: IconPopover.vala:292: Failed to get window during close.

**Comment by baraclese** [comment]
I just discovered that switching the option 'Window grouping' of the 'Icon Task List' to off seems to be a prerequisite for the error.

**Comment by serebit** [comment]
Oh, yep, now I'm seeing it after disabling window grouping.
