### ISSUE TITLE
Revisit janky digital sound output switching

### ISSUE THREAD

**Issue by baraclese** [BuddiesOfBudgie/budgie-desktop#80]
https://github.com/BuddiesOfBudgie/budgie-desktop/blob/e0f5d0529ef3fd95959198c41d0529e0b54cff0a/src/raven/sound.vala#L228

Is this still the case? I don't have a problem switching outputs in the control center so I vote for it being possible in raven as well.

**Comment by serebit** [comment]
Paging @JoshStrobl, since he's likely to know why it's still disabled.

**Comment by JoshStrobl** [comment]
> Is this still the case?

Yes.

> I don't have a problem switching outputs in the control center so I vote for it being possible in raven as well.

Congrats. Your one system does not reflect the larger whole of the userbase. S/PDIF outputs had issues either not working at all, or failing during the switch, which is why I added it in the first place.

I don't need to be paged. I get emails on new issues.
