### ISSUE TITLE
Icons are not displays or the apps panel when I try to launch anyone non-favorited app, but option related to this is disabled

### ISSUE THREAD

**Issue by SoKnight** [BuddiesOfBudgie/budgie-desktop#81]
## Description

I toggled the `only show favorited` option of the icon task list applet on my primary apps panel (and I don't have anymore panels) and after that all non-favorited apps icons are not visible on the panel until I open desktop settings again and toggle this option twice (turn on -> turn off). After this action I fixed this issue for already opened windows, but any new windows still not displaying until I do that again to fix this issue again...

## Budgie version

Budgie Desktop 10.6 (actual build from the official Solus eopkg repository)

## Operating system

Solus 4.3 Furtitude (Budgie)

## Steps to reproduce the issue

1. Open `Budgie Desktop Settings`
2. Click on your panel where apps icons are displayed
3. Click on `Icon Task List` panel applet
4. Toggle `Only show favorited` option in the applet settings (turn on)
5. Toggle that again (turn off)
6. Reboot your system fully
7. Try to open new window of anyone non-favorited app
8. Check that it's not displaying on the panel
9. Open `Budgie Desktop Settings`
10. Toggle favorited apps showing option twice (turn on -> turn off)
11. Check that opened window's icon are displays on the panel
12. Try to open another app
13. This icon isn't displays again...
14. Fix this again with double option toggling
15. It's displays again... WTF

## Actual result

Icons of new opened apps are not displaying on the panel

## Expected result
This icons must be displayed when the `Only show favorited` option is **disabled**!

## Additional information
When I opened a new window of anyone **favorited** app then it's displayed correctly, but of anyone non-favorited isn't.
Sorry for my bad english :(

https://user-images.githubusercontent.com/46436573/159278246-1060f342-233b-4a96-a68c-82ecf55b5ca3.mp4

**Comment by serebit** [comment]
I've managed to reproduce this on EndeavourOS, with the caveat that "Restrict to Workspace" *must* be enabled for this to happen. I wasn't able to reproduce it when that setting was disabled.
