### ISSUE TITLE
Compatibility with gnome-bluetooth3

### ISSUE THREAD

**Issue by gmbr3** [BuddiesOfBudgie/budgie-desktop#82]
GNOME Bluetooth 42 has changed the API
I tried to fix it but have now got stuck
My changes so far are available at [gmbr3/budgie-desktop](https://github.com/gmbr3/budgie-desktop/tree/bluetooth)

Failed build log:
[build-log.txt](https://github.com/BuddiesOfBudgie/budgie-desktop/files/8327112/build-log.txt)

**Comment by fossfreedom** [comment]
gnome-bluetooth3 and gnome-bluetooth are separate.

Budgie requires gnome-bluetooth for its build.

We will need to evaluate whether to support gnome-bluetooth3, bluez or blueman in the future being aware of potential GTK4/libadwaita and other areas that GNOME maybe considering for their latest stack.

Marking this as an enhancement.

**Comment by gmbr3** [comment]
Yeah I opened this because this will kill Budgie on openSUSE Tumbleweed in the next few days (whenever GNOME 42 ships)

**Comment by fossfreedom** [comment]
Very odd decision for the distro. They are two different api's and should be packaged separately.  Just like libhandy-0 and libhandy-1

**Comment by gmbr3** [comment]
I can bring it back, they are getting rid because I don't control GNOME so they don't know I need it.

**Comment by fossfreedom** [comment]
I would prefer that you pursue this with the relevant maintainers of your distro.

As a fallback I suppose, a meson build option could be quickly devised to build without bluetooth support.  Would prefer not to go down that route.

**Comment by gmbr3** [comment]
As I said that is what I will do but that doesn't answer the question of what Budgie does

**Comment by JoshStrobl** [comment]
Seeing as the existing ABI should stay around, just like libsoup has with libsoup3 being released, a change in how we implement bluetooth support is not a pressing matter. It is something which would be nice to get updated (e.g. use Bluez and upower to communicate with the device and get its charge status, performance connection and disconnection operations, as a couple examples). Right now our bluetooth support is fairly basic, so you would not be losing much just by omiting its support currently.

**Comment by JoshStrobl** [comment]
I am going to be going this task given we will be revamping our Bluetooth applet and supporting Bluez directly.
