### ISSUE TITLE
When selecting multitasking in the settings it crashes the settings dialog and wont re-open

### ISSUE THREAD

**Issue by Torkamata** [BuddiesOfBudgie/budgie-desktop#83]
When selecting Multitasking in the settings it crashes the settings dialog. After this occurs I am not longer able to launch "settings" from the icon, I click on the icon and nothing happens, this is repeatable on 10.6 and 10.5.

**Comment by fossfreedom** [comment]
You should be using budgie-control-center with 10.6.

You shouldn't be using gnome-control-center
