### ISSUE TITLE
Random apps appear in Icon Task List

### ISSUE THREAD

**Issue by steakscience** [BuddiesOfBudgie/budgie-desktop#85]
## Description

Random apps appear in Icon Task List

## Budgie version

v10.6

## Operating system

Endeavour OS (arch based) 2021.12.17

## Steps to reproduce the issue

1. Be in a full screen app (I think)
2. Press Alt-Tab
3. "Launch preview daemon" icon may sometimes appear in Icon Task List and can only be removed via favorite > unfavorite

Alternative steps
1. Launch Steam
2. Exit Steam
3. There should now be a Steam icon in Icon Task List

![image](https://user-images.githubusercontent.com/2727095/160235569-723c5159-831b-4771-94ed-8933585c72fd.png)

**Comment by guillotjulien** [comment]
Could be related to #78. Will test later

**Comment by wesleycpdev** [comment]
Just like #78 ?
![image](https://user-images.githubusercontent.com/72578914/160218272-d3a7a5af-9be5-429c-85ec-a13e511d0fcb.png)

**Comment by steakscience** [comment]
> Can you send a screenshot of your icon tasklist configuration in Budgie Desktop Settings? It'll make it easier for us to reproduce the bug.

![image](https://user-images.githubusercontent.com/2727095/160235599-177b890c-4e24-4f41-a4b8-f2ba6448ad67.png)

**Comment by JoshStrobl** [comment]
@steakscience I have updated `budgie-desktop-git` with a revision (current master) that includes various fixes. It would be appreciated if you could install that (using `yay`  would be easiest), relog, and check if the issues perses.

Thanks!

**Comment by serebit** [comment]
@guillotjulien has managed to reproduce this on latest git master, and is working on a fix. Marking as verified.

**Comment by JoshStrobl** [comment]
New fix in master from @guillotjulien if you would like to update your budgie-desktop-git @steakscience and get back to us on if your issue is resolved.

**Comment by steakscience** [comment]
> New fix in master from @guillotjulien if you would like to update your budgie-desktop-git @steakscience and get back to us on if your issue is resolved.

The issue was that I was on the official package (which was stuck on the Solus repo), switched to the AUR one now. 

Will update findings here.

**Comment by steakscience** [comment]
@JoshStrobl I believe this is fixed for me as well!
