### ISSUE TITLE
Add dock ability for panel.ini/layouts

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#88]
### Current Budgie version
10.6

### Use-cases
Ubuntu Budgie 22.10 is considering dropping Plank and using the inbuilt budgie dock capability now that the icon sizing issues for the panel have been resolved (yay!).  This will mean our default layout will be a true budgie only experience without needing a third-party app.

To enable this will require the ability to specify a panel in dock mode as part of the initial user experience.

### Proposal
At the moment in a panel.ini configuration we can specify extra panels, the applets contained therein, the size and the location of the panel.

The proposal here is to add a series of options in addition to "Position" and "Size" :

"AutoHide" with the values defined in the budgie desktop settings panel settings Automatically Hide drop-down
"Transparency"  with the values defined in the budgie desktop settings panel settings Transparency Hide drop-down
"DockMode" with a True/False value

Maybe needed is "Shadow" and "StyliseRegion" boolean values

### References
https://github.com/BuddiesOfBudgie/budgie-desktop/blob/master/src/panel/manager.vala#L1243

**Comment by JoshStrobl** [comment]
Seems completely reasonable to me :+1:

**Comment by serebit** [comment]
Almost done with this locally. Adding Shadow/Stylize is going to be trickier.
