### ISSUE TITLE
Sort entries in Run Dialog depending on the search text

### ISSUE THREAD

**Issue by markussawatzki** [BuddiesOfBudgie/budgie-desktop#89]
### Current Budgie version
10.6

### Use-cases
When using the run dialog and searching for a term, all non-matching applications are hidden. However, the results are not sorted "smartly" but are sorted alphabetically. This can be annoying since unnecessary amount of typing is required in order to pin down the application I search for.   
In the following image, I am searching for "firefox" and "fire" does not suffice. In my case, I need to add another "f" or use the key arrows before I can press enter.
![screenshot_22_03_28_19_33_39](https://user-images.githubusercontent.com/50970356/160460562-f7546713-29df-4b21-a929-1d8f9e2a3880.jpg)

### Proposal
The search in the  budgie menu already implements "smart" sorting. From what I can make out, the relevant code for that is in [`do_sort_list`](https://github.com/BuddiesOfBudgie/budgie-desktop/blob/07007bf22d20ae1c336013db1baf11686ede9a84/src/applets/budgie-menu/BudgieMenuWindow.vala#L584) and [`get_score`](https://github.com/BuddiesOfBudgie/budgie-desktop/blob/07007bf22d20ae1c336013db1baf11686ede9a84/src/applets/budgie-menu/BudgieMenuButtons.vala#L113).  
This code should be easily portable to the run dialog. For example, [`set_sort_func`](https://valadoc.org/gtk+-3.0/Gtk.ListBox.set_sort_func.html) can be used similarly on [`app_box`](https://github.com/BuddiesOfBudgie/budgie-desktop/blob/07007bf22d20ae1c336013db1baf11686ede9a84/src/rundialog/RunDialog.vala#L128) to set a similar function to `do_sort_list` used in the budgie-menu code. Furthermore, the [`get_score`](https://github.com/BuddiesOfBudgie/budgie-desktop/blob/07007bf22d20ae1c336013db1baf11686ede9a84/src/applets/budgie-menu/BudgieMenuButtons.vala#L113) function can also be reused. For example, by deriving a new class from [`Gtk.ListBoxRow`](https://valadoc.org/gtk+-3.0/Gtk.ListBoxRow.html), adding `get_score` to it and using the derived class in place of `Gtk.ListBoxRow` in [`RunDialog.vala`](https://github.com/BuddiesOfBudgie/budgie-desktop/blob/07007bf22d20ae1c336013db1baf11686ede9a84/src/rundialog/RunDialog.vala).

**Comment by JoshStrobl** [comment]
This should use the same new backing store that would be developed for https://github.com/BuddiesOfBudgie/budgie-desktop/issues/24

Any inconsistencies would be addressed with that.
