### ISSUE TITLE
Add an option to change the spacing between applets

### ISSUE THREAD

**Issue by RichardLuo0** [BuddiesOfBudgie/budgie-desktop#96]
### Current Budgie version
budgie-desktop 10.5.3

### Use-cases
![image](https://user-images.githubusercontent.com/22096448/161233705-6d38bc52-213c-4a77-b010-e3224bfd2b80.png)
I feel like it is too narrow in this area. Using spacer applets between each applet is just too troublesome.

### Proposal
I hope budgie can add a simple option to change the spacing between applets.

**Comment by fossfreedom** [comment]
V10.6.x as well.

implementation of such a request is tricky.  Applets & system tray components dont have a consistent container which would have been useful todo some nifty CSS type changes.

Nothing really a theme maintainer can do I guess unless there is something consistent to latch onto to add padding values.

hmm...

**Comment by serebit** [comment]
We could theoretically pull this off in-code with the GTK `spacing` property on containers, but it wouldn't space out the members of the status applet or members of the system tray. Additionally, it would have to be set per-region even if we add a setting for the entire panel.
